smrealms/smr

- tools/irc/channel_msg_op.php
The `!op info` command will always print turn information,
regardless of registration status. This will prevent tedious
workarounds, such as switching between YES and the desired status.
> channel_msg_op_info: always print number of turns

- lib/Default/SmrPlayer.class.inc
Include the force owner's name in the news entry.
This makes it consistent with player and planet deaths.
> Change format of news entry for force deaths

- engine/Default/trader_relations.php
On the "Trader Relations" page, include relations with Neutral, as is
done in the "Relations (Personal)" section of the "Trader Status" page.
There is no reason to make this exception, because relations with
Neutral can be improved (for Alskant) by trading at Neutral ports.
Including this information for non-Alskant traders doesn't hurt
anything, it will just always be zero.
> trader_relations.php: display all Races

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/universe_create_end.php
- db/patches/V1_6_61_01__view_bonds_option.sql
- engine/Default/alliance_create_processing.php
- engine/Default/alliance_planets.php
- engine/Default/alliance_roles.php
- engine/Default/alliance_roles_processing.php
- engine/Default/trader_planet.php
- templates/Default/engine/Default/includes/AllianceRole.inc
- templates/Default/engine/Default/includes/PlanetList.inc
It would be useful to be able to customize who can see the bond information in the planet list. Rather than only giving the leader *player* this ability, we can give the leader *role* this ability (and we can make it customizable for each role).
This pull request adds a new permission to the "alliance roles" that specifies whether or not they can see the bond information in the planet list. It also adds a commit with very minor cosmetic changes to the alliance roles page.
> Improved bond permissions

- engine/Default/smr_file_create.php
The current behavior of smr_file_create.php is to print "Planet=1"
for sectors that contain planets. However, this behavior was
implemented before there were different types of planets. Since the
planet types are available in the galaxy map, it seems reasonable
to include this information in the .smr file. This patch replaces
"Planet=1" with "Planet=$planetType", where $planetType is the
numerical type ID of the planet.
> smr_file_create.php: print correct planet type

- engine/Default/planet_bond_confirmation.php
- engine/Default/planet_financial_processing.php
- lib/Default/SmrPlanet.class.inc
- templates/Default/engine/Default/planet_financial.php
* Replace the modal dialog with a new planet page that asks for
confirmation of the bond request. This fixes two issues:
1. The modal dialog was very much out of the style and
aesthetic of SMR.
2. The modal dialog text erroneously flashes on the Planet
Financial page before 'Bond It!' is even clicked.
* When a planet is unclaimed, the 'Bond It!' button was displayed,
only to trigger an error if you press it. With this patch, the
button is replaced with text informing the player that the planet
must be claimed to start a bond.
* Slightly modify the description of the bonding mechanics for
clarity (e.g. "money" -> "credits" and "saving bond" ->
"planetary bond").
* Fix logging of bonding amounts. Previously it was logging
$planet->getCredits(), which is zero by definition after bonding. …
> Change the way planetary bond confirmation works

- tools/irc/server.php
When performing a WHOIS, the IRC server used by TheAirlock outputs a
different string in the 307 message. We modify the preg_match
in the server_msg_307 function accordingly.
This fixes ticket #82, but leaves the issue with the NickServ
address (coldfront vs. theairlock) unaddressed.
> server.php: modify regex for server_msg_307 response

- engine/Default/military_payment_claim.php
Follow the protocol in bounty_claim.php for storing a message from
a one-time transaction (in this case, claiming military payment)
so that it can correctly remain on the screen when AJAX refreshes.
Without this fix, the message about claimed military payment is
immediately replaced with the message that there is no military
payment to claim.
> Fix AJAX clearing military payment message prematurely

- lib/Login/SocialLogin.class.inc
- templates/Default/login.inc
SocialLogin.class.inc: prevent Facebook exception
If not specifying a Facebook App ID, return an empty Facebook login link. We do this to prevent an exception in the Facebook authorization code if we were to continue.
Ideally we would perhaps omit the Facebook login object altogether if there is no App ID, but that would require more extensive changes to the login page code. For this minimal change, a non-interactive button is preferable to an Exception.
> Fix a Facebook Login exception when no App ID is provided

- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/TraderCombatKillMessage.inc
This patch provides extra information about how many credits are lost when a player is destroyed by ports, planets, and forces. I don't believe this information is available to the destroyed player in any other form, which seems like an oversight.
The message reads:
"The X credits that were onboard Y's ship are lost in the wreckage."
> Add credits lost message to deaths from ports/planets/forces

- htdocs/login_create.php
- htdocs/login_create_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- tools/npc/npc.php
* Remove the request to provide ICQ information in the registration
page. Asking for that information makes the game look more outdated
than it needs to and significantly lengthens the page.
* Remove the `icq` argument from SmrAccount::createAccount.
This field isn't used anywhere else in the code.
* For simplicity, we don't bother to remove the `icq` column from
the `account` table. It doesn't harm anything to stay there,
since it has a null default.
> Remove ICQ from account creation

- README.md
This directory needs to be created for a successful game build,
so we use .gitkeep to ensure that the directory exists.
> Add .gitkeep in htdocs/upload/

- lib/Default/SmrPlanet.class.inc
The methods {get,set}PlanetID were unused (and non-functional)
duplicates of the {get,set}TypeID methods, so we remove them here.
This is the non-blocking commit from PR #88.
> SmrPlanet.class.inc: remove duplicate methods

- templates/Default/admin/Default/1.6/universe_create.php
Adds some more information to the initial 1.6 universe creation screen (headers and game numbers in the edit game dropdown). Moves the "Edit Existing Games" form to the top of the page, since it is easy to overlook otherwise, due to the much larger "Create New Game" form.
> Minor display changes to 1.6/universe_create.php

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/universe_create_end.php
- engine/Default/alliance_forces.php
- engine/Default/forces_list.php
- engine/Default/preferences_processing.php
- engine/Default/trader_status.php
- htdocs/config.php
- htdocs/email_processing.php
- templates/Default/engine/Default/alliance_planets.php
- templates/Default/engine/Default/council_embassy.php
- templates/Default/engine/Default/council_list.php
- templates/Default/engine/Default/council_politics.php
- templates/Default/engine/Default/council_vote.php
- templates/Default/engine/Default/course_plot.php
- templates/Default/engine/Default/game_join.php
- templates/Default/engine/Default/includes/LeftPanel.inc
- templates/Default/engine/Default/includes/PlanetList.inc
- templates/Default/engine/Default/includes/RightPanel.inc
- templates/Default/engine/Default/newbie_warning.php
- templates/Default/engine/Default/planet_main.php
- templates/Default/login.inc
These two commits replace the following hard-coded URLs with global defines:
* www.smrealms.de (already existed as `URL`)
* wiki.smrealms.de (created new global define `WIKI_URL`)
> Replace hard-coded URLs

- engine/Default/planet_stockpile.php
Since planets can only hold a certain amount of each good,
do not populate the form with default values that are greater
than the maximum the planet can hold.
This change makes the Stockpile page behavior consistent with
the Defense page.
> planet_stockpile.php: better default form values

- htdocs/config.inc
When running php scripts outside of this directory (i.e. the `irc`
or `npc` scripts), the relative path given in the `require_once`
will fail. We use `__DIR__` to make the path absolute, as suggested
in https://stackoverflow.com/a/5371875.
> htdocs/config.inc: fix autoload.php require_once

- engine/1.2/alliance_treaties_processing.php
- engine/1.2/combat_log_viewer.php
- engine/1.2/message_blacklist_add.php
- engine/1.2/planet_attack_processing.php
- engine/1.2/port_attack_processing_new.php
- engine/1.2/trader_attack.php
- engine/1.2/trader_attack_processing_new.php
- engine/Classic 1.6/planet_attack_processing.php
- engine/Classic 1.6/port_attack_processing.php
- engine/Default/message_blacklist_add.php
- engine/Default/port_attack_processing.php
Avoid unnecessary explicit mysql API calls
We remove the explicit calls to `mysql_real_escape_string`
outside of MySqlDatabase.class.inc, because the database
queries already use `$db->escapeString`.
Remove explicit mysql API calls in 1.2 engine
Use the escape_string database method instead of the explicit
API call, and put the escaping inline in the database query.
> Remove explicit mysql API calls outside of the database class

- Dockerfile
Use docker-php-ext-enable to add runkit.so to the php
configuration file.
> Dockerfile: make runkit known to php

- Dockerfile
PHP 5.6 has been extensively tested with the current code base
(the core game, admin tools, Caretaker, and NPC's), with no
compatibility issues. We should update to PHP 5.6, because 5.5
and earlier no longer have security support (see Issue #110).
> Dockerfile: update to php 5.6

- admin/Default/enable_game.php
- admin/Default/enable_game_processing.php
- admin/Default/manage_post_editors.php
- admin/Default/manage_post_editors_processing.php
- db/patches/V1_6_61_02__admin_enable_game.sql
- db/patches/V1_6_61_03__admin_manage_post_editors.sql
- lib/Default/SmrGame.class.inc
- templates/Default/admin/Default/enable_game.php
- templates/Default/admin/Default/manage_post_editors.php
Admins can now be given permission to do the following:
* Enable new games
* Assign or remove Galactic Post editors
A flyway migrate must be run for these options to take effect.
> New admin tools

- admin/Default/anon_acc_view.php
Fixes #104.
The player name database query did not specify a game_id, so it took
the name from the first entry in the database (which would be the
name from the first game that account played). With this patch, the
player name is taken from the specified game.
> anon_acc_view.php: fix Player Name display

- engine/Default/combat_log_viewer.php
- templates/Default/engine/Default/combat_log_viewer.php
Before this file was converted to a template, the combat log viewer
would identify the type of logs in the message (e.g. "There are 4
alliance logs available..."). In the template conversion, the `LogType`
template variable was set, but appears to have been mistakenly unused.
We could have simply removed this variable, but the extra descriptive
message is helpful (even if only to identify what page we're on),
so we add the LogType back in.
> combat_log_viewer.php: include type of logs in message

- templates/Default/engine/Default/alliance_roster.php
Don't show the "Save Alliance Roles" button if the player is not
allowed to change the roles.
> alliance_roster.php: improve button visibility

- templates/Default/engine/Default/includes/SectorLocations.inc
In the "Location" table, there was previously no space between the
location image and text. The added (non-breaking) space gives them
a little room to breathe and doesn't look as crowded.
Before:
After:
> SectorLocations.inc: add a space between image and text

- lib/Default/SmrPlayer.class.inc
In the message sent to planet owners when a planet kills an attacker,
it used a regular space between two HTML tags, which gets removed,
which results in two words being merged into one. We add a `&nbsp;`
to ensure that a space is added between the tags.
> SmrPlayer.class.inc: fix planet message whitespace

- lib/Default/SmrPort.class.inc
After a port has been raided, it gets a bonus to its defences.
Previously, these bonuses could result in a fractional number of
CDs. To avoid this, we simply round the number of bonus CDs.
> SmrPort: avoid fractional CDs during reinforcements

- admin/Default/1.6/universe_create.php
- templates/Default/admin/Default/1.6/universe_create.php
If there were no valid games to edit, the existing games dropdown
would be empty and clicking the "Edit" button would cause a mysql
error.
To avoid this, we omit the dropdown if there are no valid games
to edit, replacing it with some explanatory text.
> 1.6/universe_create.php: handle empty existing games

- lib/Default/SmrPlanet.class.inc
We don't want planets to start becoming habitable before players start
moving, so we have modified the `inhabitableTime` to be at a random
time after players start accumulating turns, rather than after the
game starts. This is because games often start before turns start
accumulating to give players time to create their traders.
NOTE: we use `max(StartDate, StartTurnsDate)` in case `StartTurnsDate`
can be set to before `StartDate`. This likely is an unnecessary
precaution, but it doesn't hurt anything to be careful here.
> SmrPlanet.class.inc: change inhabitableTime

- templates/Default/admin/Default/1.6/universe_create_sectors.php
Once the galaxies are created, there's no way to view the galaxy
details specified at creation (e.g. Galaxy Type, Max Force Time).
We add a small table at the top of the sector creation page, which
displays the galaxy details. This should make it a little easier
to create new games.
> universe_create_sectors.php: add galaxy details

- Dockerfile
Mail support is needed for php to send registration e-mails and
newsletters.
> Dockerfile: add support for sendmail

- lib/Default/SmrPlayer.class.inc
Even though the force owner is displayed as the sender of the
message, we add the force owner in the text for consistency.
This is an extension of PR #69, which added the force owner to
the news entry.
> SmrPlayer.class.inc: include force owner in death message

- engine/Default/planet_stockpile.php
- htdocs/config.php
- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/SmrForce.class.inc
- lib/Default/SmrGalaxy.class.inc
- lib/Default/SmrLocation.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrSession.class.inc
- lib/Default/SmrShip.class.inc
When in debug mode (as defined by `ENABLE_DEBUG` in `config.specific.php`), all php notices will be printed to help catch bugs. A quick pass through the code with these notices turned on revealed a few issues, which are fixed in this PR.
> Improved php debugging

- admin/Default/log_console_detail.php
Logs from different accounts are color-coded, but the color cycle
only has 4 colors. To avoid repeated colors if viewing more than
4 accounts, 2 additional colors (light blue and pink) were added.
The colors that are hardest to read on the dark green background
(red and blue) were moved to the end of the color cycle.
NOTE: Another option would be to include a column for the account
name instead of, or in addition to, the colors.
> log_console_detail.php: add 2 more colors

- admin/Default/log_console_detail.php
- htdocs/config.inc
- lib/Default/MySqlDatabase.class.inc
The `microtime` built-in function outputs a string that looks like:
0.39324900 1504296581
The first word is the number of microseconds in seconds.
The function `microtimeMSec` took the 6 digits after the decimal
from the first word and converted that to an int.
However, if the number of microseconds was small enough to start
with a `0` after the decimal (e.g. `0.09324900`), then casting
the substring to an int would give `93249` instead of `093249`.
Therefore, when reconstructing the time from this value, we would
be one digit off, and you'd get a timestamp from 1974 or so.
[Thanks to Curufir for identifying this issue.]
By having `microtimeMSec` (and `microtimeSec`) return strings instead
of ints, we avoid the casting problem altogether.
We also move the sanity check on the microtime …
> Fix bug in saving MICRO_TIME to the database

- admin/Default/1.6/universe_create_locations.php
- templates/Default/admin/Default/1.6/universe_create_locations.php
When adding locations to a galaxy, the list of locations is very long, and so it is onerous to scroll through whether you're looking for a specific location or a type of location. By adding navigable categories to the list, we make the process of galaxy creation easier. 
We also convert the page to a template.
> Categorize list of locations in galaxy creation

- templates/Default/engine/Default/includes/SectorMap.inc
This if-statement duplicated the checks performed inside it without
scoping any additional html. Therefore it can be safely removed.
> SectorMap.inc: remove superfluous logic

- engine/Default/combat_log_list.php
- engine/Default/combat_log_list_processing.php
- engine/Default/combat_log_viewer.php
- engine/Default/menu.inc
- engine/Default/smr.inc
- engine/Semi Wars/menu.inc
- htdocs/config.php
- lib/Default/SmrSession.class.inc
- templates/Default/engine/Default/combat_log_list.php
- templates/Default/engine/Default/combat_log_viewer.php
Two commits affecting `combat_log_viewer.php`:
1. Major refactor (breaking up into 3 files) to simplify and comment the code. This makes the diff look very large, but most of the difference is code being moved to new files.
2. Switch to named constants to avoid fragile references to the combat log pages.
See the commit messages for more details.
> Combat log viewer cleanup

- admin/Default/manage_draft_leaders.php
- admin/Default/manage_draft_leaders_processing.php
- db/patches/V1_6_61_04__admin_manage_draft_leaders.sql
- db/patches/V1_6_61_05__draft_history.sql
- engine/Draft/alliance_create_processing.php
- engine/Draft/alliance_option.php
- engine/Draft/alliance_pick.inc
- engine/Draft/alliance_pick.php
- engine/Draft/alliance_pick_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/AbstractSmrPlayer.class.inc
- templates/Default/admin/Default/manage_draft_leaders.php
- templates/Default/engine/Default/alliance_pick.php
For draft leaders:
* Draft team status in the "Pick Member" page
* Draft history in the "Pick Member" page
* Make it harder to accidentally pick team members when you're not supposed to
For admins:
* New admin tool to manage draft leaders
* Two database changes (one for draft history, one for admin permission to manage draft leaders)
See the commit messages for more details.
> Draft pick enhancements

- admin/Default/enable_game.php
- admin/Default/manage_post_editors.php
- admin/Default/manage_post_editors_processing.php
- admin/Default/permission_manage.php
* Accessing an array by a key that doesn't exist produces an undefined
index warning. Fix "Undefined index" for "processing_msg" and
"admin_id"by checking to see if the variable is set first.
The variables that we now conditionally set are checked by `empty`,
which does not generate a warning if the variable doesn't exist.
* Fix "Undefined variable: msg" by checking to see if it is empty
before using it.
> Fix some debug-mode warnings in admin tools

- .gitignore
- README.md
- lib/Default/SmrMySqlDatabase.class.inc
- lib/Default/SmrMySqlSecrets.sample.inc
- lib/Default/SmrSessionMySqlDatabase.class.inc
This change simplifies server configuration.
Move the static MySQL database configuration into a separate trait
called SmrMySqlSecrets, which is contained in a separate file from
the rest of the database code. This has several benefits:
* The database configuration only needs to be specified in a single
file, and thus reduces configuration/code duplication and also
reduces the number of files that need to be managed by Docker.
* The rest of the database code now resides in a version-controlled
file, whereas previously it was specified in two user-created
configuration files.
PHP traits require php 5.4+.
> Refactor Smr*MySqlDatabase.class.inc

- docs/.gitignore
- docs/Dockerfile
- docs/README.md
- docs/docker-compose.yml
- docs/phpdox.xml
Use phpdox to generate html documentation for all objects
defined in lib/Default. We use docker and docker-compose
to manage dependencies and run the program.
See docs/README.md for usage instructions.
I have temporarily hosted the documentation generated from
this branch [here](http://54.88.80.238:8081/index.xhtml).
> Add PHP documentation generator

- engine/Default/sector_move_processing.php
Sector movement was incorrectly logged because the target sector
and the current sector were set to the same value. This bug was
introduced in 30a7213e8b16, when logging for sector movement was
wrapped inside the mission actions.
Since 'EnterSector' superseded 'WalkSector' as the mission action
to detect if a player was in a sector (since 'EnterSector' accounts
for jumping into a sector, for example), there is no reason to keep
'WalkSector' as a mission action, since its only purpose was for
logging. Instead, we simply log the movement directly as we did
before the bug was introduced.
> Fix logging of sector movement

- lib/Default/SmrPlanet.class.inc
The `getBuildings` return value does not contain a key
for buildings that have not been built yet. The `getBuilding`
method accounts for this and checks for the existence of
the key.
> SmrPlanet.class.inc: fix index error when 0 buildings

- lib/Default/message.functions.inc
In `getMessagePlayer`, messages sent by a non-player race account
will have a sender `<RACE> Government` instead of just `<RACE>`.
> message.functions.inc: add Government to race name

- engine/Default/planet_kick_processing.php
- lib/Default/SmrPlayer.class.inc
A few calls to `sendMessage` still used integers instead of
named constants.
> Use named constants for sendMessage types

- engine/Default/combat_log_viewer_verify.php
- engine/Default/smr.inc
Now that we have a BB-tag that links to sensitive information (in this
case combat logs), since player messages are bbify'd, you could send
a message to another player with "[combatlog=X]", where X is some valid
combat log ID, and the recipient would then have a link to that combat
log -- even if they would otherwise be unable to see it in the combat
log viewer.
This exploit is unlikely to be discovered (and even harder to abuse),
but since it is theoretically possible, it needs to be prevented.
To do this, we create a security layer between the BBLink and the
displayed combat log page. This layer verifies that the player should
be allowed to access it. Currently, restrictions include:
* Log is from the current game
* Attacker/Defender is the player or in the player's alliance
> Security layer for combat log BBCode links

- engine/Default/chat_rules.php
- templates/Default/engine/Default/chat_rules.php
- templates/Default/engine/Default/includes/LeftPanel.inc
Restructure the page into summary and links. This replaces a
daunting list of rules that either a) you ignore or b) discourages
you from finding your way to the small chat link at the bottom.
* Add a prominent link to the Chat Rules on the wiki
* Add the Discord widget for the public SMR Discord server
> Advertise both IRC and Discord Chat servers

- engine/Default/feature_request_comments.php
- engine/Default/feature_request_vote_processing.php
- templates/Default/engine/Default/feature_request.php
- templates/Default/engine/Default/feature_request_comments.php
Public improvements:
* Requests/comments no longer anonymous by default (checkbox is still there)
* Votes are color-coded
Moderator improvements:
* Option to set feature request status while viewing comments
* Disentangle "Vote" and "Set Status" buttons, so you can only do one or the other at a time
* Use a dummy "Select Status" default option for the status dropdown
Code improvements:
* Fix a couple misleading variable names
> Improve "Request A Feature" pages

- engine/Default/menu.inc
Since Arid planets lack a "Financial" page, we were getting
an undefined index when we queried the `$planetOptions`.
However, `$planet->getOptions(...)` takes care of the check
for existence of the index (and it is cached), so it is an
obvious drop-in replacement that fixes the PHP warning.
> menu.inc: fix PHP warning on Arid planets

- templates/Default/engine/Default/chat_rules.php
The Rules link leads to the wiki, so we probably want to
open the link in a new window so that we're not redirecting
people out of the game.
Thanks JJ for the suggestion!
> chat_rules.php: clicking Rules link opens new window

- db/patches/V1_6_61_06__discord_id.sql
- db/patches/V1_6_61_07__alliance_discord_channel.sql
- engine/Default/alliance_stat_processing.php
- engine/Default/preferences_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/SmrAlliance.class.inc
- templates/Default/engine/Default/alliance_stat.php
- templates/Default/engine/Default/preferences.php
Store a Discord Channel in SmrAlliance
For now, we restrict to a 1-to-1 mapping between accounts and
Discord Channel ID's for any given game. We allow duplicates
across games since alliances may use the same channel for
multiple games.
* SmrAlliance: add `{get,set}DiscordChannel` methods
* MySQL database: add `discord_channel` field to `alliance` table
* Alliance Stats: add field to change/delete Discord Channel ID
----------------------
Store a Discord User ID in SmrAccount
For now, we restrict to a 1-to-1 mapping between accounts and
Discord ID's. We will handle the case of multi support later.
* SmrAccount: add `{get,set}DiscordId` methods
* MySQL database: add `discord_id` field to `account` table
* Preferences: add field to change/delete Discord ID
-------------------------
These …
> Add Discord ID fields to the database

- lib/Default/SmrPort.class.inc
- templates/Default/engine/Default/port_attack_warning.php
* Replace textual scan results ("Your scanners detect...") with a
table that looks like the sector scan results. It gives the page
a little more substance and also makes it more consistent with
how other pages look.
* Add a short bit of roleplaying text to help newer players realize
that raiding a port might not be a good idea. A link to the wiki
port combat page is provided. This was tip for newbies was
frequently requested by players.
* Add number of turrets to the port scan.
> Revamp the port attack page

- Dockerfile
- README.md
- htdocs/config.specific.sample.php
There's no need to keep the smr code in `/usr/share/`.
We can put it in `/`, which shortens many of the paths we
need to specify (e.g. for volume mounts).
> Dockerfile: place smr in filesystem root

- htdocs/config.php
- htdocs/config.specific.sample.php
There is no benefit to specifying the repository path defines
in config.specific.php. These paths cannot be changed, so we
hard-code them into config.php instead of relying on the user
to correctly define them.
Furthermore, having to manually specify `ROOT` can only ever
cause problems. The correct value for `ROOT` can be determined
programmatically using `__DIR__`.
> Move path defines to config.php

- templates/Default/engine/Default/bank_alliance.php
For players without unlimited withdrawal permissions, the variable
`$UnlimitedWithdrawal` is undefined. So first check if it exists
before using it.
> bank_alliance.php: fix undefined variable warning

- htdocs/config.php
Make sure `ENABLE_DEBUG` is defined before it is used.
This bug was introduced in PR #174.
> config.php: fix define ordering error

- admin/Default/changelog.php
- engine/Default/changelog_view.php
changelog.php: fix if version table is empty
If the `version` table is empty, then this page doesn't append to
`$PHP_OUTPUT` and therefore gives a blank page (with a PHP warning).
In this case, we simply add a line saying that an admin must
add an initial version to the database first.
--------------------
changelog_view.php: only create one continue button
If there are multiple versions since last login, then a "Continue"
button will show up for each version, which is unnecessary and
also messes up the formatting.
Move the "Continue" button out of the while loop to fix this.
> Fix changelog

- Dockerfile
This volume mount is incompatible with local dev testing, where
you mount the entire codebase as a volume. Instead, the volume
will have to be managed with the `-v` option (or docker-compose
volume).
> Dockerfile: remove upload volume

- engine/Default/bar_buy_drink_processing.php
The `$num_drinks` variable is only defined when we have purchased
a drink. So check for its existence before using it.
> bar_buy_drink_processing.php: fix PHP warning

- engine/Default/cargo_dump.php
- templates/Default/engine/Default/cargo_dump.php
In addition to the templatization and minor cleanup, there are a small number of visual changes:
1. "Dump" now contains a "(1)" to indicate turn usage more consistently.
2. Good icons are now displayed next to the good name.
> cargo_dump.php: templatize and minor cleanup

- engine/Default/rankings_alliance_vs_alliance.php
* Highlight the "Versus" subheading of "Alliance Rankings" when it is clicked on. It was previously highlighting the "Death" subheading.
* Fix an "Undefined index: alliancer" warning.
> Minor fixes on the Versus alliance rankings page

- templates/Default/engine/Default/includes/RightPanel.inc
The cargo holds section no longer gives a textual indication of
the goods in the holds, only the graphical representation.
Add a tooltip to the image in case anyone (for some reason) is
not familiar with what image corresponds with what good.
> RightPanel.inc: add tooltips to cargo

- engine/Default/alliance_stat_processing.php
Allow alliances to be created and edited without entering an
alliance description.
Two motivations:
* Proliferation of alliances with a description that is just "."
* Omitting a description sends you back to the current sector
screen, and then you have to re-enter all the other information.
> alliance_stat_processing.php: don't require description

- engine/Default/course_plot_result.php
- templates/Default/engine/Default/includes/PlottedCourse.inc
If the start sector is not the current sector or if you are on
a planet, then the existing "Plot A Course" results page is
displayed.
Otherwise, you can immediately navigate the plotted course, so go
directly to the current sector page (which includes the plotted
course summary and action buttons) instead of displaying the
intermediate results page.
Add a "Plotted Course Results" heading to the course results
minipage on the current sector page. This will help identify
the course results to anyone who may never have seen the
intermediate course results page before.
This change helps to streamline the flow of the game.
> course_plot_result.php: forward to current sector

- engine/Default/contact.php
The contact form page shouldn't be titled "Report a Bug". This was
probably a copy-paste error from the bug report page.
> contact.php: fix page title

- templates/Default/login.inc
login.inc: remove duplicate news headers
* Remove "Recent News" header just above game news and rename
"News" in the table to "Recent News". No sense in having two
here when one does the job.
* Rename "News" in admin announcements to "Announcements".
-------------------
login.inc: fix missing links
* Link to "Video Tutorials" on the wiki
* Add support@smrealms.de "Contact" link
Remaining issues:
* Duplicate link to wiki ("Merchant Library" and "Game Manual")
* No "Site Map" link
* Pointless "Home" link
---------------------
Supersedes and closes #161
> Login cleanup

- db/patches/V1_6_61_09__account_shares_info.sql
- engine/Default/chat_sharing.php
- engine/Default/chat_sharing_processing.php
- engine/Default/preferences.php
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/chat_sharing.php
- templates/Default/engine/Default/preferences.php
Provides a new database table `account_shares_info` and an interface
to manage this table.
This will be used to allow users in chat to display information
about more than just the account associated with their Discord ID
(or IRC Nick). It is generic, but the primary motivation is to
allow players to display their main and multi.
> Add chat sharing

- templates/Default/login.inc
Apply CSS from the in-game defaults to the login page so that
the News and Announcements tables (using the `standard` class)
look like the tables in-game.
> login.inc: make standard tables look standard

- templates/Default/engine/Default/bank_alliance.php
Change height of "reason" textarea from 15em to 5em. This is still
probably too large, but it's quite absurd right now considering that
not many people provide a reason at all.
> bank_alliance.php: make reason textarea shorter

- engine/Default/changelog_view.php
Players that haven't logged in for a long time are confronted
with a (potentially) massive list of changes. When the continue
button is at the bottom of the page, this creates a pretty large
barrier of entry.
The continue button at the top of the page ensures that people
a) will immediately know that they have the option to continue
and b) aren't forced to scroll through a list of changes if
they don't care about them.
> changelog_view.php: move continue button to top

- engine/Default/smr.inc
- lib/Default/Template.class.inc
Only pass them by reference if you need to modify them. Passing
a string by value does not create a copy of the string, rather
it increases the refcount of that string object.
Ref: https://derickrethans.nl/talks/phparch-php-variables-article.pdf (among others)
> Don't pass strings by reference for speed

- engine/Default/preferences_processing.php
When altering your player name, a check is done to make sure that
the new name is not already in use. Since `player_name` has a case-
insensitive collation, this prevents players from changing the case
of their name.
With this change, we allow the old and new names to be the case-
insensitively the same so long as the account ID's match.
> preferences_processing.php: allow name case change

- engine/Default/trader_status.php
- templates/Default/engine/Default/configure_hardware.php
configure_hardware.php: clarify no hardware message
Make it clear that hardware is not installed, not necessarily
unsupported.
-----------------------------
trader_status.php: add link to Configure Hardware
Link the "Supported Hardware" text to the "Configure Hardware" page.
> Configure hardware improvements

- engine/Default/smr.inc
- lib/Default/SmrSession.class.inc
The `debug` table has gotten extremely large on the live server
(roughly 1GB), which is the vast majority of the size of the
database.
I think it makes sense only to use this table in debugging
environments, so make insertion dependent on ENABLE_DEBUG
being set.
> Only insert into the debug table in debug mode

- engine/Default/course_plot_cancel_processing.php
- templates/Default/engine/Default/includes/PlottedCourse.inc
Two commits:
* Cancels the currently plotted course. This was a frequently requested feature.
* To avoid confusion between sector numbers and turn cost, add a '#' to the sector number in the plotted course action buttons.
With scanner:
Without scanner:
> Add button to cancel plotted course

- engine/Default/alliance_mod.php
- engine/Default/alliance_op_response_processing.php
- engine/Default/alliance_option.php
- engine/Default/alliance_set_op.php
- engine/Default/alliance_set_op_processing.php
- htdocs/css/Default/Default.css
- templates/Default/engine/Default/alliance_option.php
- templates/Default/engine/Default/alliance_set_op.php
* Allow alliance leaders to manage ops in-game in additon to chat.
* When an op is scheduled, a new block of text will be displayed on the alliance MOD page with an option to respond to the op.
> Add functionality to manage and respond to ops in-game

- engine/Default/sector_jump_calculate.php
- engine/Default/sector_jump_processing.php
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/JumpDrive.inc
- templates/Default/engine/Default/sector_jump_calculate.php
A new option for jump drives is "Calculate Turn Cost". When clicked
it will take you to a new page that says how many turns will be
spent when jumping to the target sector.
I think this is a reasonable addition because previously jump drives
had a fixed turn cost (15), so we could report the cost exactly.
Now the cost is just listed as (10+), which is a little misleading
since the turn cost has no upper bound.
Some additional changes needed for this feature:
* Cleanup in `sector_jump_processing.php`
* Fix an order of operations bug where scout messages could be sent for jumping out of sector when you don't actually jump because you're out of turns
* Refactor jump drive calculations in `SmrPlayer::getJumpInfo`
> Add button to calculate jump drive turns

- engine/Default/alliance_roles.php
Ensure that all role keys are defined for both Create/Edit roles.
> alliance_roles.php: fix PHP warnings

- engine/Default/cargo_dump_processing.php
* When at 0 experience, dumping goods does armour damage, but
will not let you dump if it would take you below 1 armour
(i.e. you can't destroy your ship dumping cargo).
* Armour damage will be holds/5 (e.g. you can dump 4x 300 holds
in an IST before you need to UNO). This number may need to be
adjusted based on feedback.
* There is no rollover. You either lose exp (down to 0) or armour.
* When losing experience, don't show that you lost more experience
than you have.
The official motivation for this change is to ensure that there
is a tradeoff when slaving. When the slave has exp, it can be lost;
but when you slave at 0 exp, there is no longer any tradeoff.
You basically get slaving for free, which was not intended.
Incurring a ship damage penalty seems like a fitting solution.
More …
> Dumping cargo at 0 exp damages armour

- engine/Default/bounty_claim.php
- engine/Default/trader_bounties.php
- engine/Default/trader_status.php
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/trader_bounties.php
* Convert `trader_bounties.php` to a template
* Refactor claimable bounties into the `SmrPlayer::getClaimableBounties` method
* Reorganize bounties display in the "Trader Status" and "View Bounties" pages
Trader Status page now displays (less detailed) information about both bounties on your head _and_ bounties you can claim.
View Bounties page now displays fully detailed information about both bounties you can claim _and_ bounties on your head.
> Improve bounties display

- engine/Default/alliance_leave_processing.php
Previously, the player was removed from the alliance, and then
it used the alliance ID of that player to clean up the disbanded
alliance. But since the player was now in alliance 0, nothing
happened.
This fixes disbanding an alliance so that the appropriate db
entries are deleted.
> alliance_leave_processing.php: fix disbanding

- db/patches/V1_6_61_10__vote_link_callback.sql
- engine/Default/smr.inc
- engine/Default/vote_link.php
- htdocs/vote_link_callback.php
- templates/Default/engine/Default/skeleton.php
Changes to voting sites:
* Remove MPOGD, because it no longer exists.
* Re-add TWD, which seems to be up and running just fine.
I have updated the info for SMR on this site.
Change to code organization:
* Fix a bug where when you weren't in a game, it would always
display that free turns were available. Now it gives you the
correct time when not in a game, but still doesn't give you
the free turns link (since it wouldn't have a game to attribute
them to).
* Implement a callback for the TWD voting. Free turns are no
longer awarded automatically. Instead, TWD is set up to callback
to `vote_link_callback.php` when the player actually votes, and
turns are awarded there.
The callback is implemented by passing the game and account ID
to the vote link in the query string, and TWD will return …
> Reorganize voting for free turns

- htdocs/config.php
With the change to voting that requires completion of a recaptcha,
we want to further incentivize voting, otherwise it may be considered
too much work for too few turns.
The increase from 20 to 30 mins worth of turns for voting was
approved by the admin team.
> config.php: increase VOTE_BONUS_TURNS_TIME to 30 mins

- templates/Default/login.inc
Instead of having "Game Manual" and "Merchant Library" both link
to the wiki, link "Merchant Library" to the photo album.
The idea behind this is that the photo album is (or will be) a
library of merchant profiles/photos.
> login.inc: link Merchant Library to the photo album

- .dockerignore
- docker-compose.yml
These services are not intended to be used for the live server.
They are instead intended for ease of managing services on
development machines.
> Add development docker-compose.yml

- lib/Default/SmrPlayer.class.inc
- tools/discord/commands/turns.php
* `getSharingPlayers`: Factors out the logic that interacts with `account_shares_info`. Needed for chat functions that allow displaying info about multiple players.
* `getTurnsGained`: Computes the turns gained since last player update. Generalizes this formula for any given time with optional cache bypass. This is used by `SmrPlayer::updateTurns`, but also all of the chat functions that display info about turns.
> Add some convenience methods to SmrPlayer

- tools/npc/npc.php
This provides a clearer error message when NPC's have not been
created yet, instead of a message stating that NPC's could not
be unlocked.
> npc.php: add check to see if NPC's created yet

- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/EndingJavascript.inc
The option in User Preferences indicates that it controls the AJAX
Refresh. However, it also controls the hotkeys.
We reduce the scope of the if-statement so that the option now
only controls the AJAX Refresh and not the hotkeys.
> Disable AJAX Refresh no longer disables hotkeys

- db/patches/V1_6_61_11__rename_computers.sql
This was the only good named in the singular, and so it was
always grammatically incorrect.
Requires a database migration.
> Rename Computer to Computers

- Dockerfile
In the php-apache image, the web user is `www-data`, so our
`htdocs/upload` directory needs to be writable by this user.
When mounting a named volume (e.g. the dev docker-compose.yml),
if we set the permissions in the image first, they should carry
over to the named volume.
> Dockerfile: fix upload directory permissions

- README.md
- docker-compose.yml
In the dev environment (where the local source code is mounted in
the container), we previously mounted the repository root.
This had the unpleasant side effect that you had to run `composer
install` in your host environment, which requires you to download
and correctly configure all the PHP dependencies, defeating the
purpose of using docker in the first place.
However, if we mount only the relevant source code directories,
then you retain the `vendor` directory that is created by the
`composer install` in the image, and then you no longer need to
install _any_ dependencies on the host. This is well worth the
slightly enlarged list of mounts.
> Do not require a composer install for dev env

- engine/Default/cargo_dump_processing.php
- engine/Default/shop_goods_processing.php
Players can track what ship you're in with public visibility of
number of goods traded, which is not an intended side effect of
the Current HoF.
This HoF category was requested to be removed, but that was likely
before HOF_ALLIANCE visibility was implemented. The visibility change
should be a sufficient solution.
> Change visibility of (Trade,Goods) to HOF_ALLIANCE

- engine/Default/alliance_forces.php
- engine/Default/forces_list.php
- templates/Default/engine/Default/alliance_forces.php
- templates/Default/engine/Default/forces_list.php
This dramatically improves performance of sorting the force lists,
which gets quite slow once the list is large (as it always is).
We also convert forces_list.php and alliance_forces.php to templates
in the process.
NOTE: in doing this, I believe we lose the ability to secondary sort.
While this was useful, the page loading is so slow that it loses its
convenience (you need to load the page 4 times just to sort by
desc mines with asc expire time, which is typically the only case
where secondary sorting is used). However, secondary sorting can
be re-implemented by adjusting the list.js sort function, if it is
requested.
> Use list.js to sort personal and alliance force lists

- htdocs/config.php
While a more comprehensive solution to newbie deaths is needed,
a stopgap solution is to simply give some more starting newbie
turns to newbies.
I think we won't know the "correct" amount until we have more
new players, but we'll start with a conservative increase to
750 from 500.
> config.php: increase starting newbie turns for newbies

- README.md
- docker-compose.yml
An officially docker image for Flyway recently became available.
We will use the alpine version, since it is significantly smaller
(100MB from ~600MB).
Note that the latest version is Flyway 5, so if you used an earlier
version on an existing database, you will get a warning about the
Flyway table name change (which will be an error in Flyway 6).
While the warning recommends changing the `flyway.table` property,
it is simpler to just rename the table from `schema_version` to
`flyway_schema_history`.
Flyway 5 finally provides a command to undo migrations. Yay!
> Switch to offical Flyway docker image

- engine/Default/message_view.php
- templates/Default/engine/Default/message_view.php
The template was previously set up to _always_ display individual
messages before grouped messages, which meant that if the only
new (*) messages were grouped, they would display at the end of
the list, even if it meant that old individual messages displayed
above them. This is not correct, because new messages should
always display at the top.
The engine starts to set this up correctly, by adding new messages
to the message array first, then unread messages second. However,
it then puts them into separate arrays ('Messages' and 'Grouped
Messages'). If we instead put them into the same array, then
the ordering works out correctly in a completely natural way.
As a result of this simple change, we can actually remove _all_
special casing for grouped messages in the template.
> message_view.php: fix ordering of scout messages

- engine/Default/planet_ownership.php
- templates/Default/engine/Default/planet_ownership.php
When you go to claim a planet, it is often annoying to check to
see if you already own a planet (especially now that we have multis).
With this change, a message will be displayed letting you know that
if you take ownership when you already have a planet, you will lose
ownership of that other planet. This implicitly declares the
"one planet per person" rule, which was otherwise not stated anywhere.
Also minor rewording to make the new text fit better in context.
> planet_ownership.php: add message about losing ownership

- engine/Default/current_players.php
- engine/Default/forces_examine.php
- engine/Default/trader_search_result.php
- templates/Default/engine/Default/planet_examine.php
The first argument to `Smr{Player,Alliance}::getAllianceName` is
a bool which, if true, turns the name into a link to the Roster.
Using this option simplifies a few places in the code.
NOTE: This replaces "(none)" in a few spots with "No Alliance",
in particular the Current Players and Trader Search Results pages.
The disparity was a result of not everything using the standard
methods. I somewhat prefer the former, but may wait for feedback
before I change it.
> Use getAllianceName(true) where possible

- engine/Default/alliance_broadcast.php
- engine/Default/alliance_exempt_authorize.php
- engine/Default/alliance_forces.php
- engine/Default/alliance_leadership.php
- engine/Default/alliance_leave_confirm.php
- engine/Default/alliance_message.php
- engine/Default/alliance_mod.php
- engine/Default/alliance_option.php
- engine/Default/alliance_planets.php
- engine/Default/alliance_remove_member.php
- engine/Default/alliance_roles.php
- engine/Default/alliance_roster.php
- engine/Default/alliance_set_op.php
- engine/Default/alliance_stat.php
- engine/Default/alliance_treaties_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/SmrAlliance.class.inc
- templates/Default/engine/Default/includes/RightPanelPlayer.inc
- templates/Freon22/engine/Default/skeleton.php
This is the second argument, after `$linked`.
If true, will append `' (' . $this->allianceID . ')'` to the
alliance name. This happens to fix a missing space problem
between the alliance name and ID in the right panel.
Also add this argument to `SmrPlayer::getAllianceName`, which
forwards to the `SmrAlliance` method.
> Add includeAllianceID argument to SmrAlliance::getAllianceName

- htdocs/js/ajax.js
The issue
=========
When "Auto Refresh" is disabled in preferences, then the
`startRefresh` function will not be called. However, when the
browser regains focus, it will begin to refresh with NO delay.
This is a result of the way the `onfocus` and `startRefresh`
functions interact in ajax.js.
The solution
============
One way to solve this problem is to disable the refresh by
default in ajax.js, and ONLY enable it if `startRefresh` is
called. This ensures that ajax updates will only occur if the
"Auto Refresh" preference is enabled.
--------------
This depends on PR #239. To review, please just look at the diff for the top commit in this PR.
>  ajax.js: fix refresh ignoring disable

- db/patches/V1_6_61_13__alliance_discord_server.sql
- engine/Default/alliance_mod.php
- engine/Default/alliance_stat_processing.php
- lib/Default/SmrAlliance.class.inc
- templates/Default/engine/Default/alliance_stat.php
Adds a "Discord Server" option to the Alliance Stats page, which when set will enable the Discord widget to display on the Message of the Day page.
Also improved descriptions and links for the chat-related Alliance options.
On Alliance Stats page:
On Message of the Day page:
> Alliance option to add Discord widget

- .travis.yml
- admin/Default/universe_create_end.php
- admin/Default/universe_create_ports_processing.php
- engine/1.2/album_edit_processing.php
- engine/1.2/smr.inc
- lib/Default/DummyShip.class.inc
- lib/Default/smr.inc
- tests/phplint.sh
Script to perform basic linting checks on the entire source code.
These checks are by no means sufficient, but they are a necessary
check with complete coverage.
Fixes the following fatal errors:
* As of PHP 5.4, call-time pass by reference was removed.
Function calls no longer require specifying the `&`.
* hex2bin was added in PHP 5.4. Since we require PHP 5.4+,
remove the redeclarations of this function.
* universe_create_end.php: fix missing semi-colon
> Add tests/phplint.sh

- admin/Default/info.php
- admin/Default/info_check.php
- db/patches/V1_6_61_14__remove_unused.sql
* `planet_has_goods` table
* `address`, `city`, `{postal,country}_code`, `icq` fields of the
`account` table
These are unused (or were never used), and they clutter up the
database.
> Remove some unused database elements

- templates/Default/engine/Default/port_attack_warning.php
This page contained a `<table>` element inside a `<p>`, which is
invalid HTML. There is no standard way to parse this, and the
DOMDocument parses it differently than the browser. This
results in the `<p>` element shifting after the auto-refresh.
We replace the `<p>` with `<br />` to avoid this problem.
> port_attack_warning.php: fix shifting elements

- admin/Default/album_moderate.php
- engine/Default/album_edit_processing.php
* A major piece of error checking logic was in the wrong order,
which resulted in displaying a broken profile for moderation.
We now check the account_id first before trying to display
any errors.
* Add a "<<Back" button link instead of making the `<h1>` header
the back button.
* Prefix player name with "Album Nickname" so it's clear what
is being displayed.
* Fix a few PHP warnings about undefined variables.
> album_moderate.php: fix errors

- templates/Default/engine/Default/includes/AllianceRankings.inc
If the player is not in an alliance, don't try to tell
them what rank their alliance is!
Omit the sentence "Your alliance is ranked..." if not
in an alliance.
> AllianceRankings.inc: fix undefined variable warning

- admin/Default/info.php
- admin/Default/universe_create_galaxies.php
- lib/Default/SmrSession.class.inc
The function `getRequestVar` gets a variable preferentially from
* `$_REQUEST`
* The session $var
* A default value (if specified)
* null
This greatly reduces the boilerplate in each file, and reduces
the likelihood of making a mistake setting the var (which is
a common source of back-button errors).
The two extra commits utilize this function to fix back-button errors.
> SmrSession: add helper function to get $_REQUEST data

- lib/Default/SmrPort.class.inc
Do a little minor wordsmithing to make it flow better, and be
a bit less redundant (re: "federal government").
* Remove the span around the alliance, because you can't change
the color of BBLink text.
* Add "creds" span around the bounty.
New message:
Old message:
> SmrPort: improve the port raid news message

- templates/Default/engine/Default/shop_weapon.php
This is useful primarily when you have a large list of weapons
(e.g. Race Wars Weapons) and you want to figure out which weapon
to buy.
It is not ideal for buying the same weapon multiple times,
because after you buy a weapon the sorting reverts.
I don't think it's a blocking issue due to the limited use cases.
(Perhaps in the future, more globally, we can have some system
in place to preserve client-side sorting using ajax and sessions,
for example.)
> shop_weapon.php: use list.js to sort weapons for sale

- lib/Default/SmrAlliance.class.inc
* Make the ctor protected to enforce using the cache
* Switch the order of arguments in the ctor, since I more than
once put the arguments to `getAlliance` in the order that
they're passed to the ctor.
> SmrAlliance: change ctor interface

- lib/Default/SmrPort.class.inc
* Remove code for tier 4 goods (since they don't exist).
* Add `SmrPort::selectAndRemoveGood` method to refactor common code in `doDowngrade`.
> Simplify port leveling code

- db/Dockerfile
If we want a completely sourceless live server environment, then
we will need to have an image for the database patches.
> Add flyway migration Dockerfile

- Dockerfile
- composer.json
- tools/discord/Dockerfile
- tools/discord/composer.json
- tools/irc/Dockerfile
- tools/irc/composer.json
- tools/npc/Dockerfile
- tools/npc/composer.json
The mysqli database connector has been working without issue
for a while now, so we can safely remove the deprecated mysql
connector.
This is the next step on our transition to PHP 7.
> Do not install mysql PHP extension

- tools/discord/Dockerfile
- tools/irc/Dockerfile
- tools/npc/Dockerfile
Avoid unnecessarily invalidating the layer cache by only copying
required subdirectories of the source code.
> tools/*/Dockerfile: only copy needed libs

- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrSector.class.inc
Replace some frequently called instances of the mysql escaping functions with the stored `SQL` member (or add it where it doesn't exist, i.e. `SmrSector`).
The string escaping on most pages is the 2nd highest cost behind the mysql queries themselves, clocking in around ~5%. The cost is probably mostly due to the sheer number of calls, which is often between 300-1000.
In this PR, we try to address the most frequently duplicated escaping.
> Use the stored SQL member when possible

- lib/Default/AbstractSmrAccount.class.inc
The previous implementation of these methods used `getRank`,
which has to query the user stats in the database. This gets
especially expensive when you're doing it for a list of players:
* Current Players list
* Rankings
* Alliance rosters
* Current Sector Players list
By switching to `maxRankAchieved` for these methods, we can
use data that we already have for the `SmrAccount` (no extra
database calls), which significantly speeds up these pages.
This does mean, however, that there may be a time when a player
has technically reached Fledgeling (the first veteran rank) but
is still reported in italics (Newbie/Beginner). I do not think we
need to be rigorous about this, because it is never reported
inconsistently and the player's `maxRankAchieved` will be updated
next time they log in (or …
> SmrAccount: make is{Newbie,Veteran} less expensive

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/album_approve.php
- admin/Default/album_moderate.php
- engine/Default/album_edit.php
- engine/Default/bar_gambling_processing.php
- engine/Default/buy_ship_name_processing.php
- engine/Default/trader_status.php
- htdocs/album/index.php
- htdocs/graph.php
- lib/Album/album_functions.php
- templates/Default/engine/Default/includes/RightPanelShip.inc
- templates/Default/engine/Default/message_view.php
- templates/Default/login.inc
References to internal content do not need to specify the
webserver URL. So we remove it in favor of relative paths.
Less text means less data to serve!
Also fixes a broken link in the NHA message board threads.
> Replace absolute paths in links

- admin/Default/1.6/universe_create.php
- admin/Default/account_edit.php
- admin/Default/admin_message_send.php
- engine/Default/game_join.php
- lib/Default/Globals.class.inc
- lib/Default/SmrGame.class.inc
- templates/Default/admin/Default/1.6/universe_create.php
- templates/Default/admin/Default/account_edit.php
- templates/Default/admin/Default/admin_message_send.php
- templates/Default/engine/Default/game_join.php
The previous call chain for many in-game functions was:
getGameType -> isValidGame -> getGameInfo
However, `getGameInfo` was a fairly expensive function, constructing
a large array for every call, only to have `isValidGame` check if
the result is empty or not. The condition for whether or not it was
empty was if the `SmrGame` constructor threw an exception.
To speed up all these calls, we instead do the `SmrGame` constructor
check in `isValidGame`, so `getGameType` calls no longer need to
do the work from `getGameInfo`.
We also simplify the `SmrGame` ctor check by adding the
`GameNotFoundException` class, and throw that instead of the base
`Exception` if the game is not found.
> Globals: restructure isValidGame

- admin/Default/account_edit.php
- admin/Default/admin_message_send.php
- admin/Default/admin_message_send_processing.php
- templates/Default/admin/Default/account_edit.php
- templates/Default/admin/Default/admin_message_send.php
admin_send_message.php:
* Fix an undefined variable PHP warning using
`SmrSession::getRequestVar`.
* Provide an error message if no account is selected.
Previously it would still report success even if the message
was not sent to anyone.
account_edit.php:
* Use `SmrSession::getRequestVar` to vastly simplify the boilerplate.
* Fix undefined index PHP warnings for `$var['msg']` and
`$var['errorMsg']`.
> Minor cleanup in a couple admin pages

- engine/Default/beta_func_processing.php
- engine/Default/sector_jump_processing.php
- htdocs/map_galaxy.php
- lib/Default/SmrGalaxy.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrSector.class.inc
- lib/Default/smr.inc
In profiling the Current Sector page, I found that a significant
fraction (roughly 10-20%) of the cost was from constructing an
`SmrGalaxy` for every galaxy in the game (see `getGameGalaxies`)
while checking to determine which galaxy the current sector is in.
This was unnecessary since the `sector` table includes the galaxy
containing each sector, which we query instead.
* Replace a few instances of `getGalaxyContaining` with a new
function `SmrSector::sectorExists`, which more clearly indicates
what its purpose is.
* To help with verifying sector existence, add a new exception
`SectorNotFoundException`, which is thrown in the `SmrSector`
constructor instead of the base Exception.
> SmrGalaxy: optimize getGalaxyContaining

- lib/Default/SmrPlayer.class.inc
The `get{...}Players` static functions now get all columns instead
of just the `account_id`. This allows us to pass each row to the
`SmrPlayer` ctor, rather than just passing the `account_id` and
having to perform an additional db query for _every_ other player.
Other minor changes:
* Fix a bug where `getAlliancePlayers` wasn't correctly passing
`forceUpdate` to `getPlayer`.
* Pass `$accountIDOrResultsArray` to `getPlayer` by reference to
avoid potentially copying a large array.
> SmrPlayer: single db query for grouped calls

- db/patches/V1_6_61_15__request_type_accepted.sql
- engine/Default/feature_request.php
- templates/Default/engine/Default/feature_request.php
- templates/Default/engine/Default/feature_request_comments.php
This status will help organize the (dauntingly long) list of open
feature requests. Many are good ideas that I plan to implement,
but they continue to clutter the list of open requests that still
need to be dealt with. It will also help give players some quicker
feedback about what is and isn't planned for implementation.
Also reformatted the category display:
* Include a table of categories with descriptions and counts.
* Include the currently viewed category in the table, and
highlight it in bold.
* Display the currently viewed category in the page heading.
One of the most useful changes is the description of what a "New"
request is. Make the threshold for this category a variable,
and change it from 14 days to 30.
> Add "Accepted" category to feature requests

- lib/Default/AbstractSmrShip.class.inc
- lib/Default/SmrShip.class.inc
There are up to 11 pieces of hardware at the moment, but often
only one of them is changing at a time (e.g. shields/forces).
However, we previously would update every value if any single
hardware amount changed, resulting in up to 10 unnecessary db
queries.
Because of `set{Old}Hardware`, it is easy to keep track of
which hardware has changed, and only perform the db query to
update those that have changed.
> SmrShip: only update hardware that has changed

- engine/Default/hall_of_fame_new.php
Currently, if you want to see the "HoF -> Planets" page, you have
to click on the "Buildings" button in the "Planets" subcategory,
and then click "Planets" in the breadcrumb you get on that page.
This Category link allows you to go directly to the subcategory
page.
> HOF: make categories link to the subcategory

- lib/Default/SmrPlayer.class.inc
While `killPlayer` (which is called for all death types) does some
HOF work, there were some generic stats that were only done in
`killPlayerByPlayer` (e.g. Dying:Experience:Lost)
With this change, force/port/planet deaths contribute to the generic
stats but also have their own sub-categories.
This was reported in a 2011 bug report! :D
> SmrPlayer: add HOF stats for deaths to forces/ports/planets

- lib/Default/SmrForce.class.inc
In the style of `SmrPlayer`, allow passing a db query result
into the `SmrForce` constructor, which then skips the db query
inside the constructor. This allows us to then perform a single
query in `getSectorForces` to avoid the cost of performing a
query for _every_ stack of forces in a sector.
* Modify `getForce` and `SmrForce` ctor to take a
`gameIDOrResultArray` as the first argument.
* Fix a bug with `forceUpdate` that would have prevented
`getSectorForces` from updating the cache correctly (but this
option was not in use, so the bug was only theoretical).
-------------------------
Additionally, remove duplicate db query in `SmrForce` ctor.
Deletion of expired forces is also performed in `tidyUpForces`,
which is called by every public method that gets an `SmrForce`.
But in these …
>  SmrForce: single db query for grouped calls

- lib/Default/SmrShip.class.inc
As Page pointed out in #305, this lock probably doesn't provide
any useful security.
* Race conditions on hardware would likely only occur in the same
sector (and would be protected by the sector lock).
* The hardware amount could still change between when it is
queried and when it is updated in the database, and we don't
re-query, so it wouldn't protect against race conditions.
* Since it doesn't lock on the sector level, someone laying mines
in one galaxy could block someone from unoing in another galaxy.
So we remove the lock!
> SmrShip: remove table lock from updateHardware

- db/patches/V1_6_61_16__player_npc_field.sql
- engine/Default/game_join_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/SmrPlayer.class.inc
We often have to get the display name for a list of players.
Since we append "[NPC]" to the display name for NPC players,
we have to check if each player is an NPC, which entails:
1) querying the associated account to get the account login
2) cross-checking the login with the `npc_logins` table
These two queries triple the already large expense of displaying
lists of players.
By adding a boolean `npc` field to the `player` table, we
can entirely avoid this additional cost. (This could also be
achieved with a compound query, but the boolean is the simplest
and most efficient solution.)
> SmrPlayer: add npc field

- engine/Default/course_plot_nearest_processing.php
- engine/Default/course_plot_processing.php
- engine/Default/sector_jump_processing.php
- engine/Default/sector_move_processing.php
- lib/Default/Plotter.class.inc
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/PlottedCourse.inc
The progress you have made will remain until you cancel or reach
your destination (or trigger some other condition that cancels
the plotted course). Jumping will not cancel your course, either.
* If you move to a sector that is not linked to the next sector in
the course, you will lose the "Follow/Scan Course" links on the
Current Sector page. When you move back to a sector that is linked
to the next sector, you will regain those links.
* When off the course, you will have a "Replot Course" button,
which will replot to the original destination sector, but
starting from your current sector.
* If you re-enter the course at some later point in the chain, the
course will be updated to remove all the sectors you skipped.
This is implemented with a simple modification to Plotter.class.inc.
By …
> Moving off course does not delete plotted course

- engine/Default/bar_lotto_claim.php
People have been getting the "Multiple actions" error when
claiming a lotto prize.
In a debug environment, claiming a lotto prize resulted in
trying to call `fetch_assoc` on a boolean within `$db->nextRecord()`.
I believe this is because it was a `while`-condition, but within
the `while`-loop, `$db` was modified by additional queries.
Since we know there is only one entry we will be getting, we can
use `if` instead of `while`, which fixes the issue in debug.
What is very strange about the live environment is that the ticket
is deleted, but they don't get the money. The only way this makes
sense to me is if `$player->update()` is not called if a
"Multiple actions" error is encountered. I suppose it must be...
> bar_lotto_claim.php: fix claim error

- admin/Default/ip_view_results.php
Using the "List All IPs for specified logins" option resulted in
a database error:
Unknown table 'ip'
This was because the query was missing the `ip` alias for the
`account_has_ip` table.
> ip_view_results.php: fix mysql error

- engine/Default/rankings_alliance_experience.php
- engine/Default/rankings_alliance_kills.php
- engine/Default/rankings_alliance_profit.php
Fix filtered alliance rankings
Reported by Bouncer in 2013:
Under Alliance rankings, the top 10 are fine. If your alliance is
out of the top 10 though and is shown in the lower section (say 10-20),
the ranking on the left-hand side still says 1-10.
----------------
rankings_alliance_profit.php: fix rankings if 0 profit
For alliances with no profit, they would show up as rank 0 because
the `amount` field in the query would be null. We fix this in the
same way as in `rankings_player_profit.php` by using COALESCE to
return the amount (if it exists) or 0 (if it doesn't).
> Fix alliance rankings

- lib/Default/gov.functions.inc
The bounties heading was hard-coded to "Most Wanted by Federal
Government" for both HQ and UG. It now correctly says "Most Wanted
by The Underground" at the UG.
> gov.functions.inc: fix display for UG

- lib/Default/Globals.class.inc
A couple methods were not static, but were called statically.
Make them static, since they can be (and should be, since all other
`Globals` methods are static).
> Globals: fix non-static methods called statically

- lib/Default/Globals.class.inc
The bar processing pages (buy water, buy drink, and claim lotto)
have no display, so there is no point to including them from
within `bar_main.php`.
> Globals: don't include processing pages with bar_main.php

- templates/Default/engine/Default/includes/ForceTraderTeamCombatResults.inc
The combat vs. forces results display was incorrect when combat
drones would kamikaze, but also destroy additional forces.
We fix and simplify the display logic here.
> ForceTraderTeamCombatResults.inc: fix kamikaze display

- engine/Default/bar_lotto_claim.php
- lib/Default/bar.functions.inc
* Make it clearer that the prize must be claimed before the
next drawing. (We can probably be more explicit, but this
message will at least help a little.)
* Change the old lotto news deletion so that it doesn't depend
on the specific message. Presumably this was written before
the "lotto" news type was added.
> Clarify lotto news message

- templates/Default/engine/Default/includes/PlanetListFinancial.inc
Arid planets don't have a "Financial" page, so you can't put
credits or bond on those planets. It might be confusing to
simply omit those planets, so we add a message stating that
they do not support financial stuff.
> PlanetListFinancial.inc: special case for Arid planets

- engine/Default/forces_drop_processing.php
If we know that the only reason no forces are added is because
the stack can't take any more of the forces the player tried to
drop, then say so in the error message (rather than "You want to
add/remove 0 forces?", which can be confusing for someone who
doesn't know there's a cap on force stack size).
This was suggested by RCK in 2012.
> Better error message when a force stack is full

- engine/Default/game_play.php
- engine/Default/games_previous_hof.php
The `hall_of_fame_new.php` script only works for 1.6 games. For
the old history databases (pre-1.6 games), this script causes a
database error.
We don't do anything special with this new script, just present the
stats in the simplest way possible.
Current account's stats are highlighted.
----------
NOTE: the "Rankings" db query inserts `$var['stat']`, which is a user-specified column name. This is currently not escaped in any way, so presumably is susceptible to injection. I'm not sure if there is a standard way to escape column names in this code.
> Fix broken HoF links for pre-1.6 games

- engine/Default/shop_goods.php
- engine/Default/shop_goods_processing.php
- engine/Default/shop_goods_trade.php
- engine/Default/smr_file_create.php
- lib/Default/RouteGenerator.class.inc
- lib/Default/SmrPort.class.inc
- templates/Default/engine/Default/includes/SectorMap.inc
- templates/Default/engine/Default/includes/SectorPort.inc
- templates/Default/engine/Default/port_loot.php
- tools/testDistancePlotters.php
**Serialize without modifying the port**
Break the `goods` member into three more logically distinct
members: `goodIDs`, `goodAmounts`, and `goodDistances`.
The `goodIDs` are broken up into "Buy", "Sell", and "All Goods"
arrays as before, but the latter two are simple assoc. arrays.
We will omit `good{Amounts,Distances}` in the serialization,
and only keep the `goodIDs` (which is all the cached port
users need).
We can also avoid modifying `cachedVersion` by setting this
to true in `__wakeup` instead of `__sleep`. This is because
the port we are serializing is not cached -- only the one
we get when we unserialize.
Code is included in `__wakeup` to temporarily permit unserializing
old port caches (this can be removed after any running game is
over).
(Note: below, a "good" means the lengthy …
> Restructure port data storage to improve serialization

- db/patches/V1_6_62_02__port_refresh_time.sql
- lib/Default/SmrPort.class.inc
We add a `last_update` field to the `port_has_goods` table
(and remove it from the `port` table).
This allows us to make two major improvements:
1. Restock each good individually. This fixes the bug
where refreshing the port page artificially increases
the rate at which goods restock.
2. Only perform db queries to update good amounts that have
been modified by a human (i.e. are non-deterministic).
This is especially useful because it avoids a large number
of queries that were executed just by passing through a
sector with a port.
Interface changes:
* `getLastUpdate` has been removed.
* `setGoodAmount` is now private instead of public, and has a 3rd
argument `$doUpdate` to specify whether or not this change should
be reflected in the database.
------
This depends on PR's #272 (for DB …
> SmrPort: restock each good individually

- engine/Default/shop_goods.php
The middle panel ajax is disabled on the main port page (because of
the input elements, see `Template::checkDisableAJAX`).
However, we often find ourselves refreshing the port page to see
the supply/demand incrementing, so we add the `ajax` class and a
unique id to its column to enable ajax on that specific element.
NOTE: if using this to watch for supply to increase enough to
complete a trade, the player will have to remember that the auto-fill
value for the trade will not change (since auto-updating that with
ajax would obliterate any attempt to fill in the form manually).
> shop_goods.php: allow supply to ajax update

- engine/Default/trader_status.php
- lib/Default/SmrPlayer.class.inc
- tools/discord/commands/turns.php
Add a countdown in the Trader Status page until max turns will be
reached. This feature was requested by players.
Since this is already calculated in the `turns` Discord command,
we factor the calculation into the `SmrPlayer::getTimeUntilMaxTurns`
function.
> trader_status.php: add countdown to max turns

- lib/Default/SmrPort.class.inc
Proposed changes for Game 118 were too drastic. With them, a /21
felt safe taking a level 6 port solo, so we tweak the numbers to
inspire a little more fear of lower level ports (but not as much
as before).
Below are the changes from the original proposal to the final
values for Game 118.
Base drones:      500 -> 725 (previously 1000)
Drones per level: 125 -> 100 (previously 70)
Base profit:      2.1M -> 2.7M (previously 3M)
Profit per level: 1.6M -> 1.5M (previously 1.5M)
See the [spreadsheet](https://docs.google.com/spreadsheets/d/1LAt0H8G8IHeGhwIIRtpf8gU1_mo3ardzM19kPZ5-4hQ/edit?usp=sharing) for effect at all port levels. (Make sure you're on the Game 118 Proposed tab.)
> Game 118 port combat changes

- engine/Default/planet_financial_processing.php
- templates/Default/engine/Default/planet_financial.php
The planet balance and bond can be ajax updated by wrapping them
in a span with a unique id.
The balance is always displayed, so we can span just the number.
However, the bond message is omitted if there is no bond, so we
need to the span around the entire sentence (and outside the
conditional).
>  planet_financial.php: ajax update financial page

- lib/Default/SmrPort.class.inc
- templates/Default/engine/Default/port_attack.php
Previously, you were unable to raze a level 1 port.
Now, it will remove one of the existing T1 goods and
replace it with another.
At some point in the distant past, all level 1 goods
were rearranged when a level was busted. This seems like
a nice compromise between the two.
Note that this only affects razing. Levels still cannot
be busted at level 1 by shot damage.
> SmrPort: swap one good when razing Level 1 port

- lib/Default/SmrPlayer.class.inc
* Fix the formulas so that they cannot trigger a DB error:
- Scale the loss/gain by the max level so that the bounds
are independent of the absolute magnitude of the level.
(This was still an issue for Defense World planets, which
had a much higher max level than other planet types.)
- As an extra precaution, to ensure that the death is fully
processed, take the `max(0, $expLoss)`.
* Retool the exp loss/gain percentages:
- Death to forces: 30% -> 25% (this could be much lower still)
- Death to ports: [22, 30]% -> [20, 28]%
- Death to planets: unchanged (as calibrated for level 70)
- Death to players: [-0.5, 24.5]% -> [5, 25]%
- Gain on kill: [2, 8]% -> [2.5, 12.5]% (half the loss)
The rationale for the changes are:
1) Force deaths were way too punishing and many people have
complained …
>  SmrPlayer: change exp loss/gain on death

- engine/Default/cargo_dump.php
The right panel needs to query the ship cargo anyway (and it does
so through the `SmrShip::getCargo` method), so we use the same
method here to take advantage of the cache.
> cargo_dump.php: remove redundant db query

- lib/Default/AbstractSmrShip.class.inc
- lib/Default/SmrShip.class.inc
When ship cargo changes, the data in memory is not consistent with
the data when it is loaded from the database. This means that the
cargo will be displayed one way when it first changes, and then on
the next page it will be displayed differently.
I found at least two scenarios where this occurs:
1. When you have more than one good and then sell or dump one of
the goods, it will then display with zero amount (e.g. "Ore: 0").
To fix this, we remove the field from the cargo property when
we delete it from the database so that it never shows up at all.
2. When you already have one good in your cargo and you buy a
second kind of good, if the second good has a lower ID than the
first, it will display after the first good, and then switch
on the next page. If we sort the cargo property when we …
> SmrShip: update cargo display immediately

- engine/Default/council_vote.php
- engine/Default/shop_goods.php
- engine/Default/trader_relations.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/DummyPlayer.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/council.inc
- templates/Default/engine/Default/council_vote.php
- tools/npc/npc.php
Remove the "our relation with them / their relation with us"
paradigm in favor of a single global relation between two races.
This feature was requested in 2015.
Effect on game dynamics
=======================
Due to the reduced number of players, sometimes races don't have
any active players. This makes it impossible for other races to
ever interact with that race. For the benefit of those still
playing, this change gives them the ability to make slow progress
towards peace with a defunct race.
Since there are 7 other races, which could all in theory be
choosing to change relations with your race, you are no longer
in direct control over your relations. You can still counter some
of them with your votes, and you still have the trump card: a
war vote, which will allow any active council …
> Bilateral Relations

- engine/Default/changelog_view.php
* Increase font size
* Make headers more distinctive (yellow green color)
* Increase spacing between bullets
I realize this can (and should) be done with CSS, but since the
live server is still not dockerized, players will not see CSS
changes right now.
> Make changelog more readable

- admin/Default/newsletter_send_processing.php
When sending newsletters in bulk, we want the From address to be
consistent (newsletter@smrealms.de) and the Reply-To address to
be unique (bounce_<account_id>@smrealms.de) for the purpose of
unsubscribing from e-mails.
This is recommended by Google's bulk sender guidelines.
> newsletter_send_processing.php: swap From and Reply-To

- htdocs/css/Default.css
For pages that are too long, the browser adds a vertical scrollbar.
Because the page content is centered, the added scrollbar shifts
the content every so slightly to the left.
By making the page width only as wide as the viewport width _minus_
the scrollbar, adding the scrollbar no longer perturbs the page
content alignment.
See https://stackoverflow.com/a/25981719.
> Default.css: fix shifting page center

- admin/Default/newsletter_send_processing.php
* Move initial AddReplyTo so that we are only ever setting it
once in each of the two logical branches (1. sending to a single
address, 2. sending to all players).
* Remove incorrectly set PHPMailer attribute. `Maile` was a typo
for `Mailer`, so we just remove it (we weren't using smtp anyway).
> newsletter_send_processing.php: minor cleanup

- lib/Default/SmrAlliance.class.inc
- tools/discord/GameLink.inc
The Discord GameLink.inc will no longer return games that have
ended. We do this by checking that `end_date > time()`.
> Don't let Autopilot access games that have ended

- admin/Default/account_edit.php
Fix a bug introduced in cd34fdd0625, which resulted because
`$_REQUEST['account_id']` is _always_ specified due to the way
that the form is set up. I thought the default value would be 0,
but it will always be the empty string if not specified. Then
this empty string caused a `$db->escapeNumber` to fail.
We now explciitly set `$account_id = 0` if it is not specified.
> account_edit.php: fix searching with no account ID

- engine/Default/alliance_leave_processing.php
Don't delete the NHA when the last member leaves, because there
might be more people placed into the NHA in the future.
> alliance_leave_processing.php: fix leaving NHA

- README.md
Dependencies are monitored with VersionEye. This badge provides
a convenient way to remember that we are doing so.
> README.md: add dependency status badge

- lib/Default/SmrPlayer.class.inc
This function was never used. There is a place for a function
like this (to factor out the logic for changing ships, which
does occur in a couple places), but it will need to be rewritten
anyway.
> SmrPlayer: remove changeShip method

- lib/Default/SmrPlayer.class.inc
When a player is killed, their post-death ship can have a different
speed than their pre-death ship, so turns need to be modified.
Having the speed of the escape pod hard-coded in the conversion
causes two problems:
1. We can't safely change the speed of the escape pod.
2. We can't safely allow a ship other than the escape pod
to be given upon death.
Querying the post-death ship's speed instead solves these problems.
In particular, this fixes a bug where newbie players lose extra turns
when they die, because the Newbie Merchant Vessel (the ship newbies
receive post-death instead of the Escape Pod) is speed 9 and the
Escape Pod is speed 7.
> SmrPlayer: remove hard-coded pod speed

- htdocs/js/jquery.hotkeys.js
The list of text-accepting input types specifies which input types
should disable hotkeys when they are selected. The "tel" type
(for phone numbers) was missing, so we add it here.
This fixes the bug where players could not enter cell phone numbers
in their player preferences.
> jquery.hotkeys.js: add tel to text input types

- lib/Default/AbstractSmrShip.class.inc
PHP can't correctly identify that `$this->weapons` is an array
when it isn't initialized, which causes `SmrShip::getNumWeapons`
to emit a warning in PHP 7+ that the argument to `count` must be
Countable.
> SmrShip: initialize weapons as array

- Dockerfile
- composer.json
- htdocs/config.php
- lib/Default/SmrSession.class.inc
- tools/discord/Dockerfile
- tools/discord/composer.json
- tools/irc/Dockerfile
- tools/irc/composer.json
- tools/npc/Dockerfile
- tools/npc/composer.json
- tools/npc/npc.php
Add PHP versions up to 7.2.X in the composer.json file and switch
to the latest PHP 7.2 version in Dockerfile.
Going through the list of backwards incompatible changes from 5.6
to 7.2, I don't see anything that affects the SMR codebase.
NOTE: As of PHP 7.1, the `rand()` and `array_rand()` functions use
a better random number generator, and should be considered usable.
> Allow using PHP 7+

- engine/Default/planet_attack_processing.php
- templates/Default/engine/Default/planet_attack.php
- templates/Default/engine/Default/port_attack.php
Gameplay changes:
- Busting a planet with no defenses now costs the normal planet attack turns and sends a message to the owner's alliance (previously it did not cost turns and sent no message).
Cosmetic changes:
- When a planet is busted, the final message to the owner's alliance indicates that the defenses have been breached.
- Minor spacing adjustments and wording changes to the final port/planet attack pages.
> Minor planet attack changes

- lib/Default/SmrForce.class.inc
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/Missions.inc
See #317.
In strict PHP, you can only assign variables by reference. Things
that are not variables include function calls and constants.
So we begin the herculean task of removing all unneeded references.
Here are some important details about references:
* Objects are always passed/copied by reference (in the c++ sense).
We can pass an object without the `&` and still access/modify
its internal data.
* Arrays are passed/copied by value, but not really because of
copy-on-write, which means that it will only make a copy of
the array if you try to modify it.
* References disable copy-on-write. If you have an array that was
copied by value, and then you take a reference to it, you will
immediately make a copy of it, even if the reference doesn't
modify that array.
Do not use references in an …
> Begin the crusade against references

- lib/Default/AbstractSmrPlayer.class.inc
Computing the player level from their exp is surprisingly expensive
due to the number of times it is called.
To mitigate this many-call cost, we cache the level and then
recompute it any time the player's exp changes.
> SmrPlayer: cache the player level

- lib/Default/SmrPort.class.inc
We no longer need the code to recover the old `port_info_cache`
serializations, because the current game has only ever used
the new serialization routine.
> SmrPort: remove deprecated code

- engine/Default/forces_drop_processing.php
Fixes a bug where forces dropped would vanish from ship if you
encountered an error during processing.
To reproduce the error, you would drop cds/scouts and more mines
than you have, or cds and more scouts than you have. Your ship
would update the cds/scouts or cds, but the force stack would not
have its expire time updated, and so they would immediately
disappear.
To fix the error, we simply perform all sanity checks before making
any changes to the ships. Therefore, we ensure that if any changes
are made, the entire script is processed as expected.
A note is added to explain why we don't update the expire
time automatically every time a change is made. In addition to
that note, there is a specious `$forces->update()` call in the
method that updates the expire time, and so we want to …
> forces_drop_processing.php: fix vanishing forces

- engine/Default/forces_drop_processing.php
I don't see any reason why the "Under Attack" warning should be
removed when you are dropping forces. In fact, the warning can be
missed altogether if you are attacked and then drop a force between
the next AJAX update (or page refresh, if AJAX is disabled).
> forces_drop_processing.php: don't remove under attack

- lib/Default/SmrForce.class.inc
Avoid unnecessary database calls to update SmrForce instances by
utilizing the hasChanged attribute, which can have a dramatic
impact on sectors that have a large number of force stacks.
This attribute had been implemented correctly for a long time,
but never actually used in the `update` method.
> SmrForce: use hasChanged attribute

- lib/Default/Globals.class.inc
- templates/Default/engine/Default/edit_dummys.php
The 'ID' field is redundant with the array keys, so we omit it.
> Globals::getLevelRequirements: omit redundant field

- lib/Default/SmrPort.class.inc
The `increase{Credits,Upgrade,Experience}` are used in favor of
the `add{Credits,Upgrade,Experience}` methods.
> SmrPort: remove unused methods

- admin/Default/account_edit_processing.php
- engine/Default/reopen_account.php
- htdocs/config.php
- htdocs/loader.php
- htdocs/login_processing.php
- templates/Default/admin/Default/account_edit.php
- templates/Default/engine/Default/reopen_account.php
Sometimes users will request that their account be closed (usually
to not receive newsletters anymore). However, it would be nice to
allow these players to reopen their accounts on their own should
they choose to return (since the energy barrier for getting an admin
to reopen is probably too high).
We add a new option to `account_edit.php` that allows admins to
close accounts with the "User Request" reason. This is a special
reason that will trigger the `reopen_account.php` page upon login,
where they can simply press a button to re-open their account.
> Add a way to close accounts but let users reopen

- htdocs/resend_password.php
- htdocs/resend_password_processing.php
- lib/Default/AbstractSmrAccount.class.inc
Players might be discouraged from returning if they cannot remember
their password _or_ login name. To mitigate this concern, we allow
users to request a password reset using e-mail address only.
This change does not make password resets less secure, because you
must own the e-mail address to reset the password, and e-mails are
unique for each account.
It does mean that it is easier to spam someone with unwanted
password reset requests (all you need to know is their e-mail), but
if you want to grief someone, I can think of better ways to do it
than through SMR. Also, since we log the ip address we can take
action against the perpetrator.
> Do not require login to resend password

- engine/Default/game_play_processing.php
- lib/Default/SmrSession.class.inc
- lib/Default/smr.inc
- lib/Login/loginSmarty.php
Add a new method `SmrSession::updateGame`, which changes the
`game_id`, but also ensures that active sessions are unique for
each (account_id, game_id) pair.
This allows players to have multiple games open for the same
account (though in different browsers, due to the nature of the
browser cookies).
This is also an important step towards integrating multis into
the same account as the main.
-------------------
**Prerequisite commit**
SmrSession: remove LIMIT 1 from deletion
One possible solution to (or mitigation of) the infrequent mysql error:
```
Duplicate entry '<hash>' for key 'PRIMARY'
```
is to remove the `LIMIT 1` qualifier from the deletion that directly
precedes the INSERT that is causing this error.
The reason this may help is because certain incompletely understood
race …
> SmrSession: allow active session for each game

- lib/Default/council.inc
The `account` and `npc_login` tables were joined in the query
simply to determine if a player was an NPC. With the addition
of the `player.npc` field, we can omit them from the query.
> council.inc: simplify council query

- engine/Default/login_check_processing.php
We can avoid extra database work by using the `last_login`
information that we already loaded into the `SmrAccount`.
This also makes the checks independent of the structure of
the `account` table.
> login_check_processing.php: simplify checks

- admin/Default/announcement_create_processing.php
The `sizeof` function (an alias of `count`) only works on objects
implementing `Countable`. Strings do not do that, and should use
`strlen` instead.
> announcement_create_processing.php: fix PHP warning

- tools/discord/Dockerfile
- tools/irc/Dockerfile
- tools/npc/Dockerfile
* Switch from php-cli base image to php-cli-alpine.
* Don't install git. It's not needed for installing composer deps.
Image size reductions:
* discord: ~550MB -> ~170MB
* irc: ~410MB -> ~90MB
* npc: ~410MB -> ~90MB
> tools/*/Dockerfile: reduce image size

- engine/Default/message_view.php
Fix "Only variables should be assigned by reference" warnings.
Also remove a bunch of unnecessary uses of references. See #317.
> message_view.php: fix PHP references warning

- templates/Default/engine/Default/course_plot.php
The `sectorId` input element for the form used to move stored
destinations has `type=number`. Somewhere around the transition
to PHP7, it was no longer possible to set the value for this input
from a string with JavaScript. In this case, the `sectorId` input
value would be set to the empty string.
In the JavaScript, the value for `sectorId` is set using the
`data-sector-id` attribute, which is ostensibly an integer. However,
it had an extra space in the value, causing it to be interpreted
as a string. Removing the extra whitespace allowed it to be
interpreted as a number again, thus fixing the bug.
We could also have converted the `data-sector-id` attribute to
a JavaScript `Number`, but that seems to ignore the underlying
problem.
> Fix moving stored destinations

- docs/Dockerfile
* PHPDox was fixed to correctly support PHP 7.2 in the v0.11 release.
See https://github.com/theseer/phpdox/issues/322.
* Clarify that we're using the CLI image variant (note that 7.2 is
the same as 7.2-cli).
NOTE: We would like to use 7.2-cli-alpine for the builder image,
even though it has no effect on the final image, since it affects
the intermediate images for local building. However, PHPDox has
problems with the alpine image (likely due to the poor support
of `iconv`).
> docs/Dockerfile: update to PHP 7.2

- engine/Draft/alliance_option.php
When `alliance_option.php` was converted to a template, the
Draft version of this page broke. It is now fixed.
> Fix drafting option for draft leaders

- engine/Default/bank_alliance.php
- engine/Default/bank_alliance_processing.php
This array was accessed without being defined first, which causes
PHP warnings (but does not affect the functionality).
We initialize the array before it is accessed to prevent these
warnings.
> bank_alliance*.php: initialize playerTrans array

- engine/Default/news_read.php
- engine/Default/news_read_current.php
- htdocs/config.php
- lib/Default/news.functions.inc
Breaking news is often the most important news; however, since we
weren't displaying it with the regular news, we could only see one
breaking news entry at a time. This meant that if, for example, an
alliance attacked multiple planets in an evening, you would only
see the most recent event in the news the next day (and you would
only know the other attacks happened if you were actively refreshing
the news). This doesn't make sense for "important news".
Instead, we will display the news with the regular news, in addition
to displaying the most recent in the breaking news slot. To achieve
this, we also have to stop deleting breaking news entries after one
day (so that they don't disappear from regular news) and change the
query for the "most recent breaking news" to include a one day …
> Display breaking news with regular news

- engine/Default/current_sector.php
- engine/Default/shop_goods.php
- engine/Default/shop_goods_processing.php
Only construct the trade message in `shop_goods_processing.php`
instead of both `shop_goods.php` and `current_sector.php`.
The wording of the two had also become unsynchronized at some
point.
Also correctly pluralize the nouns (points, units, credits).
> Remove duplicated trade messages

- engine/Default/shop_goods.php
- engine/Default/shop_goods_processing.php
Underground ships (Thief / Assassin / DC) can steal goods instead of buying them:
* Stolen goods cost 0 credits
* Maximum exp is earned
Add small chance to get caught stealing goods:
* 1-9% chance to get caught (from Port Level 9 to 1 respectively)
* Fine is `(Port Level + 1) * Ideal Price`
* Lose 5 alignment when caught
>  Allow Underground ships to steal goods

- templates/Default/engine/Default/current_sector.php
Pass `AlreadyDestroyed => false` to the included templates for
minimal combat display. Since `AlreadyDestroyed` is only true
for the trader doing the attacking when there is no combat, we
don't get a combat log and so we know that the minimal display
will not be triggered.
This logic is perhaps a bit convoluted, but would probably need
a refactor to make the logic more automatic.
> current_sector.php: fix mini combat display warnings

- htdocs/css/shared.css
- templates/Default/engine/Default/GalaxyMap.inc
When we are scrolling around the Galaxy Map for large galaxies,
it is a pain to scroll up to the top left corner to change the
galaxy or center on a sector. By having the header in a fixed
position on the page instead, it is always available for use.
Originally, I wanted the header to have a solid background that
would overlap (and obscure) the galaxy map, and then a little
jQuery button that would minimize the header. I didn't know how
to implement this, so I settled for a transparent background,
but no ability to minimize the header. This means the galaxy
map is always slightly obscured, and the header is a bit harder
to read when it overlaps the galaxy map, but I think it is
better than obscuring a significant portion of the galaxy map.
Since I was using pure html/css, I also was …
> Allow header to overlay Galaxy Map

- engine/Default/games_previous.php
For compatibility games, the database query was extracting the
start/end dates in a date format rather than seconds since epoch.
We were then trying to pass those dates through the PHP `date`
function, which was not valid. It would emit a warning and then
display the date as 1/1/1970.
Now we simply select the start/end dates in seconds since epoch
and convert them to date format in PHP like we do everywhere else.
> games_previous.php: fix start/end dates

- engine/Default/sector_jump_calculate.php
- templates/Default/engine/Default/sector_jump_calculate.php
When displaying jump calculation, also show the maximum number of
sectors that can be misjumped.
> sector_jump_calculate.php: add max misjump

- Dockerfile
* Do not explicitly install curl and json php extensions. These are
already installed in the php-apache image. As a result, we do not
need to install the curl-dev package.
* Install zip/unzip instead of git. The former is the preferred way
to install composer dependencies.
This also reduces image size from ~500MB to ~450MB.
> Dockerfile: simplify apt installs

- lib/Default/Plotter.class.inc
Fix typos in `Plotter::findReverisblePathFromX` when it was added in
1adb4c1e4d62. These typos allowed players to plot to any location
in the universe, even if they hadn't scouted it.
I've also removed the `isset` workarounds for the default arguments.
It's possible the warning this circumvented was changed in PHP7, but
more likely is that this was a manifestation of the typos.
Thanks to RedRocket for reporting the bug.
> Plotter: fix findReversiblePathFromX

- .gitignore
- Dockerfile
- admin/Default/album_moderate_processing.php
- admin/Default/newsletter_send_processing.php
- config/config.specific.sample.php
- docker-compose.yml
- engine/Default/contact_processing.php
- engine/Default/preferences_processing.php
- htdocs/config.inc
- htdocs/email_processing.php
- htdocs/login_create_processing.php
- htdocs/resend_password_processing.php
- lib/Default/SmrPlayer.class.inc
- lib/Default/smr.inc
- opendkim/README.md
* Switch from using the php `mail` function to the PHPMailer module.
* We no longer need the sendmail package and configuration in
the smr image. Mailing will be done with PHPMailer's SMTP
library to connect to a postfix/opendkim container.
* When using the docker-compose orchestration, we will want
to always use the name of the `smtp` service as the SMTP
hostname. However, we add the `SMTP_HOSTNAME` config option to:
a) allow specifying a non-docker SMTP host or
b) use the local mail server (if empty or unset)
The latter is necessary to run this patch on the current live
(non-dockerized) server.
* We pass `true` to the PHPMailer ctor to indicate that we
want to throw an exception if there is an error while
sending the mail.
> Use separate postfix/opendkim container

- lib/Default/SmrPlanet.class.inc
Add a new news entry for each planet attack. Previously an attack
would be omitted if _any_ attack was made recently (even if it was
a different planet). Now we use planet owner to determine uniqueness
of planet attacks.
Increase the time before a new news entry is added for the _same_
planet from 10 mins to 30 mins. This helps avoid duplicate entries
now that we aren't worried about missing other planet attack news.
> SmrPlanet: make planet attack news more reliable

- engine/Default/map_local.php
- htdocs/css/shared.css
- htdocs/map_galaxy.php
- lib/Default/SmrAlliance.class.inc
- lib/Default/SmrSector.class.inc
- templates/Default/engine/Default/GalaxyMap.inc
- templates/Default/engine/Default/includes/SectorMap.inc
- templates/Default/engine/Default/includes/SectorMapOptions.inc
- templates/Default/engine/Default/map_local.php
* Hide Allied Forces: toggles on and off displaying alliance forces.
If off, only your own forces will display on the map.
* Show Seedlist Sectors: toggles on and off display of sectors that
are in the alliance seedlist.
We implement these options as part of a PHP session, for simplicity,
to avoid unnecessarily modifying the `account` or `player` database
tables. This is because these options are typically not needed to
persist indefinitely. We will need to monitor community reaction to
this behavior, as well as possible performance impact of PHP sessions
to see if we need to migrate these options to the database at a
later time.
Add a few class methods:
* SmrSector::hasPlayerForces
This is needed to replace `hasFriendlyForces` when using the
"Hide Allied Forces" option. We could have …
> Add new options to Local and Galaxy maps

- htdocs/config.php
Calling `date_default_timezone_get` before setting the timezone
raises a warning in xdebug and can impact performance (since it
has to determine which timezone to use).
Just set it to "CET", since that's what the server currently
uses. If we really want, we can make it a `config.specific.php`
option in the future.
We also may want to consider switching to UTC as well, but that
may require us to change how player time offsets are stored
(currently they're just integers, which is problematic when it
comes to daylight savings).
> config.php: set date.timezone

- lib/Login/SocialLogin.class.inc
There are no API changes between 2.7 and 2.12 that affect our
usage, so we can upgrade now. Version 2.12 will reach end-of-life
some time in 2020.
> SocialLogin.class.inc: update to v2.12 Facebook API

- lib/Default/smr.inc
Showing 3 decimals instead of 4 allows us to associate the decimal
number with the number of milliseconds, which is a more natural unit
than tenths of a millisecond.
> smr.inc: show only 3 decimals of script runtime

- htdocs/css/Freon22-layout.css
- lib/Default/smr.inc
- templates/Default/engine/Default/includes/copyright.inc
- templates/Freon22/engine/Default/skeleton.php
The script runtime was computed at the end of `do_voodoo`, but before
`$template->display`. As a result, the displayed runtime only included
the cost of processing the `engine` files. However, this entirely
excludes the cost of processing the `template` files, which is the
majority of the cost for some files (e.g. Local and Galaxy maps).
Ideally we would compute the script runtime at the end of `do_voodoo`
just before `exit` is called, but unfortunately there is no way to
then display this number since the html document tags are closed at
the end of `$template->display`.
Since `copyright.inc` is processed (nearly) last on the page, it is a
significant improvement to compute the script runtime inline, so we
do that now . This is still not ideal, but it only excludes a few
milliseconds of …
> Make script runtime more accurate

- htdocs/map_galaxy.php
Because the Galaxy Map page uses the template system to display
the content, it will do the work to prepare the page for AJAX
updates unless it is told not to do so.
We don't even include the javascript necessary to display AJAX
updates, so this work was always being done (even if AJAX was
disabled in account preferences) for no reason.
Depending on the size of the galaxy, this extra work could take
hundreds of milliseconds (or 1/4 to 1/3 of the total runtime)!
To fix this, we simply tell the template system that AJAX is
disabled on the galaxy map.
> map_galaxy.php: significant speedup

- lib/Default/SmrPlayer.class.inc
The e-mail notifications for received player messages did not
correctly handle non-player senders. We would be calling
`SmrPlayer::getPlayer` for an account that doesn't exist, which
would throw a database error.
To fix this, we have to instead call `getMessagePlayer`, which
handles non-player senders correctly (this is what we do to
parse senders when viewing/sending messages in-game).
> SmrPlayer: fix e-mail notifications from non-player accounts

- tools/chat_helpers/channel_msg_op_info.php
The previous formula did not account for the fact that you may
have been losing turns by being at the turn cap since the last
time you accessed the game. The new formula first calculates your
current turns (if you were to log in _now_) and only then calculates
the turns you will have at the op time.
> channel_msg_op_info.php: fix turn reporting

- config/irc/config.specific.sample.php
- tools/irc/server.php
The server ping (which occurs roughly every minute) prints a message
that becomes extremely verbose when the ircbot has been running for
a long time. To avoid overloading the logs, we silence this message
by default. An optional config variable `IRC_BOT_VERBOSE_PING` can
be sent to `true` to recover this diagnostic message.
> Silence ircbot ping message by default

- .dockerignore
- Dockerfile
Add enough data from the `.git` directory to be able to store
the commit hash of HEAD. This allows us to tell which version
of the code is running in a docker image.
Ideally we would want this in the image metadata, but I think
Docker prevents this sort of dynamic logic at build time.
We use this method in favor of two other alternatives:
1. Docker Cloud build arg
Docker Cloud provides a `$SOURCE_COMMIT` build arg, but it can
only be passed into the build environment with a custom build
hook. Unfortunately, this causes the Docker Cloud build to not
utilize the layer cache correctly, even though diagnostic
messages indicate that it is pulling/pushing the layer index
for the repo. I don't understand why it does this, and Docker
Cloud support is very limited. I suspect it is because the …
> Dockerfile: Add git commit data to the docker image

- htdocs/loader.php
In 2f705a49e007c, an include using `get_file_loc` was moved above
the part of the code where `$overrideGameID` was defined.
This caused all non-Default games to break, because it loaded the
wrong `Smr*` classes.
We have to be very careful about the ordering of includes here,
and there is now a comment warning about this.
> loader.php: fix include ordering issue

- engine/Default/game_play.php
For "Play Game" and "Previous Games", disabled games were previously
displayed. On the live server, there are a few accidental games that
show up in the "Previous Games", and only showing the enabled games
will hide these. For "Play Game", hiding disabled games allows us to
close a game temporarily if there is a serious issue without shutting
down the entire server.
> game_play.php: only display enabled games

- Dockerfile
Closes #297.
At long last, the mystery is solved. The reason the live server was
~5x faster when it was using the host system's PHP (rather than Docker)
was because it had the Zend OPcache enabled. This PHP extension caches
the compiled PHP and allows it to be reused at runtime. Since we have
some fairly large libraries, loading and parsing each script was a
significant expense.
Simply installing the `opcache` PHP extension in the Dockerfile
dramatically improves performance.
> Dockerfile: enable Zend OPcache

- engine/Default/preferences_processing.php
- templates/Default/engine/Default/preferences.php
Display changes:
* Merge the "Enable Default CSS", "Template", and "Colour Scheme"
options into a single "CSS Template" option, which lists all
the possible Template/Colour Scheme variants as well as "None".
The "None" option is the equivalent of Enable Default CSS == No.
It is now listed as a separate "CSS Template" option because,
when disabled, it doesn't matter to the user what the
Template/Colour Scheme are.
* Rename "Change CSS Link" to "Add CSS Link", and reword the help
text to make it clearer what this option does. Also removed the
link to the non-existent CSS file example.
These changes were needed for the following reasons:
a) It wasn't clear how all these knobs interacted.
b) Fewer knobs is easier for the user in general.
c) It was annoying to switch between templates because …
> preferences.php: reorganize CSS preferences

- engine/Default/course_plot_nearest_processing.php
- engine/Default/course_plot_processing.php
- engine/Default/course_plot_result.php
- templates/Default/engine/Default/course_plot_result.php
Because we deep copied the `$path` in `course_plot_processing.php`
and `course_plot_nearest_processing.php` _before_ we performed
the final path processing, we duplicated this work in
`course_plot_result.php`.
If we instead do the common processing in `course_plot_results.php`
_only_, then we avoid both the duplicated code/processing _and_
the cost of the deep copy.
Since `course_plot_results.php` is sometimes a display page, we do
the processing first so that we don't do the display work if we
end up forwarding to `current_sector.php`.
Also:
* Convert `course_plot_results.php` to a template.
> Streamline course plot processing

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/1.6/universe_create_warps.php
- admin/Default/game_delete_processing.php
- admin/Default/smc_new.php
- db/patches/V1_6_62_04__add_sector_warp.sql
- lib/Default/SmrSector.class.inc
Due to the way we construct `SmrSector`, we end up querying the
`warp` table for every single sector. This essentially doubles the
cost of the `SmrSector` ctor.
On the other hand, adding an extra `warp` field to the `sector`
table adds a negligible cost to the `sector` database query, so we
do this instead.
> Move warp into sector table

- lib/Default/Smr12HistoryMySqlDatabase.class.inc
- lib/Default/Smr12MySqlDatabase.class.inc
- lib/Default/SmrClassicHistoryMySqlDatabase.class.inc
- lib/Default/SmrClassicMySqlDatabase.class.inc
- lib/Default/SmrMySqlDatabase.class.inc
- lib/Default/SmrSessionMySqlDatabase.class.inc
The `Smr*MySqlDatabase` classes used constructors with the same name
as the class. This emits a warning in PHP 7:
> Methods with the same name as their class will not be constructors
in a future version of PHP.
We use the magic method `__construct` instead.
> Replace deprecated constructors

- templates/Default/engine/Default/planet_main.php
The `<img>` tags for the planet hardware had IDs that were
duplicating the ship IDs for `cds` and `shields` (and also had
a duplicate `turret` ID that should have been `armour`). This
resulted in the following warning, e.g.:
> DOMDocument::loadHTML(): ID shields already defined in Entity
To fix these, we simply remove the `id` attributes for these
images, since they are not needed.
> planet_main.php: remove duplicate id attributes

- engine/Default/planet.inc
- engine/Default/planet_bond_confirmation.php
- engine/Default/planet_construction.php
- engine/Default/planet_defense.php
- engine/Default/planet_financial.php
- engine/Default/planet_main.php
- engine/Default/planet_ownership.php
- engine/Default/planet_stockpile.php
- lib/Default/Template.class.inc
In `create_error`, an exception is thrown if `USING_AJAX=true`.
This is because the ajax page refreshes don't really know how
to handle when a different page needs to be displayed without
the user clicking a button.
The most important place where this occurs is when a player is
kicked from a planet (by the owner or in a bust). In the past,
this would cause ajax to stop updating due to the exception.
We could instead forward to the current sector page, but this
would display a disjointed page because a) the left panel links
don't have span id's for updating and so you'd still see the
"Planet Main" link, and b) the middle panel won't update
correctly because we already have ajax-enabled child elements,
which disables the full middle panel update.
Instead what we will do is use …
> Auto-update page to current sector when kicked from planet

- lib/Default/SmrPlanet.class.inc
Wait 1 hour instead of 30 minutes before generating additional
news entries for an attack on the same planet (with the same owner).
NOTE: if the planet owner changes, another attack at any time will
trigger a news entry.
This was changed because planet busts on big planets can sometimes
last up to an hour. But we don't want the cooldown to be so large
that a second attack isn't announced (let's say an alliance is
attacked once, and then they stop for an hour and come back -- this
should generate two news entries).
> SmrPlanet: change timer for planet bust news

- engine/Default/forces_mass_refresh.php
- lib/Default/SmrForce.class.inc
Gameplay
-----------
SmrForce: halve the Refresh All interval  
Due to faster connections to the server over time, people have
stopped using "Refresh All" because it is simply far too much
slower than refreshing each stack individually. While we still
want there to be a tradeoff between speed and convenience, dropping
the wait time per stack from 2 seconds to 1 second should make
it more competitive.
Non-Gameplay
---------
Refresh All costs a fixed number of seconds per stack, and so we
use a named constant instead of hard-coding the number.
Add a method `SmrForce::updateRefreshAll` to set the `refresh_at`
and `refresher` fields of the `sector_has_force` table when the
"Refresh All" button is pressed.
We also refactor completely `forces_mass_refresh.php` to use
class methods instead of …
> Changes to Refresh All

- composer.json
We need some PHP7 fixes that have been added to phpquery in the
5 years since v0.9.6 was released.
In particular, this fixes the error in phpQueryObject.php:3124
> Error: Call to undefined function split()
I believe this is only an issue if you enable debugging in
phpquery with `phpQuery::$debug = 1`, but it being broken
makes debugging other phpquery issues more difficult.
> composer.json: switch to phpquery dev-master

- lib/Default/Template.class.inc
If we already started output buffering before calling
`Template::display`, we may have unwanted content in the buffer
that we need to remove before we send the Content-Type headers.
Ultimately, we want to remove all instances of pre-header output,
so we disable the `ob_clean` when `ENABLE_DEBUG=true`.
> Template.class.inc: call ob_clean conditionally

- lib/Login/SocialLogin.class.inc
The Facebook App recently changed to require explicitly listing
the Valid OAuth Redirect URIs (presumably when they bumped the
minimum API to v2.6 on Apr 12, 2018). We also enabled "Enforce HTTPS"
at their recommendation. As a result, the Facebook login for the new
containerized server broke. Here's why:
After the redirect back to the SMR server, we need to get an
access code from the social platform. For Facebook, this requires
passing the Redirect URI again (for some OAuth reason...), and
if you don't explicitly specify it, the Facebook code will auto-
detect it. We were not explicitly specifying it, and since Nginx
is currently set up to use regular HTTP in the `proxy_pass` to
the `smr` container, it was autodetecting a non-HTTPS URL.
I don't think we want to change how the …
> Fix facebook login

- admin/Default/announcement_create_processing.php
Messages can now be unlimited in size, instead of limited to
255 characters.
> Remove restriction on admin announcement message length

- htdocs/css/shared.css
The full blue color was a bit hard to look at for some people,
so reduce the opacity of the blue stripes to 50% (note that
`rgba` is a well-supported CSS function, but 8-digit hex is not).
Before / After
> shared.css: change lm_seedlist stripe color

- templates/Default/admin/Default/box_reply.php
When replying to messages reported by players, clarify that the
"Points" input box specifies ban points, which are added when the
message is sent.
> box_reply.php: clarify points input

- admin/Default/box_view.php
- htdocs/config.inc
- templates/Default/admin/Default/box_view.php
config.inc: restructure how exceptions are handled
* Always send the automatic bug report to both the in-game box
(so that devs who can't access `bugs@smrealms.de` can still see
every automatic bug report) and to the `bugs@smrealms.de` e-mail
so that we have a permanent record of the report.
* If there is neither a `SmrPlayer` nor a `SmrAccount`, send the
error message to the in-game box with both account ID and game ID
set to 0.
* When handling exceptions, always redirect the user to the next
appropriate game page even if the error logging fails.
> Make exception logs available in-game and in e-mail

- lib/Default/smr.inc
One of the biggest problems with ajax is when it just silently
dies. The primary culprit for this behavior is when something
triggers an error while auto-refreshing, which then throws an
exception in `create_error` since ajax is not handled there.
We don't want that to happen, so we can instead use javascript to
redirect to the error page (like we did with being ejected from
a planet in 1b2d59c6b21).
Because we both forward to the error page and redirect with
javascript (for safety in case javascript is disabled), players
may see the old error page flash briefly before it displays the
`current_sector.php` page with error message.
> smr.inc: make errors during ajax updates more recoverable

- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/RightPanelShip.inc
- templates/Default/engine/Default/includes/SectorMap.inc
- templates/Default/engine/Default/skeleton.php
Since the player does not see itself on the Local Map, it shouldn't
see the flagship icon either if they are the alliance flagship.
Instead, a natural place to display the flagship icon is on the
right panel.
Add convenience function `SmrPlayer::isFlagship`.
Local Map for flagship player
Local Map for non-flagship player
> Display flagship on right panel

- templates/Default/engine/Default/includes/SectorNavigation.inc
The Current Sector navigation links had the `class` attribute
specified twice, and the second one (`class="ajax"`) was being
ignored by browsers and phpquery. Since I don't see why these
elements were intending to be ajax enabled to begin with, we
simply remove it to fix the error.
> SectorNavigation.inc: fix duplicate class attribute

- templates/Default/engine/Default/sector_jump_calculate.php
The `short_open_tag` php option is on by default, and the dev
environment uses the default php options at the moment.
Unfortunately, the production value is off, and so any code
that uses short tags will break in production.
> sector_jump_calculate.php: fix short tags issue

- admin/Default/admin_message_send_processing.php
- templates/Default/admin/Default/admin_message_send.php
* When sending to "All Players", only send messages in games that haven't ended.
* Display that the message is being sent to "All Players" when that's what the admin is doing.
> Minor improvements to Admin Send Message

- engine/Default/vote_link.php
- lib/Default/VoteSite.class.inc
- lib/Default/smr.inc
* Refactor voting code out of `smr.inc` and into a new `VoteSite` class.
* Prohibit voting until after the _max_ time you can gain from free turns. Previously it was only prohibiting it based on the time you get from one site.
> Refactor voting code to fix game start timer

- db/patches/V1_6_62_09__alliance_invites.sql
- engine/Default/alliance_invite_accept.php
- engine/Default/alliance_invite_player.php
- engine/Default/alliance_invite_player_processing.php
- engine/Default/alliance_join_processing.php
- engine/Default/alliance_option.php
- engine/Default/alliance_roster.php
- lib/Default/SmrAlliance.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/smr.inc
- templates/Default/engine/Default/alliance_invite_player.php
Allow alliance members with permission to change the alliance password
to invite players into the alliance.
Add a new alliance option "Invite Player", which links to a page that
displays the current alliance quotas (vet/total), allows you to invite
specific players, and lists all pending invitations.
Players who are invited will receive an automatic player message with
a link to join the alliance (achieved through a new `join_alliance`
BBCode tag). You can optionally attach a personal message to the
invitation (this is omitted if you are blacklisted or mail banned,
but the invitation is still sent).
Library changes:
* Add `doAllianceCheck=true` argument to `SmrAlliance::canJoinAlliance`
so that we can check if a player can join an alliance before making
him leave his current alliance. If …
> Add alliance invitations

- engine/Default/message_view.php
- htdocs/js/ajax.js
- templates/Default/engine/Default/message_view.php
The previous design had two main problems:
1. It was difficult to see specific individual scout messages.
2. Messages are marked as read as soon as you open the message box.
However, scout messages were previously grouped according to how
many read/unread messages you had from a player. If that number
crossed the `MESSAGE_SCOUT_GROUP_LIMIT` threshold as a result of
marking them read, then links that were displayed when you first
opened the page become stale by the time you click on them.
(The page doesn't change, but the auto refreshes invalidate any
links that aren't either `ALWAYS_AVAILABLE` or generated in
subsequent calls to the code.)
While we could have simply made all links `ALWAYS_AVAILABLE`, the
more correct solution is to ensure that the generation of links
doesn't depend on …
> message_view.php: revamp scout message grouping

- .travis.yml
- README.md
- composer.json
- lib/Default/SmrSession.class.inc
Since we use OPcache, it is better to do as much as possible at
compile time so it can be cached and reloaded. Const is compile
time, and static variable are runtime, so we switch to consts
when possible.
NOTE: this sets minimum PHP requirement to 7.1.
> SmrSession: change static arrays to constants

- Dockerfile
Access logging bloats the container size and is not needed in
dev environments. On the live server, we are logging with the
nginx reverse proxy, so the apache logging was redundant.
Also, since `docker logs` shows combined error/access logs, it
was very difficult to display only the errors (mostly because
the access log is so huge that even redirecting the stdout to
`/dev/null` takes an excessively long time.
> Dockerfile: disable apache access logging

- engine/Default/sector_move_processing.php
See #317.
NOTE: objects used as globals must still be assigned using references.
Doing a standard assignment to `$sector`, for example, results in the
green sector showing up as the current sector on the Local Map!
> sector_move_processing.php: remove references

- composer.json
- lib/Default/Template.class.inc
PHPQuery is abandonware and will likely run into issues as PHP
versions increase. We can replace PHPQuery with the builtin classes
DOMDocument and DOMXPath using nearly the same amount of inline code.
This also fixes an issue where converting the DOM to HTML caused
extra whitespace to be inserted between elements. This was due to
PHPQuery setting `formatOutput=true` on an internal DOMDocument
that could not be changed without modifying the PHPQuery source.
(NOTE: To achieve the fixed whitespace using DOMDocument directly,
we need to circumvent PHP Bug #76285 when converting to HTML.)
> Template.class.inc: remove PHPQuery dependency

- admin/Default/game_status.php
- admin/Default/game_status_processing.php
- lib/Default/AdminPermissions.class.inc
- templates/Default/admin/Default/game_status.php
Since we usually use the term 'Game' to refer to an individual
`SmrGame`, we change this tool to refer to 'Server' instead,
which should clarify for admins what this tool actually does.
* Add success messages
* Convert `game_status.php` to template
> Rename "Game Open/Close" admin tool

- admin/Default/box_view.php
- admin/Default/game_maintainance.php
- db/patches/V1_6_62_12__remove_message_types.sql
- engine/Default/buy_message_notifications.php
- engine/Default/message_view.php
- lib/Default/message.functions.inc
The following tables have been replaced with function calls
defined in `message.functions.inc`:
* `message_box_types` -> `getAdminBoxNames()`
* `message_types` -> `getMessageTypeNames()`
We do gain a performance improvement by avoiding the database calls,
but they are not significant. The bigger advantage is being able to
modify these tables if needed without the hassle of modifying the
database.
> Replace some tables with PHP arrays

- lib/Default/AbstractSmrAccount.class.inc
Declare unchanging arrays of the `SmrAccount` class constant
instead of static to take advantage of OPcache compile-time
caching.
> SmrAccount: use const instead of static

- admin/Default/game_maintainance.php
- db/patches/V1_6_62_14__remove_rankings.sql
- engine/Default/rankings_view.php
The `rankings` table was superseded by the `user_rankings` table.
Since the `rankings` table was never formally populated in version control, I copy the live server entries for historical purposes:
> Remove unused rankings table

- engine/Default/contact_processing.php
- tests/phplint.sh
- tools/npc/npc.php
Due to a lack of parentheses in the `find` command, the tests
were only being run on `.inc` files. Now with this fix we test
both `.inc` and `.php` files.
Fix discovered errors in:
* contact_processing.php
* npc.php
>  phplint.sh: fix omitting .php files

- engine/Default/feature_request_vote_processing.php
- engine/Default/vote_processing.php
The NHL account is a special account used by a player who already
has an account. Therefore, it should not be given any voting
privileges because it would essentially give that player two votes.
> Prevent NHL from casting votes

- admin/Default/announcement_create_processing.php
- engine/Default/album_delete_processing.php
- engine/Default/album_edit.php
- engine/Default/album_edit_processing.php
- engine/Default/feature_request.php
- engine/Default/feature_request_comment_processing.php
- engine/Default/feature_request_processing.php
- engine/Default/feature_request_vote_processing.php
- engine/Default/game_join_processing.php
- engine/Default/game_play.php
- engine/Default/game_play_processing.php
Replace instances of `SmrSession::$account_id` with calls to the
read-only method `SmrAccount::getAccountID` whenever we have the
global variable `$account` available.
Ultimately, we want to make `SmrSession::$account_id` private so
that it is harder to accidentally modify.
> Use SmrAccount::getAccountID when possible

- templates/Default/engine/Default/includes/SectorForces.inc
We put both the Examine and Refresh button for friendly forces on
the same line. This does two helpful things:
1. It is easier to go down the list of forces and click either the
Examine or Refresh button (since they're now aligned in separate
vertical columns).
2. More forces can be seen on a single page since the row was always
vertically extended to fit the two buttons.
One downside is that the "Attack" button will shift position as the
sector goes from having only enemy forces to enemy + allied forces.
We could just right-align the "Attack" button to ensure it stays
in the same place, but this might look even more strange.
Before:
After:
> SectorForces.inc: modify spacing

- engine/Default/hall_of_fame_new.php
Use `$game_id = null` when `$var['game_id']` is not set to avoid
an undefined index warning.
> hall_of_fame_new.php: fix PHP warning

- config/config.specific.sample.php
- engine/Default/game_play.php
- engine/Default/preferences_processing.php
- htdocs/login_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/Globals.class.inc
- templates/Default/engine/Default/preferences.php
This is intended to allow us to use the history databases
independently of the account-linking databases. We want to
do this because we will always want to display previous
games, but may not always want to support account linking.
* Move history component of `COMPATIBILITY_DATABASES` into
separate (optional) `HISTORY_DATABASES` config setting.
This is then wrapped by `Globals::getHistoryDatabases`.
* Replace the `USE_COMPATIBILITY` config setting with the
function `Globals::useCompatibilityDatabases`, which will
only be true if `COMPATIBILITY_DATABASES` is defined.
Do not specify an empty array if the intention is to omit
account linking. Simply leave it undefined.
> Refactor COMPATIBILITY_DATABASES

- templates/Default/admin/Default/1.6/universe_create_sectors.php
Our auto-refresh javascript disables clicking after a link is
clicked _unless_ the link has specific properties that indicate
that it is not modifying the current page.
On this page, we want "Create SMR file" to have this property,
so we add `target="_self"` to tell javascript not to disable
clicking.
> universe_create_sectors.php: fix ajax click disabling

- README.md
- admin/Default/1.6/universe_create_locations.php
The `$sector` variable is a special global, and should not be
overwritten (i.e. dont' use it as the temporary object of a for-loop).
This also fixes a PHP warning that `$sector` is unset in `smr.inc`.
Also update the README with a more complete list of special global variables.
> universe_create_locations.php: don't unset $sector

- templates/Default/engine/Default/includes/Head.inc
Re-add the semi-colon removed in 796845c8939, but only in cases
where we're in a game (so that we don't get a trailing semi-colon
outside of a game).
> Head.inc: fix title when in a game

- engine/Default/current_sector.php
It was confusing to players when they would join a game and they
would have 0 turns and would not be gaining any. Instead of printing
the "You are out of turns!" message, display a more information
message about when the game starts if the `StartTurnsDate` has not
been reached yet.
Before turns are given, the page will look like this:
> current_sector.php: pre-game turns message

- engine/Default/message_delete_processing.php
When clicking the "Empty Read Messages" link, the processing page
will not post an `action`. We now check to see if the `action`
exists in `$_REQUESTS` before using it to fix an undefined index
PHP warning.
> message_delete_processing.php: fix PHP warning

- templates/Default/engine/Default/port_attack_warning.php
It is surprising to people when reinforcements arrive and the
defenses suddenly shoot up dramatically. Adding a message in the
port attack warning page should help mitigate this confusion.
> port_attack_warning.php: add reinforcements timer

- admin/Default/password_check.php
The "Select All" button wasn't working previously because the
`$action` variable was undefined. Storing the `action` request
variable fixes this bug and also fixes the undefined variable
PHP warning.
> password_check.php: fix Select All button

- tools/irc/irc.php
Close connections after each callback to ensure that the mysql
connection isn't idly sitting open, because doing so makes it
prone to becoming stale and triggering a timeout error, e.g.:
> mysqli::query(): MySQL server has gone away
This can occur even if the `mysql` service is a dependency of
the `irc` service.
> irc.php: prevent stale mysql connections

- htdocs/config.php
- lib/Default/SmrPlayer.class.inc
- lib/Default/council.inc
- templates/Default/engine/Default/council_list.php
* Change `Council::getPresident` to `getPresidentID` and return
only the ID instead of performing an addition query to get
the associated `SmrPlayer`. Since we call this on every page
to display the player name, it needs to be quick, and in these
cases we have no need for the `SmrPlayer` of the President.
* Do not query `getCouncil` from within `getPresidentID`.
Most of the time when we are querying the President, we don't
need to know the entire council. This should be a faster query
since we only need to return 1 result.
* Add constant `ALIGNMENT_PRESIDENT` to config.php so that the
alignment qualification for President is not hard-coded.
> Simplify code to determine the racial President

- engine/Default/course_plot_nearest_processing.php
- engine/Default/course_plot_processing.php
- engine/Default/course_plot_result.php
The definition for a class has to be loaded _before_ `unserialize`
is called on a serialized instance of that class; otherwise, there
must be an autoloader for that class.
While autoloading is the better long-term goal, we can circumvent
this particular issue by serializing the `Distance` object before
it is stored in the `SmrSession`. This way, when the session
automatically unserializes its objects internally (something for
which we cannot predict what class definitions we'll need), it
will not be unserializing a `Distance` object, and therefore when
we unserialize it a second time in the script where it's used, we
can make sure to load the class definition first.
Note that while this creates a "PHP Fatal Error" on the server,
it does not seem to prevent it from working correctly …
> Serialize Distance before storing in SmrSession

- engine/Default/port_attack_warning.php
- templates/Default/engine/Default/port_attack_warning.php
Make sure `$Port` is always defined. Previously, if the ship
didn't have a scanner, then (as of f18adce1) the player would
hit an undefined variable and call methods on `null`.
> port_attack_warning.php: fix undefined Port variable

- admin/Default/admin_message_send.php
- admin/Default/admin_message_send_processing.php
- templates/Default/admin/Default/admin_message_send.php
Change the client-side html5 restrictions to allow the Expire time
specified in hours to be fractional (in units of 0.01 hours).
We do this by specifying the "step" field for the input element.
We also change the default Expire time from 1 hour to 0.5 hours
so that it is more obvious that fractional hours are allowed.
We add a couple sanity checks on the `expire` POST variable.
Also fix a PHP warning with `account_id`.
> admin_message_send.php: allow fractional hours

- config/config.specific.sample.php
- engine/Default/bug_report_processing.php
- htdocs/config.inc
- templates/Default/engine/Default/bug_report.php
Add new const `BUG_REPORT_TO_ADDRESSES`, which is a configurable
array of e-mail addresses that automatic bug reports will be sent to.
Just like with automatic bug reports, we now send player-submitted
bug reports to the bug report e-mail recipients as well.
This provides a way to keep a permanent record of reports as well
as customizing the recipients with the configurable option
`BUG_REPORT_TO_ADDRESSES`.
>  Make bug reporting recipients configurable

- admin/Default/manage_draft_leaders_processing.php
- admin/Default/manage_post_editors_processing.php
- engine/Default/hall_of_fame_player_detail.php
- htdocs/album/album_comment.php
- htdocs/album/index.php
- htdocs/config.inc
- htdocs/disabled.php
- htdocs/email.php
- htdocs/email_processing.php
- htdocs/index.php
- htdocs/level_requirements.php
- htdocs/loader.php
- htdocs/login.php
- htdocs/login_create_processing.php
- htdocs/login_processing.php
- htdocs/manual.php
- htdocs/manual_toc.php
- htdocs/map_galaxy.php
- htdocs/offline.php
- htdocs/resend_password_processing.php
- htdocs/reset_password_processing.php
- htdocs/ship_list.php
- htdocs/weapon_list.php
- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/hof.functions.inc
- tools/discord/mysql_cleanup.php
- tools/irc/channel_msg.php
- tools/npc/chess.php
- tools/npc/npc.php
* Catch `Throwable` instead of `Exception` so we can cleanly log fatal PHP errors instead of getting 500 Internal Server Error pages.
* Add `AccountNotFoundException` and use `PlayerNotFoundException` more thoroughly to avoid catching unrelated errors.
* In debug-mode, display error messages on the page in human-readable format.
> Improve error handling

- htdocs/login_create_processing.php
* Perform the recaptcha check as early as possible to avoid
additional database queries. This will help reduce the work
the server needs to do when bots are crawling the site.
* Check if the `g-recaptcha-response` index of `$_POST` exists
before using it to avoid a PHP undefined index warning.
> login_create_processing.php: move recaptcha check

- lib/Default/hof.functions.inc
When getting the HoF amount for another player, we don't want to
even try to construct an `SmrPlayer` if we know there is no game
specified. This was previously caught by a generic try-catch, which
was replaced by specifically catching `PlayerNotFoundException` in
1f638bbdb; however, when `$gameID=null`, a regular `Exception` was
thrown, which broke this piece of code.
Rather than bothering with exception handling at all, we can skip
the `SmrPlayer` construction if we know that we haven't specified
a game. When we have specified a game, we expect the `SmrPlayer`
construction to succeed in all cases.
> hof.functions.inc: fix getHofRank error

- engine/Default/current_sector.php
The `$sector` global and `ThisSector` template variable are already
assigned by `do_voodoo` in smr.inc. As such, there is no need to
set them again in current_sector.php.
> current_sector.php: don't reassign sector

- htdocs/config.inc
For an Exception, the `getMessage` and `getTraceAsString` do not
provide complete backtrace information -- they do not include the
file and line number of the error itself.
If we instead cast the Exception to a string, then a complete
error message (with full backtrace) is printed.
> config.inc: print complete backtrace

- engine/Default/bar_gambling_processing.php
Remove a hacked global variable to avoid a PHP warning that
complains about `$player_card` not being an object that implements
Countable.
We do this by passing the array of cards to `check_win` instead
of the total card values.
> bar_gambling_processing.php: fix check_win

- htdocs/resend_password_processing.php
* Make sure that the `email` field is not empty when requesting
to resend a password. This provides a more accurate error message
and also avoids a PHP undefined index warning.
* Perform this check before any includes to reduce the work that
the server has to do when bots are crawling this page.
> resend_password_processing.php: fix PHP warning

- engine/Default/logoff.php
- htdocs/album/album_comment.php
- htdocs/album/search_processing.php
- htdocs/config.inc
- htdocs/email.php
- htdocs/email_processing.php
- htdocs/index.php
- htdocs/loader.php
- htdocs/login_create_processing.php
- htdocs/login_processing.php
- htdocs/map_galaxy.php
- htdocs/resend_password_processing.php
- htdocs/reset_password_processing.php
- lib/Default/AbstractSmrAccount.class.inc
When specifying the `Location` header, we can use a value relative
to the webserver instead of manually specifying the full URL.
We will use the leading '/' to indicate that the location is relative
to the webserver root instead of the current directory (e.g. to avoid
issues with '/album').
This also allows us to simplify some pages, since we needed to
include configuration files to define the `URL` constant.
> Make header locations relative

- lib/Default/Plotter.class.inc
This method is unused and redundant with `getNextOnPath`, so we
remove it.
> Distance: remove getStartSectorId method

- engine/Default/course_plot_result.php
To determine if the course was plotted from the current sector,
it checks if the start of the path (after the start sector is
removed) is linked to the current sector. This is degenerate
because more than just the current sector is linked to this
start sector.
For example, if you plot _from_ 2 sectors away from your current
sector _to_ your current sector, the course will not be displayed
because both your current sector and the "from" sector are linked
to the start of the path. This will then forward you to the
Current Sector page, but you're already at the destination sector,
so the course is unset.
Since we have access to the "from" sector directly, we can simply
check if the current sector is the "from" sector. There's no need
to do anything with the start of the path or linked …
> Fix edge case where course plot does nothing

- htdocs/login_social_processing.php
- templates/Default/login.inc
If you leave the login page open for longer than the PHP session
timeout and then click a social login link, then an exception is
thrown because the PHP session data has expired.
For Facebook, the error will look something like:
```
FacebookSDKException: Cross-site request forgery validation failed.
Required param "state" missing from persistent data.
```
To fix this, we no longer display the social login URL on the login
page. Instead, we link to a wrapper `login_social_processing.php`,
construct the social login URL there, and then immediately forward
to it to ensure that the session that's created while generating
the URL is still active.
> Fix stale social login URLs

- engine/Default/sector_scan.php
- lib/Default/SmrSector.class.inc
- templates/Default/engine/Default/includes/PlottedCourse.inc
- templates/Default/engine/Default/includes/SectorMap.inc
getLocalMapHREF -> getLocalMapMoveHREF
getCurrentSectorHREF -> getCurrentSectorMoveHREF
These methods were renamed for consistency with the `Globals`
methods `get*SectorMoveHREF` and to avoid confusion with the
other methods of `Globals` with the same name as the originals
but that only link to the Local Map or Current Sector pages
(i.e. no movement involved).
> SmrSector: rename methods for clarity

- templates/Default/engine/Default/alliance_set_op.php
This was erroneously set as `flagship2.png` instead of `flagship.png`.
> alliance_set_op.php: fix flagship image path

- templates/Default/admin/Default/location_edit.php
When editing a single location, `$Locations` is not set, and so
causes an undefined variable warning. Instead of just casting the
variable to a bool, check for its existence, which fixes the warning.
> location_edit.php: fix editing single location

- engine/Default/smr_file_create.php
- lib/Default/AbstractSmrShip.class.inc
This call to `getAllBaseShips` passed `game_id` to the function
instead of `game_type_id`. Even though this argument is unused
(the ships are independent of game type at the moment), it is
implemented as an array key for the base ship cache.
By passing the wrong argument, we were unable to re-use the cache
for later calls. These later calls were also done serially for
each ship, which dramatically increased the query overhead.
Now that we pass the expected argument, we can re-use the cache
as expected, and significantly optimize the ship-related calls.
> smr_file_create.php: fix call to getAllBaseShips

- templates/Default/engine/Default/includes/SectorMap.inc
In UniGen, this was still querying `getSector{Players,Forces}`,
which is unnecessary since we do not display Forces/Players.
It is also a significant cost when called for every sector in
a galaxy.
By moving all such calls to inside an `if (!$UniGen)` clause,
we ensure that these methods are never called in UniGen.
There should be no effect on Local/Galaxy Map.
> SectorMap.inc: optimize UniGen

- admin/Default/1.6/universe_create_sectors.php
- lib/Default/SmrGalaxy.class.inc
- templates/Default/admin/Default/1.6/universe_create_sectors.php
Since the method to set the sector connectivity is random,
the resulting connectivity will not necessarily match the
requested connectivity. Therefore, it is useful to display
the actual connectivity of the sectors in each galaxy.
> universe_create_sectors.php: Add connectivity display

- engine/Default/game_join_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/DummyPlayer.class.inc
- lib/Default/SmrPlayer.class.inc
Use `SmrSector::getLocationSectors` to avoid an explicit database
query. This also has the benefit of caching the sector, since we
will certainly need it.
We also make the method static so that it can be used in
game_join_processing.php before the `player` record has been
created (and thus we do not have access to an SmrPlayer instance).
Remove `getHome` from the abstract base class, because we remove
it completely from DummyPlayer (it serves no real purpose there).
> SmrPlayer: refactor getHome

- engine/Default/rankings_sector_kill.php
- htdocs/map_galaxy.php
- lib/Default/SmrSector.class.inc
Major optimization of multi-sector queries (i.e. `getGalaxySector`
and `getLocationSectors`) to allow us to perform only a single
query to cache all sectors instead of separate queries for each
sector.
We refactor `getSector` and the ctor to optionally take a `$db`,
which if specified is expected to already have a sector query
ready to extract.
This improves the performance of the Galaxy Map and UniGen.
> SmrSector: optimize multi-sector queries

- lib/Default/SmrSector.class.inc
This method was not clearing all the caches owned by SmrSector.
We now also clear the `CACHE_LOCATION_SECTORS` cache for
completeness (even though it is only used in one obscure place).
> SmrSector: make clearCache more complete

- admin/Default/1.6/universe_create_save_processing.php
- lib/Default/SmrGalaxy.class.inc
Add new method `setConnectivity`, which is factored out of
`generateSectors`. This avoids the extra work of re-creating
all the sectors when we simply want to change the connectivity.
* Significantly simplified algorithm for setting connections.
We can simply loop over the galaxy sectors rather than looping
over sector ID's.
* Fixed an issue with actual connectivity not matching the
requested connectivity. The old algorithm would often give
a very small number of disabled links (~99% connectivity)
in most cases. I could not figure out why this was happening.
The new algorithm reliably matches the requested connectivity.
> SmrGalaxy: refactor generateSectors

- engine/Default/game_play.php
- lib/Default/AbstractSmrCombatWeapon.class.inc
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/DummyPlayer.class.inc
- lib/Default/SmrCombatDrones.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrWeapon.class.inc
- templates/Default/engine/Default/game_play.php
Past Maintenance was a feature from SMR 1.5 that allowed players
to get more turns while reducing the effectiveness of their actions.
This was only partially implemented in SMR 1.6, but also entirely
unused.
If it were to ever be re-implemented, it would take more work to
modify the existing methods than to write it from scratch, so we
remove the no-op methods to help reduce the complexity of the
existing code and to avoid unnecessary database calls when
attacking.
Rename "Maintenance" to "Turns" in some places where the two concepts
were entangled.
NOTE: we also add the `PLANET_DAMAGE_MOD` constant to the
AbstractSmrCombatWeapon class to ensure that we consistently
reduce damage done to planets.
> Remove "Past Maintenance" feature

- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/smr.inc
These functions specified privileges in some older version of the
game, but they currently don't do anything.
We have newer and better supported ways to specify privileges
now, so we simply remove these obsolete functions.
> smr.inc: Remove functions has_{,_beta}_privilege

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/1.6/universe_create_sector_details.php
Because `$sector` is a special global variable, we do not want
to assign to it (arbitrarily), even in the UniGen, since it can
be used while the admin player is in the game they are editing.
Renaming the variables to something other than `$sector` fixes
all possible problems that might arise from overwriting the
global variable.
> UniGen: remove incorrect assignments to $sector

- engine/Default/alliance_forces.php
- engine/Default/current_players.php
- engine/Default/forces_list.php
- engine/Default/game_stats.php
- engine/Default/shop_weapon_processing.php
- engine/Default/trader_search_result.php
- engine/Draft/alliance_pick.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/AbstractSmrShip.class.inc
- lib/Default/DummyShip.class.inc
- lib/Default/Plotter.class.inc
- lib/Default/Rankings.inc
- lib/Default/SmrAlliance.class.inc
- lib/Default/SmrForce.class.inc
- lib/Default/SmrGalaxy.class.inc
- lib/Default/SmrLocation.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrPort.class.inc
- lib/Default/SmrShip.class.inc
- lib/Default/SmrWeapon.class.inc
Set up a consistent infrastructure for all classes that can be used to construct multiple class instances with a single query. This is necessary because query overhead is the biggest static expense (behind the dynamic expense of sector lock), so we want to minimize the number of queries we make.
We modify class construction and multi-instance query infrastructure for the following:
* SmrLocation
* SmrForce
* SmrGalaxy
* SmrPlanet
* SmrPlayer
* SmrWeapon
> Optimize queries for constructing multiple class instances

- lib/Default/MySqlDatabase.class.inc
Even with our SQL member enhancements, `escapeNumber` often shows up
as the 2nd or 3rd highest cost in profiling. This is due to the sheer
number of calls.
Numbers, including hexidecimals, do not need to be quoted in mysql
(and most query languages don't even allow you to quote numbers),
and so we remove the option to quote them. Since we are not quoting
them, then there is no need to escape them.
Calling `escapeString` in the guts of `escapeNumber` is therefore
essentially a no-op, and we should just return the number directly
once we have verified that it is numeric. This reduces the cost of
`escapeNumber` by a factor of ~3 or 4.
> MySqlDatabase: optimize escapeNumber

- lib/Default/SmrPort.class.inc
There were a few places where this member could still be used. Documented the one place where it could not be used due to SmrPort deserialization.
> SmrPort: use SQL member

- admin/Default/map_show_processing.php
- engine/Default/bar_galmap_buy.php
- engine/Default/beta_func_processing.php
- lib/Default/SmrPort.class.inc
Add an optional `$db` argument to `getPort` and the class ctor,
which if specified should contain a loaded query with all the
fields of the `port` table.
This allows us to perform a single multi-port query, and then
construct many SmrPort instances without incurring the cost from
the overhead of multiple queries.
>  SmrPort: enable multi-port queries

- admin/Default/1.6/universe_create_ports.php
- htdocs/js/smr15.js
- templates/Default/admin/Default/1.6/universe_create_ports.php
Use the `onInput` event instead of `onFocus` event to recalculate
the totals from user input. This is more precisely what we want
to do, and simplifies the javascript (because previously we had
to set an event to turn on recalculating at regular intervals,
and then another event to turn it off).
We also remove the javascript function that was used for mines
(i.e. asteroids), for which the calling code was removed in
844dab9.
> universe_create_ports.php: convert to template and tweak javascript

- engine/Default/government.php
- engine/Default/government_processing.php
- engine/Default/underground.php
- lib/Default/gov.functions.inc
- templates/Default/engine/Default/government.php
- templates/Default/engine/Default/includes/BountyList.inc
- templates/Default/engine/Default/underground.php
Additional changes:
* Rename the HQ's based on their location name so they don't
all say "Federal Headquarters" (instead, they will now say
"<Race> Headquarters").
* Rename button for joining HQ from "Become a gang member" to
"Become a smuggler". Gang member doesn't have the right
connotation.
* Replace the "Become a ..." form with a submit-style link.
Therefore, we remove the (redundant) check of the form action
in government_processing.php.
> {government,underground}.php: convert to template

- engine/Default/bar_gambling_bet.php
- engine/Default/bar_gambling_lotto.php
- engine/Default/bar_main.php
- templates/Default/engine/Default/bar_gambling_bet.php
- templates/Default/engine/Default/bar_gambling_lotto.php
- templates/Default/engine/Default/bar_main.php
* bar_gambling_bet.php
* bar_gambling_lotto.php
We need to generalize bar_main.php to accomodate any bar-related
script that has been templatized. We do this by always including
the template if `$PHP_OUTPUT` is empty (which it should be for
templatized scripts).
> Convert a few bar pages to templates

- engine/Default/shop_goods_trade.php
This reverts commit a9967149c3c5e8c19abbf15e469944d7251fe49a.
The variable actually was necessary for the case where the player
has not yet failed a trade.
> Revert "shop_goods_trade.php: remove unnecessary variable"

- lib/Default/ChessGame.class.inc
* Fix "only return variables by reference" warning
The `setWinner` method returns an unbound array, so it cannot be
returned by reference.
* Fix sending resign message
Resign messages were sent to the wrong account (a GameID was passed
to a function expecting an AccountID).
> Chess fixes

- engine/Default/shop_ship.inc
- engine/Default/shop_ship.php
Split shop_ship.php into a part that queries the ship list and
a part that processes the list (shop_ship.inc).
This is the easiest way to change the ship list for different
game types, because then the query in shop_ship.php can be modified
without duplicating the logic in shop_ship.inc.
> Refactor shop_ship.php

- templates/Default/engine/Default/shop_weapon.php
It may be useful to know the power level of your weapons when
selling them. Previously only the Value was shown. Now we show
Power Level as well.
Also rename header "Cash" to "Credits" for consistency.
> shop_weapon.php: Sell Weapons shows power level

- htdocs/css/shared.css
Style `button` and `input[type=submit]` elements with pointer
cursors by default.
Since our default style is not obviously a button, this makes
it clearer when elements are clickable.
> shared.css: use pointer cursor for submittables

- engine/Default/shop_ship.php
- engine/Default/shop_weapon.php
Instead of naming shops "Ship Dealer" or "Weapon Dealer", use the actual name of each shop location.
Closes #582.
> Use real shop names

- templates/Default/engine/Default/includes/PlanetList.inc
Capitalize the word "none" when there are no Supplies on a planet,
for consistency with the "Nothing" when there is no Build.
> PlanetList.inc: none -> None

- admin/Default/1.6/universe_create_save_processing.php
- db/patches/V1_6_63_05__op_leader_role.sql
- engine/Default/alliance_create_processing.php
- engine/Default/alliance_option.php
- engine/Default/alliance_roles.php
- lib/Default/SmrAlliance.class.inc
- templates/Default/engine/Default/includes/AllianceRole.inc
Adds the ability for access to the "Schedule Operations" page to be given to any alliance role. Previously this was restricted to the "*".
> Op leader permission for alliance roles

- lib/Default/SmrPlanet.class.inc
- lib/Default/smr.inc
Previously, there was a flat chance to destroy each type of structure.
Generators/Bunkers = 50%
Hangars = 33%
Turrets = 17%
With the addition of new structures, we need a more formulaic method
to choose a structure. So we use the following formula:
% Chance = (Num Buildings / Max Buildings) / Build Time
Therefore, you're more likely to lose structure types that you have
a lot of (compared to how many the planet can support), and types
that take longer to build have a lower chance to be lost.
For a max level Terran planet, the chances work out to be similar
to the original constant values:
Generators = 60%
Hangars = 30%
Turrets = 10%
(Added a `getWeightedRandom` function to help pick the structure
to lose given an array of keys and weights.)
> SmrPlanet: change how we choose structure to destroy

- db/patches/V1_6_63_07__ship_changes_game122.sql
Thief:
+10 holds (150 -> 160)
Assassin:
+1 hp (4 -> 5)
Death Cruiser:
+1 hp (5 -> 6)
-25 mines (125 -> 100)
Advanced Carrier:
-50 shields (750 -> 700)
+50 armour (100 -> 150)
-25 drones (275 -> 250)
The changes to the Assassin and ITAC are to help fix the relative
win % chances of the hunter ships. This addresses the most over-
and under-powered hunters.
The Thief and DC are modified in relation to the Assassin. The
Thief gets a very minor boost to trade potential, and the DC trades
a little bit of utility for a more reasonable number of weapons.
> Minor ship changes starting Game 122

- templates/Default/engine/Default/preferences.php
Opening the Chat Sharing preferences without first joining a game
was causing a database error, since the Chat Sharing engine code
depends on `$player`. The easiest way to fix this is to add the
link to the game-specific preferences at the top of the page, rather
than with the account-specific preferences below.
This moves the Chat Sharing away from its natural place next to
the Discord ID/IRC Username options, but it is a small price to pay.
> preferences.php: move Chat Sharing to game options

- engine/Default/validate_processing.php
If you clicked "Validate me now!" without entering a validation
code, we would silently skip the validation check (and the account
would still not be validated). This was misleading, so now we
always do the validation check unless "I'll validate later." is
clicked.
We also display any error messages on the validation page itself,
since otherwise you can't get back to it after an error (e.g. an
incorrect validation code is entered) without relogging, which was
not very intuitive.
> validate_processing.php: don't silently skip check

- db/maintenance/cleanup_old_data.sql
* player_read_thread
* weighted_random
These are the largest remaining tables that have no usefulness
after a game ends.
> cleanup_old_data.sql: add tables to clean up

- templates/Default/engine/Default/includes/PlanetList.inc
At least one column of a table has to _not_ have the `shrink`
attribute for any of the `shrink` attributes to have an effect.
We want the planet image (column 1) to shrink, so we remove the
attribute from the "Name", "Owner", and "Build" columns. This
results in a spacing that seems okay.
> PlanetList.inc: fix non-shrinking table columns

- README.md
Retain only the docker-compose instructions for using the codebase.
The pure docker and native installation instructions are much more
involved (and outdated), and it is easier to understand and use the
docker-compose instructions.
Also remove VersionEye badge, since it no longer exists.
> README.md: simplify usage instructions

- db/patches/V1_6_63_09__remove_old_account_id.sql
- htdocs/login_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/SmrSession.class.inc
This static variable is no longer used, so there is no need to
keep it around. We also remove it from the `active_session` table.
> Remove old_account_id from SmrSession

- engine/Default/preferences_processing.php
- htdocs/login_create_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- templates/Default/engine/Default/preferences.php
Three somewhat independent password-related improvements:
---------------
preferences_processing.php: fix change password bug
Fix a bug that let you change your password even if you entered the
wrong current password.
The SmrAccount::checkPassword method was wrong because it didn't
hash the input password before checking it against the stored hash,
so it always returned "false".
However, the "Current Password" input in the "Change Password"
option in preferences was also wrong in a way that cancelled out
the SmrAccount error, because it would only trigger the "Your current
password is wrong" error if `checkPassword` returned "true"!
To fix this:
* flip the logic in the `checkPassword` call in preferences
* compare the hashed input password to the stored password
--------------- …
> Password-related bugfixes and cosmetics

- htdocs/css/login.css
The default input element padding in Chrome sized everything
correctly, but the img layout in Firefox was off by 1px.
Set the padding explicitly so that the login page looks the
same between Chrome and Firefox.
Without this change, the login box in Firefox/IE looked like this:
> login.css: fix inputbox padding for Firefox

- docs/Dockerfile
This reduces the intermediate image size from ~1.2GB (with the
standard php-cli image) to ~0.7GB. All auxilliary php services
now use the php-cli-alpine image.
To get alpine to work with phpDox, we needed to use an updated
iconv extension. This is a bit of a hack, but gets the job done.
See https://github.com/docker-library/php/issues/240.
> Use php-cli-alpine for api-docs image

- htdocs/images/warp_chart.svg
- htdocs/js/map_warps.js
- htdocs/map_warps.php
- templates/Default/engine/Default/GalaxyMap.inc
Use the d3 directed graph javascript library to create an interactive
warp map.
The map is accessible through a link in the Galaxy Map.
Also restyle the "Switch galaxy" dropdown menu in a consistent style.
> Add interactive warp map

- htdocs/config.php
Display the server time in UTC, for two reasons:
1. It is not subject to any daylight savings shifts, which makes
it more reliable.
2. It is a standard time that most people use (or would expect)
when coordinating worldwide activities.
Now seems like a good time to make this change, since we're not yet adjusted to the new US time shift.
> config.php: switch from CET to UTC

- db/patches/V1_6_59_01__classic_ship_reverts.sql
Flyway recently (v5.2.1) switched from the MariaDB driver to MySQL.
Unlike MariaDB, MySQL has a strict requirement that comment lines
beginning with "--" have at least one whitespace after them before
the comment begins.
One of our patches was missing this whitespace, and needs to be
updated for compliance with the MySQL requirement. The checksum
for any previous applications of this patch will need to be updated.
(The new checksum is -884764634.)
> Fix invalid MySQL syntax in Flyway patch

- admin/Default/account_edit_processing.php
- engine/Default/preferences_processing.php
- lib/Default/SmrPlayer.class.inc
Since names that are changed by admins are usually inappropriate,
we will no longer display what the original name was in the news
message, only the player ID.
When players change their own name, both the old and new name will
continue to be displayed.
> Do not display previous name when admin changes player name

- lib/Default/council.inc
The President must be one of the council members, otherwise there
is no President.
This issue was introduced in 75772c1846d, which caused the President
to be chosen as the first player (in descending experience) to have
a qualifying alignment, even if they weren't in the council.
This fix is a slight performance regression.
> council.inc: fix how President is chosen

- .dockerignore
- .gitignore
- docker-compose.yml
For data that we care about (in this case, the game database
and the player uploads), it is easier to manage a local directory
than an anonymous data volume. In particular, back up and restore
can be done without interacting with docker (if desired), and we
have more control over where the data is located (e.g. if we want
it on a raided partition instead of confined to wherever docker
puts the data volumes in the OS partition).
> Migrate away from anonymous data volumes

- engine/Default/beta_func_processing.php
- engine/Default/beta_functions.php
- engine/Default/planet_stockpile_processing.php
- lib/Default/SmrPlanet.class.inc
- templates/Default/engine/Default/beta_functions.php
Add the following options to Beta Functions:
1. Set the planet buildings to max
2. Set the planet defenses to max
3. Set the planet stockpile to max
These options can be accessed when you are in a sector with a planet,
which should help with debugging / testing planets.
Some minor adjustments to SmrPlanet were needed to accomplish this.
> Add planet modifiers to Beta Functions

- engine/Default/alliance_treaties.php
- engine/Default/alliance_treaties_confirm.php
- engine/Default/alliance_treaties_confirm_processing.php
- engine/Default/alliance_treaties_processing.php
- lib/Default/SmrTreaty.class.inc
- templates/Default/engine/Default/alliance_treaties.php
- templates/Default/engine/Default/alliance_treaties_confirm.php
Break up the monolithic treaty scripts into template, confirm,
and processing pages.
Factor the treaty types into a new SmrTreaty class, and use the
treaty type keys consistently to facilitate looping over each of
the types instead of writing them all out explicitly.
> alliance_treaties.php: convert to template

- htdocs/js/ajax.js
If no elements on the page changed, then ajax would stop refreshing.
In practice, this would usually happen any time the `tod` (server time)
and `rt` (script runtime) elements were identical between updates,
which happened just often enough for people to notice it freezing
from time to time, but not often enough to feel like it was
reproducible.
To fix this, we simply remove the restriction that there must be at
least one updated element.
Thanks to @Page-  for helping to debug this issue!
> ajax.js: fix a longstanding cause of ajax freezing

- admin/Default/log_anonymous_account.php
- templates/Default/admin/Default/log_anonymous_account.php
Also completely rewrite its guts.
* Vastly simplify database queries and logic for organizing the logs.
* Fix the display so that transactions are separated by game.
Previously, all transactions for each anon account number were
displayed together (no delineation by game_id, but anon_id is
not a unique index!).
* Display the time of each transaction.
* Color the transaction for deposits (green) and withdrawals (red).
* Move the back button to the top of the page so you don't have to
scroll all the way to the bottom.
> log_anonymous_account.php: convert to template

- htdocs/css/shared.css
- templates/Default/engine/Default/chess_play.php
- templates/Default/engine/Default/includes/ChessMoves.inc
* Use lighter color black squares. Since the unicode chess symbols
have transparent white pieces, a darker black square makes them
harder to see. A light gray square makes both player colors more
visible.
* Make the chatbox for the move list less wide so that the middle
panel fits within the default page width.
* Start the chess move display at move 1 instead of move 0 (since
it comes from the index of an array, we just add 1).
New:
Old:
> Minor chess display changes

- config/SmrMySqlSecrets.sample.inc
- lib/Default/MySqlDatabase.class.inc
- lib/Default/Smr12HistoryMySqlDatabase.class.inc
- lib/Default/SmrClassicHistoryMySqlDatabase.class.inc
- lib/Default/SmrMySqlDatabase.class.inc
The mysqli database connector provides a (relatively) secure error
message when a database connection fails, e.g.,
Connection failed: Access denied for user 'smr'@'XXX.XX.X.X' (using password: YES)
and does not directly throw an exception, which would display the
password passed to its constructor (since PHP backtraces will print
function arguments in plain text). However, since our function
`MySqlDatabase::error` takes the mysqli error message and packages
it into an exception, the password is leaked by the `MySqlDatabase`
constructor line of the resulting backtrace. But we want to be able
to raise an exception (securely) since that's how we perform our
standard error handling.
Fortunately, we can plug this leak by loading the password directly
in MySqlDatabase instead of the derived …
> Prevent mysql password leaking in backtraces

- htdocs/config.inc
- htdocs/login.php
- htdocs/map_galaxy.php
- htdocs/offline.php
- lib/Default/smr.inc
If we initialize the Template at the config.inc level, then it will
be reused between pages that call `forward`. In general, this is not
a problem, because we typically don't set template variables until
we're on the final page that we intend to display. However, it has
caused a problem in at least one case, where we forwarded to the
error.php page after the `PageTopic` variable had already been set
(thus triggering an Exception).
This particular issue could have been obviated by not setting the
`PageTopic` template variable until after all `create_error` sanity
checks had been performed on the display page. But this is not a
safe assumption (it depends on the coder always remembering when to
assign to the template), nor does it fix any cases that we haven't
yet encountered.
Instead, …
> Create a new Template for each page

- htdocs/loader.php
- lib/Default/shop_goods.inc
- lib/Default/smr.inc
For pages generated by `loader.php`, initialize all globals at global
scope (usually as null, unless the variable is sufficiently simple).
Then load them with the `globals` keyword within `do_voodoo`, which
will be primarily responsible for setting the appropriate values.
We no longer need to use the `$GLOBALS` superglobal, so we remove
that altogether.
Also, do not use global keyword with $_REQUESTS (since it is a
superglobal).
> Change how globals are handled

- lib/Default/AbstractSmrShip.class.inc
Use standard array functions to swap, rotate, add, and remove weapons
from the `weapons` array. This streamlines the methods `removeWeapon`,
`moveWeapon{Up,Down}`, and `addWeapon` (replacing the clunkier for-
loops and temporary variables used previously).
> SmrShip: simplify weapon reordering methods

- engine/Default/sector_scan.php
- templates/Default/engine/Default/sector_scan.php
* Add a navigation menu
* Rearrange vessel/force scan table
* Add "#" to sector number in Rescan/Enter buttons
Also fix HTML warnings:
* `<table>` inside `<p>`
* Obsolete `align` attribute
> sector_scan.php: change layout

- engine/Default/error.php
- engine/Default/shop_goods_processing.php
- htdocs/error.php
- templates/Default/admin/Default/1.6/universe_create_locations.php
- templates/Default/admin/Default/1.6/universe_create_warps.php
- templates/Default/admin/Default/account_edit.php
- templates/Default/admin/Default/ip_view.php
- templates/Default/engine/Default/GalaxyMap.inc
- templates/Default/engine/Default/alliance_option.php
- templates/Default/engine/Default/changelog_view.php
- templates/Default/engine/Default/chess_play.php
- templates/Default/engine/Default/game_join.php
- templates/Default/engine/Default/includes/EndingJavascript.inc
- templates/Default/engine/Default/includes/Head.inc
- templates/Default/engine/Default/includes/LeftPanel.inc
- templates/Default/engine/Default/includes/LocalMapJS.inc
- templates/Default/engine/Default/includes/RightPanelPlayer.inc
- templates/Default/engine/Default/preferences.php
- templates/Default/engine/Default/shop_goods_trade.php
- templates/Default/engine/Default/shop_hardware.php
- templates/Default/engine/Default/skeleton.php
- templates/Default/engine/Default/trader_examine.php
Make the following changes for better adoption of HTML5:
* Remove `type` attributes from `<script>` and `<style>` tags.
* Replace the `<big>` element with CSS.
Also fix an issue with the wrong number of columns in the skeleton table.
> Fix obsolete html

- engine/Default/shop_goods_processing.php
- lib/Default/AbstractSmrPort.class.inc
Instead of overwriting `$gained_exp` when stealing, handle this case
in `SmrPort::calculateExperiencePercent` directly. Doing this has
three benefits:
1. We can early return from the function, avoiding a bunch of math.
2. Everything is handled consistently in this one function.
3. We avoid a division-by-zero warning in a specific case.
The division-by-zero was occuring when stealing with low relations
(i.e. between -300 and 0) and for low cost goods (e.g Tier 1). For
this regime, the ideal price was ludicrously low (e.g. 7 credits
for 100 Food). At this point, the 0-relations offer price is always
going to be equal to the ideal price (since it is ~87% of the ideal
price). Since `$idealPrice - $offerPriceZeroRelations` is in the
denominator, we get a div-by-0. This does not occur for …
> Change how full exp is awarded for stealing

- lib/Default/AbstractSmrPort.class.inc
- templates/Default/engine/Default/shop_goods_trade.php
Modify the ideal price trade formulas in the following ways:
**DISTANCE**
Ideal price grows more slowly with distance (and scales the same
with distance for both buy & sell). This was needed because the
sell prices for jump routes (>10 sectors) were too lucrative.
**RELATIONS**
Reduce the penalty for having less than perfect relations. This
effect was way too severe for relations below zero.
BUGFIX: The price to buy goods is now correctly scaled with relations.
Previously, this was mostly backwards -- you'd get a cheaper price
the worse your relations were (due to a perhaps accidental quadratic
term in the equation). This makes low-relations purchases cost more.
**PORT LEVEL**
Remove the port level factor in the buying formula. This was an
unnecessary complication that needlessly punished …
> Modify trading formulas

- engine/Default/current_sector.php
- lib/Default/smr.inc
- templates/Default/engine/Default/includes/PlanetCombatResults.inc
- templates/Default/engine/Default/includes/PortCombatResults.inc
The combat summary display on the Current Sector page (for allies
contributing to the combat) will now include a link to the combat
log report.
This affects both Port Raids and Planet Busts.
> Add combat log links to Current Sector display

- lib/Default/SmrPlanet.class.inc
With a 15% chance every 70 damage (the previous algorithm), you
would destroy the following number of structures in a max level
planet bust on average:
Terran - 18 structures (6 levels)
Dwarf - 13 structures (4.33 levels)
This is a bit too much, especially considering how long it takes
to build structures when near the max planet level.
Increasing the damage threshold from 70 -> 100 achieves a less
severe result:
Terran - 13 structures (4.33 levels)
Dwarf - 9 structures (3 levels)
This might still be too high, but it is a step in the right
direction, and will be a good place to evaluate further.
> Slightly decrease structure damage in planet busts

- engine/Default/toggle_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/RightPanelShip.inc
* Clicking the Show/Hide link no longer stops automatic ajax updates.
* Multiple clicks of Show/Hide on the same page are now respected.
Add `'AJAX'=>true` to the container used for the JavaScript-only
Show/Hide link so that when we run toggle_processing.php,
`USING_AJAX=true`.
Since the Show/Hide HTML changes are performed exclusively in JS,
the only purpose of the call to toggle_processing.php is to update
the `display_weapons` setting for the SmrPlayer. Therefore, we will
do an early exit in toggle_processing.php (when triggered with ajax)
so that the remainder of `do_voodoo` (i.e. template display and
SmrSession updating) does not get run.
The only somewhat backwards aspect of this fix is that we had to make
SmrPlayer::setDisplayWeapons update the `player` database table
directly. …
> Fix weapon Show/Hide ajax

- .env.sample
- README.md
* Include phpMyAdmin instructions in the MySQL section.
* Make it clearer that the setup must occur in a clone of the
repository.
* Add a `.env.sample` file and re-arrange order of documentation
so that the configuration file instructions come first.
* Add a note to the .env file about dashes in hostnames on Windows
machines (due to experiences with one user).
> Improve installation documentation

- engine/Default/chess_move_processing.php
- engine/Default/chess_play.php
- htdocs/js/ajax.js
- lib/Default/ChessGame.class.inc
- lib/Default/SmrSession.class.inc
- lib/Default/Template.class.inc
- lib/Default/smr.inc
- templates/Default/engine/Default/chess_play.php
Chess moves now have a more standard processing procedure, using containers and forwarding as we would normally expect.
The ajax updating infrastructure has been slightly modified to make this happen correctly, notably by disentangling how we set `AJAX_CONTAINER` and `USING_AJAX`. Roughly, they now mean:
* `AJAX_CONTAINER`: a page that will be accessed by ajax submitting a link (with possible XML returns)
* `USING_AJAX`: an ajax trigger or auto-update that should not require a sector lock
These variables will likely need to be documented and/or renamed for clarity, but I think there is more to do to simplify this infrastructure before that is done.
Also fixed a few bugs in ChessGame.class.inc that were causing ajax triggers (once working correctly) to update the content in unexpected …
> Fix chess ajax triggers

- engine/Default/forces_drop_processing.php
- lib/Default/smr.inc
Previously, dropping a single force using the "[x]" links on the
right panel would always take you to the Current Sector page.
However, if you are on the Local Map, it is likely that you want
to stay on the Local Map, and so we now do that in order to avoid
unnecessary clicking and page switching.
This may have some impact on gameplay, since the old behavior
does combine two actions together in a relevant way (e.g. dropping
a single mine and then going to the Current Sector page to attack).
We will want to monitor the community feedback from this change
before deploying it to the live server.
> Stay on Local Map when dropping single forces

- lib/Default/AbstractSmrShip.class.inc
Previous exp/damage ratios:
* vs players: 1/4
* vs ports/planets/forces: 1/20
New exp/damage ratios:
* vs players: 1/4 (unchanged)
* vs ports: 1/10 (2x higher)
* vs planets: 1/2 (10x higher)
* vs forces: 1/20 (unchanged)
Ports were increased by 2x because the exp was aggressively low.
There is not too much risk, so it should not be heavily rewarded,
but even at the increased level, it is 1/2 the exp you would make
trading a 1x route in an IST.
Planets were increased by 5x*2x = 10x. The 5x comes from the fact
that weapons do 1/5 their normal damage to planets (e.g. a HHG does
60 shield damage instead of 300), and the 2x is to bring it in line
with the change to ports. This is likely still too low.
The following exp will be earned from damage done (spread out across
all attackers).
- Level …
> Increase exp earned per damage to ports/planets

- lib/Default/AbstractSmrShip.class.inc
In player vs. player combat, if a team with more than 1 player had
a player with no weapons, then when checking if assists should be
awarded, we would get a warning when trying to iterate over the
'Weapons' index of the results array. This was because this index
was not initialized, and thus undefined if the player had no weapons.
We could fix this by skipping the check if 'Weapons' was not set,
but it is more robust to initialize 'Weapons' as an empty array.
> Initialize Weapons index in combat results array

- engine/Default/game_join.php
- engine/Default/hall_of_fame_new.php
- engine/Default/hall_of_fame_player_detail.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/SmrGame.class.inc
- lib/Default/hof.functions.inc
- lib/Default/smr.inc
- templates/Default/admin/Default/game_delete_confirm.php
* Lots of visual / performance / code improvements
* Fixed two bugs when viewing "Personal HoF" for other players:
1. It will display that player's ranks in the categories list instead of yours.
2. It will correctly display that player's name in the page topic instead of yours.
* Fix `SmrPlayer::sameAlliance` to check the game ID.
* Stop hiding HOF_ALLIANCE stats after a game has ended.
* Prevent rows from jumping around on ajax updates by secondary sorting on `account_id`.
* The All-Time HoF now excludes live games from all categories (not just HOF_ALLIANCE stats).
> Various Hall of Fame fixes

- engine/Default/skeleton.php
- lib/Default/Template.class.inc
- lib/Default/smr.inc
- templates/Default/default.inc
We have _at long last_ (really... it's taken forever) converted all
pages to templates. Therefore, we can finally remove the extra
processing of `$PHP_OUTPUT`!
If a template file is not found, it will raise an exception.
Closes #30.
> Finalize transition to templates

- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/DummyPlayer.class.inc
- lib/Default/SmrPlayer.class.inc
* Use existing `setNewbieTurns` method instead of complicating the
`setTurns` method with newbie turn logic.
* Remove the `updateLastActive` argument from all the turns methods.
Taking turns will always update the "last active" time, and giving
turns will never do this (and so we move the code that sets it out
of `setTurns` and into `takeTurns`).
> SmrPlayer: simplify turns interface

- admin/Default/1.6/universe_create_planets.php
- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/1.6/universe_create_sector_details.php
- lib/Default/AbstractSmrPort.class.inc
- lib/Default/SmrPlanet.class.inc
- templates/Default/admin/Default/1.6/universe_create_planets.php
- templates/Default/admin/Default/1.6/universe_create_sector_details.php
- templates/Default/admin/Default/1.6/universe_create_sectors.php
Revamped the "Edit Sector" page in the Uni Gen. Additional information about planets will be specified, and you can now select specific port goods if you want to.
Also includes other minor tweaks to the Uni Gen display and a refactoring / addition of some methods to `SmrPort`.
> Uni Gen: add port good selection

- engine/Default/council_embassy_processing.php
- engine/Default/game_join_processing.php
- engine/Default/shop_ship.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/AbstractSmrPort.class.inc
- lib/Default/AbstractSmrShip.class.inc
- lib/Default/Globals.class.inc
- lib/Default/SmrAlliance.class.inc
- lib/Default/SmrPlanet.class.inc
- tools/irc/channel_msg_sd.php
Remove the following Globals methods:
* getGameDescription
* getGameSpeed
* getGameMaxTurns
* getGameMaxPlayers
* getGameCreditsRequired
* getGameIgnoreStats
* getAllianceMaxPlayers
* getAllianceMaxVets
* getStartingCredits
Some of these were unused. For those that were used in some places,
we can easily replace them with calling the methods directly on an
SmrGame instance that we can access.
We did need to add the following methods to more easily access an
SmrGame instance in some classes:
* SmrPlanet::getGame
* SmrAlliance::getGame
* SmrShip::getGame
* SmrPort::getGame
Also some minor refactoring of game_join_processing.php.
> Remove unnecessary SmrGame wrappers in Globals

- docker-compose.yml
- lib/Default/MySqlDatabase.class.inc
Fixes the following PHP Warning:
```
DOMDocument::loadHTML(): Input is not proper UTF-8
```
The charset for the `smr_live` database is currently set to `latin1`,
since it was created before UTF-8 was standard in MySQL. This caused
any UTF-8 characters to be encoded in the database in what looked to
be gibberish, even though querying and displaying those characters in
HTML worked correctly (since the mysql server and client were using a
consistent encoding).
We want the characters to be stored in UTF-8 in the database, so we
need the charset to be `utf8` for both server and client. By setting
the charset when the mysql server starts up, the client will default
to the server's charset, which avoids an additional query that would
be incurred by using
```php
self::$dbConn->set_charset('utf8') …
```
> docker-compose.yml: set mysql charset to utf8

- htdocs/album/album_comment.php
- htdocs/loader.php
- htdocs/login.php
- htdocs/login_create_processing.php
- htdocs/login_processing.php
- htdocs/map_galaxy.php
- htdocs/map_warps.php
- lib/Album/album_functions.php
- lib/Default/SmrSession.class.inc
- lib/Default/smr.inc
- tools/npc/npc.php
Make the `account_id` attribute private and replace direct calls
to it with the setter/getter methods.
This makes it more explicit when and how we are setting the account.
> SmrSession: add account setter/getter methods

- engine/Default/mission_abandon_processing.php
- engine/Default/mission_decline_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/Globals.class.inc
- lib/Default/Mission.class.inc
- templates/Default/engine/Default/includes/Missions.inc
When you can accept a mission, you now also have the option
to decline it, which will prevent it from displaying again.
Once you have accepted a mission, you can now also abandon
it at any time, which will allow you to restart it later.
Use a new `Mission` class to hold the HREF methods:
* getAcceptHREF (from Globals::getAcceptMissionHREF)
* getClaimRewardHREF (from Globals::getClaimMissionRewardHREF)
* getDeclineHREF (new)
* getAbandonHREF (new)
Add method `SmrPlayer::declineMission`, which uses a new "step"
argument to `addMission` to reuse that code to effectively add
the mission in its completed state.
Also remove the `SmrPlayer::getCompletedMissions` method because
it is unused and non-functional (it queries a non-existent table
`player_completed_mission`).
> Add ability to decline and abandon missions

- htdocs/config.php
- templates/Default/login.inc
- tools/irc/channel.php
Since IRC is usually empty these days, players join and don't see
anyone and then quickly leave. This notification is sent whenever
a new player joins IRC to help explain where everyone is and how
to communicate with them.
Also removed a few custom join notifications for specific people.
To avoid being spammy, this is only displayed for people that Caretaker has not seen before.
> Notify IRC users about discordbot

- lib/Default/AbstractSmrPlayer.class.inc
Specifying the image dimensions allows the browser to allocate
space for the image before the image is downloaded. This prevents
other page elements from being shifted after the image is loaded
(which makes the page flicker and look like it's jumping around).
This is certainly worth a small amount of additional text being
served.
> Add img dimensions to President icon

- engine/Default/alliance_stat_processing.php
If a player has permission to change some alliance info, but *not*
`change_mod` permission, then this will result in the following
warning:
Undefined variable: url in /smr/engine/Default/alliance_stat_processing.php on line 28
Fix this by first checking that `isset($url)` before using it.
> alliance_stat_processing.php: fix PHP warning

- db/patches/V1_6_63_20__chess_game_id.sql
- engine/Default/chess.php
- lib/Default/ChessGame.class.inc
- templates/Default/engine/Default/chess.php
Having chess matches span multiple games caused two major problems:
1. It was a sneaky way to keep track of who a player is from game
to game, circumventing the anonymity that everyone assumed they
had.
2. If one player in a match doesn't join a subsequent game, then
we can get any number of Exceptions due to trying to access
methods on a player that is `null`.
The simplest solution to these problems is to have matches end when
the game ends.
To implement this, we need to make a few changes:
* Add a `game_id` column to the `chess_game` table.
(Since we can't know what game_id past chess games were associated
with, they will be assigned `game_id=0`.)
* Replace the `ChessGame` method `getOngoingAccountGames` with
`getOngoingPlayerGames`, which is restricted to matches in the
current game.
* …
> Chess matches will now end with each game

- htdocs/login_create.php
- htdocs/resend_password.php
- htdocs/reset_password.php
- templates/Default/admin/Default/1.6/GameDetails.inc
- templates/Default/admin/Default/1.6/universe_create_galaxies.php
- templates/Default/engine/Default/alliance_create.php
- templates/Default/engine/Default/game_join.php
- templates/Default/engine/Default/planet_ownership.php
- templates/Default/socialRegister.inc
The `required` attribute is a less destructive way of telling a
user that a form field cannot be left blank than redirecting to an
error page (which usually results in losing any form fields already
filled in and having to navigate back to the page).
It can easily be circumvented (by falsifying form data or by not
having an HTML5-compatible browser), so the checks on these fields
in the PHP need to remain.
However, it is still very useful, so I suspect I'll be adding it
more systematically throughout the code later.
> Add required HTML5 attribute to some input fields

- config/config.specific.sample.php
- templates/Default/login.inc
Uses the global config variable `GOOGLE_ANALYTICS_ID`.
Currently we're only tracking the login page (since it is useful to
know where we receive traffic from). Internal tracking is less
important, but it can easily be added later.
Closes #137.
> login.inc: add optional Google Analytics tracking

- admin/Default/1.6/upload_smr_file_processing.php
- engine/Default/smr_file_create.php
- htdocs/config.php
To make sure that we don't inadvertently use an incompatible SMR
file when we're loading a game from file in the Uni Gen, we add a
file version to the metadata that we can check against.
Also add the date the file was created (in a comment) for reference.
> Add FileVersion metadata to SMR file

- admin/Default/box_view.php
- admin/Default/notify_view.php
- engine/Default/hall_of_fame_new.php
- engine/Default/hall_of_fame_player_detail.php
- engine/Default/smr_file_create.php
- lib/Default/Globals.class.inc
- lib/Default/smr.inc
Replace this with explicit calls to methods of `SmrGame`. In some
cases we switch to using the "Display Name", which includes the
game ID.
> Globals: remove getGameName method

- admin/Default/npc_manage.php
- admin/Default/npc_manage_processing.php
- engine/Default/alliance_create_processing.php
- engine/Default/alliance_leadership_processing.php
- engine/Default/alliance_roles_processing.php
- engine/Default/beta_func_processing.php
- engine/Default/course_plot_nearest_processing.php
- engine/Default/course_plot_processing.inc
- engine/Default/course_plot_processing.php
- engine/Default/course_plot_result.php
- engine/Default/game_join_processing.php
- htdocs/config.php
- htdocs/login_create_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/AbstractSmrShip.class.inc
- lib/Default/AdminPermissions.class.inc
- lib/Default/RouteGenerator.class.inc
- lib/Default/SmrAlliance.class.inc
- lib/Default/SmrPlayer.class.inc
- templates/Default/admin/Default/npc_manage.php
- tools/npc/npc.php
This admin tool replaces some of the logic in the `npc.php` script to create NPC accounts/players/alliances. It also allows us to add new NPC slots and to set their active status, which previously could only be done directly inside the database. The name and alliance specified in `npc_logins` are now only default values -- these can be changed at creation time (so that, e.g., you don't need to create an entirely new NPC account just to have a different NPC name).
Some engine pages needed to be refactored into class methods (`SmrAlliance::createAlliance` and `SmrPlayer::createPlayer`) and several other methods needed to be added.
See commit messages for complete details.
> Add an Admin Tool to manage NPCs

- admin/Default/1.6/universe_create_sectors.php
- engine/Default/bar_galmap_buy.php
- engine/Default/smr_file_create.php
- htdocs/map_galaxy.php
- lib/Default/AbstractSmrLocation.class.inc
- lib/Default/AbstractSmrPort.class.inc
- lib/Default/MySqlDatabase.class.inc
- lib/Default/SmrForce.class.inc
- lib/Default/SmrGalaxy.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/SectorMap.inc
We have a lot of methods that get an entity for a given sector
by querying the database if it is the first time the entity has
been requested. If we're performing a separate query for each
sector in a galaxy, then the database communication overhead
becomes the dominant cost.
On these pages, we can mitigate this overhead cost by performing
a single query for the entire galaxy to cache all the entities
that will be needed later.
The caching infrastructure was already set up for the most part,
we just needed methods to operate on a galaxy.
Adds galaxy-wide static caching methods to the following classes:
* SmrForce
* SmrPlanet
* SmrPlayer
* SmrPort
* SmrLocation
These are a bit more complicated than `SmrSector::getGalaxySectors`
because they only conditionally exist, but the principle is …
> Optimize galaxy-wide database queries

- admin/Default/1.6/universe_create_sectors.php
- htdocs/js/ajax.js
- lib/Default/SmrSession.class.inc
- templates/Default/admin/Default/1.6/universe_create_sectors.php
- templates/Default/engine/Default/includes/SectorMap.inc
Galaxy maps are very large, and the process of manually adjusting
sector connections was slowed down by the fact that adding/removing
a wall reset the page display to the top left.
By using ajax, the process is much faster because the position on the
page remains unchanged. It also reduces bandwidth because only a small
amount of data on the page is modified, and so we don't need to serve
the entire page each time.
Also made some additional bugfixes to `1.6/universe_create_sectors.php` and
`SmrSession.class.inc` that needed to be addressed to support this change.
> Use ajax to update Uni Gen sector walls

- htdocs/js/smr15.js
- lib/Default/VoteSite.class.inc
- lib/Default/smr.inc
- templates/Default/engine/Default/includes/VoteLinks.inc
Due to a security fix in Chrome 76 and Firefox 70, it is no longer
possible to execute javascript in a new tab. Therefore, we can no
longer call one of our js functions in a link that opens a new tab.
For example, the following will now open a blank page and then fail
to load "a" because `voteSite` is not defined in that tab's context:
```
<a href="javascript:voteSite(a,b)" target="_blank">
```
See https://bugs.chromium.org/p/chromium/issues/detail?id=992244
The fix to our voting links is to use a normal href link for the
external site (with `target="_blank"`), and then add an `onclick`
event to redirect the current page (if necessary, i.e. if free
turns are available):
```
<a href="a" onclick="window.location='b'" target="_blank">
```
The real `onclick` event is only slightly more …
> Fix voting links in new web browsers

- admin/Default/1.6/game_create.php
- admin/Default/1.6/game_create_processing.php
- admin/Default/1.6/game_edit.php
- admin/Default/1.6/game_edit_processing.php
- lib/Default/SmrGame.class.inc
- templates/Default/admin/Default/1.6/GameDetails.inc
Admins can now specify the starting political relations between races.
This can be modified as well, but only until the game has started.
Added a new method `SmrGame::setStartingRelations` to avoid code
duplication between game create/edit.
> Uni Gen: specifiable starting political relations

- config/npc/config.specific.sample.php
- lib/Default/ChessGame.class.inc
- lib/Default/ChessPiece.class.inc
- tools/npc/chess.php
- tools/npc/npc.php
Put active NPCs to work for all enabled games instead of hard-coding
the `NPC_GAME_ID` in the NPC configuration file (which needed to be
manually updated each game). This is the simplest way to avoid manual
intervention for NPCs with each new game.
This new scheme uses the SmrSession to track which NPC is working,
rather than using globals in npc.php.
NOTE: This scheme may not work correctly if multiple games are active,
one of which is a non-Default game (because it may autoload the wrong
version of libraries).
> npc.php: don't use a hard-coded game ID

- engine/Default/shop_goods_processing.php
- lib/Default/AbstractSmrPort.class.inc
Stolen goods has been working towards a port level increase.  Added a separate function for stealing goods to the port class so that theft bypasses port upgrade calls.
> SmrPort: stolen goods bugfix

- engine/Default/shop_goods_processing.php
- lib/Default/AbstractSmrPort.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/shop_goods.inc
* All races will now gain/lose relations when trading with Neutral ports, not just Alskant.
* Raiding a Neutral port will now decrease Neutral relations, just like with all other port races.
* Getting caught stealing will now decrease relations the same amount as a bad bargain. (Note: Successful stealing no longer increases relations thanks to the bugfix in #765.)
> Gameplay changes to relations

- tools/npc/npc.php
This function was only dumping illegal goods when it was in a sector
that offered federal protection. Since dumping cargo is not allowed
in Fed sectors, this was causing an error, leaving NPCs unprotected
with illegal goods on board.
To fix this problem, we dump illegal goods before we plot to Fed.
For simplicity and safety, we do this unconditionally (regardless of
the reason the NPC is going to Fed).
If the NPC tries to plot to Fed with illegal goods on board while in
a Fed sector already, then this error will still occur, and I don't
think that it's worth coding a workaround into the AI. We can always
simply delete the NPC cargo if we must (NPCs don't necessarily need
to follow the rules the way players do).
> npc.php: fix handling of illegal goods in plotToFed

- htdocs/login_processing.php
- htdocs/login_social_create.php
- htdocs/login_social_processing.php
- lib/Default/SocialLogin.class.php
- lib/Default/SocialLogins/Facebook.class.php
- lib/Default/SocialLogins/Twitter.class.php
- lib/autoload.inc
- templates/Default/login.inc
* Add a separate page for displaying account creation via social login. This is necessary so that the display is not part of the processing page, which may have been contributing to errors from invalidated social credentials (e.g. if you refresh the page after you are prompted to create an SMR account).
* Clean up SocialLogin interface by abstracting the class and utilizing a new `SocialLogins` namespace for the derived classes.
Note: The autoloader function needed to be generalized to handle namespaces (which will be in a subdirectory with the same name as the namespace).
> Improve social login processing

- htdocs/map_warps.php
Add low-level tags (html, head, etc.) and place content elements
in the appropriate places (e.g. the `<script>` tags were outside of
`<body>`, which was invalid).
Also add a sensible title to the page.
> map_warps.php: fix HTML structure

- admin/Default/enable_game.php
- templates/Default/admin/Default/enable_game.php
When enabling games, you usually are interested in the most recently
created game, which will have the largest `game_id`. Reverse sort the
list of games in the dropdown list so that this game is at the top.
> enable_game.php: reverse sort games

- engine/Default/planet_defense_weapon_processing.php
- lib/Default/SmrPlanet.class.php
When adding a mounted weapon, it is possible that a weapon has been
added to the selected slot in the time between when the "Defense" page
was rendered and when the "Transfer" button was clicked.
To mitigate this (rare) scenario, the processing script will now raise
an error if the selected slot is already occupied.
Also refactor the common logic from moveMountedWeapon{Up,Down} into a
new function swapMountedWeapons.
> Prevent overwriting planet mounted weapons

- engine/Default/forces_drop_processing.php
This fixes an error that players would get when they leave an input
field on the forces_drop.php page blank.
In 4452a2dba9f, this script was modified to simplify the checks on
the input fields with the addition of the "number" HTML5 input types.
However, empty strings are valid HTML5 "number" type values, and this
was not accounted for in the PHP validation logic.
Add in an explicit check to set the value to "0" if the input value
is the empty string.
> forces_drop_processing.php: don't error on empty

- lib/Default/SmrPlayer.class.php
Significant optimizations were made to the Galaxy Map in 8379956c5,
including a new function `SmrPlayer::getGalaxyPlayers`, which used a
single database query to cache the results for all subsequent calls
to `SmrPlayer::getSectorPlayers` (to avoid making a separate database
query for each sector in the galaxy).
The optimization is fine in principle, but `getGalaxyPlayers` was
caching the wrong results because the query was not identical to the
one in `getSectorPlayers`. Most importantly, it didn't exclude players
on planets, and so the Galaxy Map was incorrectly displaying them
(even enemy players, which had serious gameplay implications).
The fix is simply to make sure the queries between the two functions
in SmrPlayer are consistent.
> Fix Galaxy Map showing traders on planets

- lib/Default/AbstractSmrPort.class.php
- lib/Default/SmrPlanet.class.php
- templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc
* Determine the number of downgrade chances up front to simplify the
looping condition.
* For SmrPlanet, return an array instead of an HTML string so that
we can report total structure losses. (E.g., instead of repeating
"This team destroys 1 generator" 3 times, it will simply say
"This team destroys 3 generators" once.)
> Improve Smr{Port,Planet}::checkForDowngrade

- admin/Default/album_approve.php
- engine/Default/album_edit.php
- engine/Default/chat_sharing.php
- engine/Default/hall_of_fame_player_detail.php
- engine/Default/preferences.php
- engine/Default/preferences_confirm.php
- lib/Default/AbstractSmrAccount.class.php
- lib/Default/hof.functions.inc
- templates/Default/admin/Default/account_edit.php
- templates/Default/engine/Default/album_edit.php
- templates/Default/engine/Default/alliance_pick.php
- templates/Default/engine/Default/feature_request_comments.php
- templates/Default/engine/Default/includes/HallOfFame.inc
- templates/Default/engine/Default/preferences.php
Add a new function `SmrAccount::getHofDisplayName`, which returns the
HoF name in a form that is suitable for display (i.e. all HTML special
characters are escaped). The existing `SmrAccount::getHofName` returns
only the raw HoF name.
Most notably, there are some HoF names that use the `&`, which when
displayed unescaped causes DOMDocument to issue a warning.
Also fixed the link to the user's album page on the "Edit Photo" page.
It was missing the `nick` query string param added in 9e11f611990a5f5.
It is also now url-encoded.
> Fix unescaped HTML special characters in HoF names

- Dockerfile
- docker-compose.yml
- htdocs/config.inc
- htdocs/config.php
- lib/Default/SmrSession.class.php
- tools/npc/npc.php
* Switch to the development php.ini instead of using the default php ini values when `PHP_DEBUG=1`.
* Use `E_ALL` for all modes (debug, beta, live).
* npc.php: 
- Try to convert all error events into exceptions so that we can shut down NPCs cleanly.
- Fix some issues with NPC error messages, and allow errors to be logged in-game an by e-mail.
> Improve error reporting and NPCs

- lib/Default/SmrWeapon.class.php
- lib/Default/WeightedRandom.class.php
when firing at 100 or greater accuracy there is no need for a weighted random roll.  the shot is already guaranteed to hit.  simply reporting the hit saves resources and should prevent the weight from being adjusted the wrong way.
> add trap to catch accuracy 100 or greater

- .travis.yml
- Dockerfile
- composer.json
- docs/Dockerfile
- tools/discord/Dockerfile
- tools/discord/composer.json
- tools/irc/Dockerfile
- tools/irc/composer.json
- tools/npc/Dockerfile
- tools/npc/composer.json
- Use "*" for ext-json dependency in composer.json since this extension
comes packaged with PHP and has switched to a versioning scheme that
mirrors the PHP version number.
- Update phpmailer minimum version in composer.json to 6.1.0, which
is the first version that tests against PHP 7.4.
- Install gcrypt package in docs/Dockerfile because the new XSL package
has incorrectly omitted it as a dependency. Otherwise, it has build
errors:
ld: cannot find -lgcrypt
ld: cannot find -lgpg-error
- Change version constraint operator in discord/irc/npc composer.json
files from "~" to "^" as per 5e903dadacdfeceba46.
- Update uopz from 6.0.1 -> 6.1.1, which adds PHP 7.4 support.
> Update to PHP 7.4

- templates/Default/engine/Default/includes/ForceTraderTeamCombatResults.inc
- templates/Default/engine/Default/includes/ForcesCombatResults.inc
- templates/Default/engine/Default/includes/PlanetCombatResults.inc
- templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc
- templates/Default/engine/Default/includes/PortCombatResults.inc
- templates/Default/engine/Default/includes/PortTraderTeamCombatResults.inc
- templates/Default/engine/Default/includes/TraderTeamCombatResults.inc
PHP 7.4 now warns when trying to index `null` like an array. We have
a lot of places (in the combat report code specifically) that relied
on this returning null without a warning.
Fixes the following warning:
> Notice: Trying to access array offset on value of type null
> Fix invalid array access in combat reports

- config/npc/config.specific.sample.php
- tools/npc/npc.php
To avoid an infinite loop, set an upper limit for the number of
actions an NPC can take in a single execution.
The sample limit is set to 2500 actions, which corresponds to about
a half hour of actions.
> npc.php: add NPC_MAX_ACTIONS

- lib/Default/smr.inc
The `strpos` and `substr` methods expect a string as input, even
though `number_colour_format` will typically be passed a float|int.
> smr.inc: fix types in number_colour_format

- lib/Default/AbstractSmrPort.class.php
The `SmrPort::stealGoods` method needs to be public, since it is used
in shop_goods_processing.php.
This bug was introduced in 508cb96bd0.
> SmrPort: fix visibility of stealGoods method

- engine/Default/bar_buy_drink_processing.php
- engine/Default/cargo_dump_processing.php
- engine/Default/shop_goods_processing.php
- engine/Default/shop_hardware_processing.php
- engine/Default/shop_ship_processing.php
- engine/Default/shop_weapon_processing.php
- htdocs/config.inc
- htdocs/config.php
- lib/Default/AbstractSmrAccount.class.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/AbstractSmrPort.class.php
- lib/Default/AbstractSmrShip.class.php
- lib/Default/SmrCombatDrones.class.php
- lib/Default/SmrForce.class.php
- lib/Default/SmrMines.class.php
- lib/Default/SmrPlanet.class.php
- lib/Default/SmrPlayer.class.php
- lib/Default/SmrScoutDrones.class.php
- lib/Default/SmrSession.class.php
- lib/Default/SmrWeapon.class.php
- tools/npc/chess.php
- tools/npc/npc.php
The functions `round`, `floor`, and `ceil` return a float type, even
though the returned value is a whole number. With strict types enabled,
we can not pass the result of one of these functions as an argument
that is type-hinted as an integer.
We add wrappers for these functions: `IRound`, `IFloor`, and `ICeil`,
which cast the return value as an int type.
NOTE: While `intval` is another method of converting to int types, we
want to avoid it, where possible, since it casts _any_ type to an int.
If we know the input is a float, then we should use `IFloor` instead.
> Add rounding functions that return integer types

- lib/Default/AbstractSmrPort.class.php
When razing was added back in 2013 (38e4b44aab), the refactoring of
the attacker list into `getAttackersToCredit` left a dangling database
reference in `creditCurrentAttackersForKill`, causing the following
notice (new in PHP 7.4) to be emitted:
Notice: Trying to access array offset on value of type null
As a result, the "Levels Raided" Hall of Fame category was not being
populated.
The simplest fix is to use the current level of the port, rather than
the level the port was at the last time each player attacked it (as it
is stored in the `player_attacks_port` table). Regardless of which way
the stats are awarded, the impact should be completely negligible.
> SmrPort: fix "Levels Raided" HoF credit

- engine/Default/game_play_preprocessing.php
- lib/Default/smr.inc
Remove a special case for preprocessing the "Play Game" page in the
`do_voodoo` function. This was only needed for the "Classic" version
of the engine (v1.2), which no longer exists. Now it uses forwarding
like all other pages.
> Refactor: Add game_play_preprocessing.php

- htdocs/css/Default.css
This change fixes the box spacing around links with the `submitStyle`
class so that they are styled the same way as submit input elements.
In Chrome, the user agent stylesheet specifies `padding` for submit
input elements as 1px (top/bottom) and 6px (left/right). Perhaps this
was different (0px and 8px) in the past or for other browsers. We
should probably set this explicitly, to ensure it is consistent with
the `submitStyle` class, but for now it is sufficient to assume a
recent Chrome version.
The `border-spacing` is a more subtle issue. We set it to 0 for a lot
of tables in our CSS, and it seems to be inherited by `submitStyle`
links contained in those tables. However, if the link is inside a
default table, then its `border-spacing` gets reset to the user agent
stylesheet default of …
> Make submitStyle links look like submit input elements

- engine/Default/buy_ship_name_processing.php
The existing scheme had a lot of PHP warnings and did not work as
expected. The new scheme has two main components:
1. Run the requested ship name through DOMDocument and check if it
triggers any HTML parsing errors.
2. Make sure all tags are matched, since DOMDocument allows some tags
to be unmatched (e.g. <span>).
We also disallow the `<marquee>` tag, since it is deprecated.
> buy_ship_name_processing.php: improve HTML validation

- admin/Default/npc_manage.php
- engine/Default/bank_anon_create.php
- engine/Default/buy_ship_name.php
- lib/Default/AbstractSmrAccount.class.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/AbstractSmrPort.class.php
- lib/Default/ChessGame.class.php
- lib/Default/Globals.class.php
- lib/Default/Mission.class.php
If an engine filename has the "processing" suffix, then it should
not ever be responsible for creating a display page (i.e. it should
always forward to another page).
Therefore, we should not ever be creating a processing container that
uses `skeleton.php` as the url.
> Don't use skeleton.php in processing containers

- .travis.yml
- engine/Default/game_play_preprocessing.php
- tests/strict_types.sh
This declaration must come at the top of every (non-template) file.
Since it is easy to accidentally omit when creating a new file, this
test will help ensure that such omissions are caught.
> Add test to check "strict_types" declaration

- engine/Default/bar_talk_bartender.php
- engine/Default/bar_talk_bartender_processing.php
- templates/Default/engine/Default/bar_talk_bartender.php
We were previously abusing the default value of `Request::get` to only
perform the processing work when request data was submitted. Instead,
we should be using a separate processing page, where the form input is
required.
> bar_talk_bartender.php: move processing to new page

- engine/Default/buy_ship_name.php
- engine/Default/buy_ship_name_preview.php
- engine/Default/buy_ship_name_preview_processing.php
- engine/Default/buy_ship_name_processing.php
- lib/Default/SmrPlayer.class.php
- templates/Default/engine/Default/buy_ship_name.php
- templates/Default/engine/Default/buy_ship_name_preview.php
* Split main page into two separate forms and delineate them more
clearly:
- The top form is where you can add a text or HTML ship name (which
is now required and uses the "Enter Name Here" initial value as a
placeholder instead).
- The bottom form is only for logos, and the image input is now
required.
* Split HTML preview off into its own page to simplify the request
processing.
* Add SmrPlayer::setCustomShipName method.
> Rewrite "Naming Your Ship" pages

- templates/Default/engine/Default/trader_status.php
Display the amount of credits in alliance account on trader status screen.  Because my spaceship should have that kind of capacity for communication. 
Assuming it works of course.  I have no local test bench.
> Alliance account

- engine/Default/bounty_place.php
- engine/Default/bounty_place_confirm.php
- engine/Default/bounty_place_confirm_processing.php
- engine/Default/bounty_place_processing.php
- templates/Default/engine/Default/bounty_place.php
Move input validation out of bounty_place_confirm.php and into
bounty_place_processing.php.
So the flow now looks like this:
bp.php -> Display the input form
bp_processing.php -> Validate the input data and forward
bp_confirm.php -> Display confirmation of input data
bp_confirm_processing.php -> Validate confirmation and process
This flow avoids any need for SmrSession::getRequestVar, and instead
we can just use the Request class in the processing pages. (When the
form validation was in bp_confirm.php, we were reprocessing the form
validation on each ajax refresh as well!)
> bounty_place.php: restructure forwarding

- engine/Default/bank_alliance.php
- engine/Default/bank_alliance_processing.php
- engine/Default/rankings_alliance_death.php
- engine/Default/rankings_alliance_experience.php
- engine/Default/rankings_alliance_kills.php
- engine/Default/rankings_alliance_profit.php
In 2c5a0340984352, the `getAllianceName` method of SmrPlayer was
renamed to `getAllianceDisplayName`; however, there were still some
calls to the old method name, causing the following error:
Call to undefined method SmrPlayer::getAllianceName()
These were all related to database operations, so we use the method
to get the raw alliance name, SmrAlliance::getAllianceName().
> Fix call to renamed SmrPlayer method

- engine/Default/shop_goods.php
- engine/Default/trader_status.php
- templates/Default/engine/Default/alliance_roster.php
- templates/Default/engine/Default/council_embassy.php
- templates/Default/engine/Default/council_vote.php
- templates/Default/engine/Default/includes/RightPanelPlayer.inc
- templates/Default/engine/Default/shop_goods.php
- templates/Default/engine/Default/shop_weapon.php
- templates/Default/engine/Default/trader_search_result.php
- templates/Default/engine/Default/trader_status.php
- templates/Freon22/engine/Default/skeleton.php
When the second argument is `true`, the race name becomes a link to
the given race's council page.
In some cases, this just simplifies the code (by generating the link
automatically instead of creating it manually). In others, it adds a
link to the race name where there was none before, e.g.:
* Alliance Roster (for player race)
* Weapon Shop (for weapon race)
> Use getColouredRaceName second argument consistently

- htdocs/login_social_processing.php
- lib/Default/SocialLogin.class.php
Because the social login type should be internally consistent between
the URL on the login page and the types accepted by the SocialLogin
class, we were raising an exception if the type passed in the URL to
the login_social_processing.php page was unknown. This helped ensure
that we would be notified (by bugs emails) if we accidentally broke
social logins.
Unfortunately, because the login_social_processing.php page is linked
on the public-facing login page, it has been added to a bunch of bot
databases. Most of the search engine spiders respect our robots.txt
file, but some do not, and SQL injection attacks obviously do not.
As a result, we get a lot of unwanted bugs emails where a bot uses an
outdated or malicious social login type. This is just too much noise,
and so we now redirect to …
> Throw user error on invalid social login type

- admin/Default/1.6/game_create_processing.php
- admin/Default/npc_manage_processing.php
- engine/Default/alliance_create_processing.php
- engine/Default/alliance_stat.php
- engine/Default/alliance_stat_processing.php
- htdocs/js/smr15.js
- lib/Default/SmrAlliance.class.php
- templates/Default/engine/Default/alliance_create.php
- templates/Default/engine/Default/alliance_roster.php
- templates/Default/engine/Default/alliance_stat.php
When creating and modifying alliances, there will now be three
recruitment options:
1) Open - Anyone can join freely, no password is needed
2) Closed - Players can only join by direct invitation
3) Password - Players can join by invitation or with a password
This creates a lot more flexibility for alliance leaders to manage
their membership.
Note: We use a combination of the `password` and `recruiting`
attributes of SmrAlliance to infer the "recruitment type". This
is perhaps not ideal, but it requires no database changes.
> Add open and closed recruiting options for alliances

- htdocs/config.inc
- htdocs/login_create_processing.php
- htdocs/login_processing.php
- lib/Default/MySqlDatabase.class.php
- templates/Default/login/login.php
* The `mysqli` calls now raise exceptions with complete error messages if they fail, so we do not need to handle these errors manually in `logException`.
* Prevent user passwords from being saved in plaintext (no longer stored in the SmrSession on account creation and masked if output in the `logException` message).
* Improve login form validation.
> Improve logging and login security

- engine/Default/planet.inc
- engine/Default/planet_attack_processing.php
- engine/Default/planet_kick_processing.php
- lib/Default/SmrPlanet.class.php
- lib/Default/SmrPlayer.class.php
- templates/Default/engine/Default/includes/PlanetCombatResults.inc
- templates/Default/engine/Default/includes/PlanetKillMessage.inc
- templates/Default/engine/Default/includes/PlanetList.inc
- templates/Default/engine/Default/includes/PlanetListFinancial.inc
- templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc
- templates/Default/engine/Default/includes/SectorPlanet.inc
- templates/Default/engine/Default/planet_examine.php
- templates/Default/engine/Default/planet_ownership.php
The `SmrPlanet` methods change as follows:
* Replace `getName()` -> `getDisplayName()` and escape HTML entities,
for consistency with the naming scheme for other classes that need
to display user-generated names.
* Replace `getDisplayName()` -> `getCombatName()`, which is now also
escaped for HTML, but the name change signifies that it should be
used only in the context of combat messages.
Note that there is no longer a function to return the raw planet name,
because there is nothing that needs it right now.
> Fix escaping of HTML entities in planet names

- db/patches/V1_6_63_22__track_alliance_invite.sql
- engine/Default/alliance_invite_accept_processing.php
- engine/Default/alliance_invite_cancel_processing.php
- engine/Default/alliance_invite_player.php
- engine/Default/alliance_invite_player_processing.php
- lib/Default/SmrInvitation.class.php
- lib/Default/SmrPlayer.class.php
- templates/Default/engine/Default/alliance_invite_player.php
This can be done from the "Invite Player" alliance option page.
It will also delete the invitation message sent to the player.
The new `SmrInvitation` class is responsible for interfacing with the
`alliance_invites_player` table.
Note that accepting one invitation no longer cancels all other open
invitations (with the notion that it's more similar to the scenario
with alliance passwords).
> Add ability to cancel alliance invitations

- engine/Default/buy_ship_name.php
- engine/Default/buy_ship_name_preview.php
- engine/Default/buy_ship_name_preview_processing.php
- engine/Default/buy_ship_name_processing.php
- lib/Default/Globals.class.php
- templates/Default/engine/Default/bar_main.php
- templates/Default/engine/Default/buy_ship_name.php
- templates/Default/engine/Default/donation.php
Refactor the `buy_ship_name*` pages so that they do not hard-code the
costs. Instead, they will be taken from this new `Globals` method,
which will allow us to, e.g., make them game-dependent.
Note that the `buy_ship_name.php` form was simplified a lot by passing
the costs through the container and by using `<button>` instead of
`<input>` (since a button's text display can be different from its
value).
> Add Globals::getBuyShipNameCosts

- admin/Default/announcement_create.php
- engine/Default/announcements.php
- templates/Default/admin/Default/announcement_create.php
The Announcements messages have been historically written with only
BBCode in mind. Recently, I've started using HTML (because it was
allowed), but this prevents us from easily escaping the unintended
HTML entities in old messages.
Rather than manually escaping all the old messages, I've decided to
disallow HTML in Announcements and instead rely on BBCode. All recent
messages using HTML have been manually converted to BBCode.
> announcements.php: escape HTML entities

- admin/Default/newsletter_send_processing.php
- engine/Default/game_leave_processing.php
- lib/Default/smr.inc
Some admin tools are fairly time intensive (sending newsletters,
creating games, editing galaxies, etc.), and there is no reason to
be hogging a sector lock during that time.
The easiest way to avoid sector locks is to exit the current game,
if any. We generalize `game_play_preprocessing.php` to work for the
"Admin Tools" link as well.
> Leave game when clicking on "Admin Tools"

- admin/Default/box_reply.php
- admin/Default/box_reply_processing.php
- admin/Default/box_view.php
- templates/Default/admin/Default/box_reply.php
- templates/Default/admin/Default/box_view.php
* Display which box we're viewing/replying to in the page title.
On the "Reply To" page, this fixes a copy+paste error that titled
the page as "Reply To Reported Messages".
* Add a back button on the "Reply To" page, which returns to the
message box we were viewing.
* Add the option to grant SMR reward credits from the "Reply To"
page. This is useful especially for the "Player Bug Reports".
> Improve admin message boxes

- engine/Default/chat_rules.php
- lib/Default/smr.inc
- templates/Default/engine/Default/chat_rules.php
- templates/Default/engine/Default/includes/LeftPanel.inc
- templates/Freon22/engine/Default/includes/LeftPanel.inc
* Show "Join Chat" and "Hall of Fame" even if not logged into a game
* Synchronize Freonn22 and Default templates
* Reorganize the link groups for a more logical ordering
* Link to rules on wiki instead of webboard
Out of game (Default)
In game (Default)
Out of game (Freon22)
In game (Freon22)
Join Chat
> Improve Left Panel

- admin/Default/manage_draft_leaders.php
- admin/Default/manage_draft_leaders_processing.php
- db/patches/V1_6_64_03__add_draft_leader_home_sector.sql
- engine/Draft/alliance_pick.php
- engine/Draft/alliance_pick_processing.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Draft/SmrPlayer.class.php
- templates/Default/admin/Default/manage_draft_leaders.php
* Draft leaders may be associated with "home sectors" when assigned, which is where players will be moved to (if in Sector 1 to start), and where they will return when podded.
* Players are eligible to be picked if they are in Sector 1, so long as they have not previously been drafted.
Some minor refactoring of `SmrPlayer` was needed to achieve this behavior.
> Changes for Draft Rounds

- engine/Default/bounty_place.php
- engine/Default/bounty_place_confirm.php
- lib/Default/AbstractMenu.class.php
- lib/Semi Wars/Menu.class.php
- templates/Default/engine/Default/skeleton.php
- templates/Freon22/engine/Default/skeleton.php
Remove the `create_menu` function in favor of setting the `MenuItems`
template variable, which will use the menu.inc template to display
the menu bar.
This transition had been partially complete for a very long time!
Misc: rename page "Place a Bounty" to "Place Bounty".
> Fully transition to using menu bar template

- engine/Default/message_box.php
- engine/Default/message_box_delete_processing.php
- engine/Default/message_delete_processing.php
- engine/Default/message_notify_confirm.php
- engine/Default/message_notify_processing.php
- engine/Default/message_view.php
- htdocs/js/listjs_include.js
- lib/Default/AbstractMenu.class.php
- lib/Default/Globals.class.php
- lib/Default/message.functions.inc
- lib/Default/smr.inc
- templates/Default/engine/Default/message_box.php
- templates/Default/engine/Default/message_view.php
Scout message UI/UX changes:
* The sender will no longer be displayed as a separate (redundant) field so
that the message can fit on a single line.
Message box UI/UX changes:
* The "Political Messages" box now always shows up in box view.
Conditionally hiding it seemed unnecessary.
* Remove redundant link to "Manage Blacklist" in box view. We keep the
link in the navigation bar.
* Clicking "Empty Read Messages" for Scout messages used to delete all
Scout messages (even unread ones). Now it behaves like all other box
types, and only deletes read messages.
* Deleting messages now stays in the selected folder instead of going
back to the box view, unless deleting "All Messages" (since it does
not make sense to display an empty list of messages).
* Reporting a …
> Tweaks to message boxes

- engine/Default/validate_processing.php
- htdocs/login_create_processing.php
- lib/Default/AbstractSmrAccount.class.php
- templates/Default/engine/Default/validate.php
validate.php: add option to resend the code
There are a variety of reasons why someone may need the validation
code resent. There was no obvious option to do this previously.
(The only method was to change your e-mail to the same address.)
> Add option to resend validation code

- engine/Default/bar_buy_drink_processing.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/missions.inc
The mission 'Steps' array has a variety of placeholders for data that
needs to be determined dynamically (sector ID, drink name, etc.).
Some of the replacements were being done in SmrPlayer::rebuildMission,
and others in `checkMissionRequirements`. This split was unnecessarily
complicated, so now it is done entirely in `rebuildMission`.
Two additional simplifications:
1. Instead of replacing placeholders manually in each element of the
mission step array, walk recursively over all (string-like) array
leaves. (Note that `str_replace` always outputs a string, which
is why we skip any non-string-like leaves.)
2. Remove aliases in `checkMissionRequirements`. If we want to check
a requirement, we now need to pass in values that have the same
keys. This fixes a bug with {Enter,Leave}Sector …
> missions.inc: simplify requirement checking

- engine/Default/planet_construction_processing.php
- htdocs/config.php
- templates/Default/engine/Default/planet_construction.php
Since planet construction awards experience, it is sensible to incur
a turn cost. At one turn per build, this change is mostly symbolic,
but at least it prevents infinite exp gain per turn. (It also adds
some much needed cost to draining the stockpile after a planet bust.)
> planet_construction.php: builds now cost 1 turn

- engine/Default/council_vote.php
- engine/Default/trader_relations.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/DummyPlayer.class.php
- templates/Default/engine/Default/trader_status.php
The "personal" relations (as displayed to the player) was often
referred to in the code as "pure" relations. We change the code
(function and variable names) to use "personal" instead.
Also change a few instances of "global" relations in code variable
names to "race" relations (since "global" may be confused with the
"total" relations). In the future this may be renamed consistently
to "political" relations, but for now we'll stick with "race" since
it results in fewer code changes.
> SmrPlayer: make relations naming more consistent

- docker-compose.yml
- traefik/file-provider.toml
- traefik/traefik.toml
There is a major design change between v1.7 and v2+: "backends and
frontends are replaced with routers and middlewares". As a result,
all of our traefik labels need to be updated; in particular, the host
rule and http path manipulation are no longer combined and need to be
specified separately with the `rule` and `middleware` labels.
Many of our services (traefik, api-docs, portainer, and pma) require
a trailing slash at the root entrypoint to work correctly. To do this
in traefik v2, we define the `add-slash` middleware. We also need to
chain this with the `strip-pathprefix` middleware (which assumes the
role that `PathPrefixStrip` had in v1.7).
Some http paths needed to change:
* `/traefik` is now accessed at `/dashboard` due to a limitation with
customizing the dashboard absolute URI …
> Update to traefik v2

- engine/Default/planet_defense_weapon_processing.php
- templates/Default/engine/Default/planet_defense.php
Mounted weapons can now only be destroyed when all the mount slots
are filled (i.e. if you destroy one, you must replace it before you
can destroy another one).
The original intention was only to allow a way to replace or upgrade
weapons, and the previous implementation was the best design I could
think of at the time. However, it allowed for mounted weapons to be
entirely depleted at no cost, which was not fair (or intended).
Some unsavory tactics are still available (e.g. you can replace the
most powerful weapons with weak weapons), but the impact is no longer
devastating and comes at a small cost.
> Limit destroying planetary mounted weapons

- engine/Default/smr_file_create.php
- htdocs/config.php
- lib/Default/AbstractSmrCombatWeapon.class.php
- lib/Default/SmrCombatDrones.class.php
- lib/Default/SmrMines.class.php
- lib/Default/SmrScoutDrones.class.php
- lib/Default/SmrWeapon.class.php
These weapon features are no longer in use (I believe they were an
SMR 1.5 experiment), so remove them to avoid confusion and clutter.
We could retain them in case we want to re-implement these features
in the future, but the infrastructure for them is so minimal that it
would be just as much work with and without the existing code.
Update the SMR file version to 1.07 due to a corresponding change in
the [Weapons] section format.
> Remove unused EMP Damage and Raid weapon attributes

- templates/Default/engine/Default/trader_examine.php
add a unique message indicating a ship being examined has cloaked.  in contrast, the current behavior is the catch all "You have no targets!" message which may be confusing.
> Cloak on examine

- admin/Default/location_edit.php
- db/patches/V1_6_65_01__weapon_bonuses.sql
- db/patches/V1_6_65_02__location_sells_special.sql
- engine/Default/bar_talk_bartender.php
- engine/Default/bar_talk_bartender_processing.php
- engine/Default/beta_func_processing.php
- engine/Default/edit_dummys.php
- engine/Default/planet_defense_weapon_processing.php
- engine/Default/shop_weapon.php
- engine/Default/shop_weapon_processing.php
- engine/Default/smr_file_create.php
- htdocs/config.php
- lib/Default/AbstractSmrLocation.class.php
- lib/Default/AbstractSmrShip.class.php
- lib/Default/Plotter.class.php
- lib/Default/SmrEnhancedWeaponEvent.class.php
- lib/Default/SmrPlanet.class.php
- lib/Default/SmrSector.class.php
- lib/Default/SmrShip.class.php
- lib/Default/SmrWeapon.class.php
- lib/Default/SmrWeaponType.class.php
- templates/Default/engine/Default/bar_talk_bartender.php
- templates/Default/engine/Default/course_plot.php
- templates/Default/engine/Default/shop_weapon.php
Weapons can now have one or both of two possible enhancements:
1. Increased damage (multiplicative +5% bonus)
2. Increased accuracy (additive +3% bonus)
The magnitude of these bonuses will likely need to be tweaked as we
see how they play out in the game. The intention is for them to be
small enough that they don't become mandatory in battles, but big
enough so that people will want to invest some resources to acquire
them.
If either of these enhancements are present, a weapon will be shown
in green with a "+" for each enhancement it has.
One enhanced weapon will now be sold from a single weapon shop every
6 hours (a number likely to be tweaked).
Players can get a hint about where the sale is taking place by giving
a bartender a sufficiently big tip. If the sale is in a different
galaxy, …
> Enhanced Weapons

- lib/Default/smr.inc
- templates/Default/engine/Default/alliance_mod.php
Before:
3 days, 2 hours, 20 minutes and 13 seconds
After:
3 days, 2 hours and 21 minutes
In general, nothing in the game requires display resolution on the
order of seconds (except perhaps early planet builds, but it's nice
to have a little bit of fuzziness there).
This has two key benefits.
1. Reduces the frequency of ajax updates, which will help decrease
bandwidth costs and reduce distracting page changes (for example,
when table column widths would change as the seconds tick).
2. Shortens the time string so that the value fits better in tables.
> Omit seconds from format_time

- lib/Default/SmrEnhancedWeaponEvent.class.php
- lib/Default/SmrWeaponType.class.php
- templates/Default/engine/Default/course_plot.php
This function returns all weapon types that can be purchased in the
given game. It has two main purposes:
1. Fix a bug with enhanced weapons where `createEvent` could randomly
choose a weapon type that is not purchasable at a weapon shop
(e.g. Planet Turret, Hell Blaster, etc.).
2. Improve "Plot To Nearest" by only listing weapons that are sold by
weapon shops that exist in the current game. This aims to prevent
needlessly getting the "Unable to find what you are looking for"
error message for inaccessible weapons.
> Add SmrWeaponType::getAllSoldWeaponTypes

- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/ChessPiece.class.php
A `switch` construct that uses `return` in a case does not need to
also `break` (since it will never be executed). As the `break` is
unused code, it can be safely removed.
This was identified by Scrutinizer.
> Remove unused break statements

- admin/Default/1.6/check_map.php
- htdocs/weapon_list.php
- lib/Default/AbstractSmrCombatWeapon.class.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/AbstractSmrPort.class.php
- lib/Default/SmrWeapon.class.php
- lib/Default/SmrWeaponType.class.php
- lib/Default/Traits/RaceID.class.php
- templates/Default/admin/Default/npc_manage.php
This PHP trait is used to implement the interface for any class that
needs to have a `$raceID` property. It provides the `getRaceID` and
`getRaceName` methods.
Additional notes:
1. This fixes a bug in smr_file_create.php, where `getRaceName` was
being called on an `SmrWeaponType`, which did not implement this
method. By inheriting the RaceID trait, it now has access to the
`getRaceName` method.
2. Moved the RaceID trait from AbstractSmrCombatWeapon to SmrWeapon,
since the abstract class doesn't need to know about race (the other
classes extending AbstractSmrCombatWeapon don't have a notion of
race, e.g. SmrScoutDrone, SmrCombatDrone, etc.).
> Add Traits/RaceID

- htdocs/js/filter_list.js
- htdocs/weapon_list.php
- templates/Default/weapon_list.php
The Weapon List page now displays a "Locations" column that lists
all the shops where each weapon is sold.
This was requested as a result of the Enhanced Weapons feature,
since it will be very helpful to know what weapons are sold at
each shop.
Note that we sacrifice a bit of visual conformity (equal height
rows) to support this feature.
> weapon_list.php: add locations where weapons are sold

- engine/Default/chess_play.php
- lib/Default/ChessGame.class.php
- templates/Default/engine/Default/chess_play.php
The board has never displayed correctly from black's perspective,
because while the rows were correctly reversed, the files were
not (so the board was mirrored, not rotated).
Also display the coordinates on only the bottom and left, rather
than all sides (as in regulation boards).
> Fix chess board from black's perspective

- admin/Default/account_edit_processing.php
- admin/Default/manage_draft_leaders_processing.php
- admin/Default/manage_post_editors_processing.php
- engine/Default/alliance_leadership_processing.php
- engine/Default/alliance_message.php
- engine/Default/alliance_message_view.php
- engine/Default/alliance_mod.php
- engine/Default/alliance_share_maps_processing.php
- engine/Default/bar_buy_drink_processing.php
- engine/Default/bar_galmap_buy.php
- engine/Default/bar_lotto_buy_processing.php
- engine/Default/bar_lotto_claim.php
- engine/Default/bar_main.php
- engine/Default/beta_func_processing.php
- engine/Default/current_sector.php
- engine/Default/message_blacklist_add.php
- engine/Default/message_view.php
- engine/Default/trader_savings.php
- engine/Default/trader_status.php
- lib/Default/smr.inc
- tools/chat_helpers/channel_msg_op_info.php
This visually shortens many queries that have both an `account_id`
and `game_id` in the `WHERE` clause, and also makes the query more
or less agnostic to what columns make an SmrPlayer unique.
> Use SmrPlayer::getSQL when possible

- config/SmrMySqlSecrets.sample.inc
- config/config.specific.sample.php
- engine/Default/game_play.php
- engine/Default/history_alliance_detail.php
- engine/Default/history_games.php
- engine/Default/history_games_detail.php
- engine/Default/history_games_hof.php
- engine/Default/history_games_news.php
- lib/Default/AbstractSmrAccount.class.php
- lib/Default/Globals.class.php
- lib/Default/MySqlDatabase.class.php
- lib/Default/Smr12HistoryMySqlDatabase.class.php
- lib/Default/SmrClassicHistoryMySqlDatabase.class.php
Add the methods `switchDatabases` and `switchDatabaseToLive` to switch
between history and live databases. Updated the config.specific.sample
to reflect that the keys of the global history databases array is the
database name, and not the old abstract implementation class name.
This was refactored out of #915 and finalized separately here.
> Improve design for switching between databases

- db/patches/V1_6_40__base_layout.sql
- db/patches/V1_6_42_03__rework_saved_combat_logs.sql
- db/patches/V1_6_47__destination_buttons.sql
- db/patches/V1_6_51__improve_alliance_op_responses.sql
- db/patches/V1_6_54_01__shiplist_update.sql
- db/patches/V1_6_56_01__adding_planet_type_support.sql
- db/patches/V1_6_61_05__draft_history.sql
- db/patches/V1_6_61_08__galactic_post_papers.sql
- db/patches/V1_6_61_09__account_shares_info.sql
- db/patches/V1_6_62_02__port_refresh_time.sql
- db/patches/V1_6_62_04__add_sector_warp.sql
- db/patches/V1_6_62_05__alliance_flagship.sql
- db/patches/V1_6_62_09__alliance_invites.sql
- db/patches/V1_6_63_01__player_assists.sql
- db/patches/V1_6_63_17__game_dates.sql
- db/patches/V1_6_63_20__chess_game_id.sql
- db/patches/V1_6_63_22__track_alliance_invite.sql
- db/patches/V1_6_64_03__add_draft_leader_home_sector.sql
Remove all integer display widths from the flyway migration scripts.
This fixes the following warning:
> WARNING: DB: Integer display width is deprecated and will be removed
> in a future release. (SQL State: HY000 - Error Code: 1681)
Note that the integer display width has no impact on the allowed range
of integer values, so there is no practical impact on the database
with this change.
Existing databases will need to run `flyway repair` to update the
flyway schema history.
> Fix database migration warning

- docker-compose.yml
- phpunit.xml
We will want to test the entirety of `lib`, so don't restrict the
code coverage reporting to just `lib/Default`.
> phpunit.xml: track code coverage in all of lib

- lib/Default/AbstractSmrShip.class.php
- lib/Default/SmrShip.class.php
* In `getPowerUsed` no need to check the number of weapons since
we're looping over the weapons array.
* In `addWeapon`, use the `checkPowerAvailable` function instead
of duplicating that function's logic.
We no longer need `hasRemainingPower` (unused), and we need to move
the `checkPowerAvailable` function to the abstract class so that it
can be used there.
> SmrShip: simplify power functions

- engine/Default/sector_jump_processing.php
- engine/Default/sector_mines.inc
- engine/Default/sector_move_processing.php
The jump/move sector movement files duplicated the logic for bumping
into mines. Move this common logic into its own file.
One change with this is that jumping into a sector with mines while
you have newbie turns now costs additional turns (just like moving).
I'm guessing this was just a desynchronization in the logic.
> Deduplicate mine bump processing logic

- db/patches/V1_6_65_05__revert_lvl5_weapons.sql
- db/patches/V1_6_65_06__update_photon_torpedos.sql
- engine/Default/bar_talk_bartender_processing.php
- engine/Default/planet_attack_processing.php
- engine/Default/port_attack_processing.php
- engine/Default/sector_mines.inc
- engine/Default/shop_weapon_processing.php
- htdocs/js/filter_list.js
- htdocs/weapon_list.php
- lib/Default/AbstractSmrShip.class.php
- lib/Default/SmrEnhancedWeaponEvent.class.php
- lib/Default/SmrPlanetType.class.php
- lib/Default/SmrWeapon.class.php
- templates/Default/weapon_list.php
* Planets/ports don't take structure damage until shields are breached.
* Enhanced weapons can now have +4% accuracy (previously +3%) and +15 damage (previously +5%).
* Power level 5 weapons are now unique (i.e. you can only have one of each type on a ship).
* HHG/Nuke accuracy is reverted to 35% (previously 30%).
* Protoplanets have been given 10 additional structures (+10 hangars, +5 generators, -5 bunkers).
* Slightly reduce strength of Photon Torpedo (PT => -1% accuracy, HPT => +1% accuracy, -5 damage).
* Scout ships no longer hit mines, but take additional turns to traverse minefields.
> Balance changes for Game 137

- admin/Default/1.6/upload_smr_file_processing.php
- htdocs/config.inc
With increased type-strictness, uploading a .smr file to the Uni Gen
was throwing due to `parse_ini_string` returning values as strings,
even when they represent integers. By converting (and validating) the
values to int type, we can safely pass them along to our library.
> Uni Gen: Convert uploaded .smr file values to ints

- admin/Default/1.6/check_map.php
- admin/Default/1.6/galaxies_edit.php
- admin/Default/1.6/universe_create_sector_details.php
- admin/Default/1.6/universe_create_warps.php
- engine/Default/bar_talk_bartender_processing.php
- engine/Default/current_sector.php
- engine/Default/map_local.php
- engine/Default/sector_scan.php
- htdocs/map_warps.php
- lib/Default/SmrGalaxy.class.php
- lib/Default/SmrSector.class.php
- templates/Default/admin/Default/1.6/universe_create_locations.php
- templates/Default/admin/Default/1.6/universe_create_planets.php
- templates/Default/admin/Default/1.6/universe_create_ports.php
- templates/Default/admin/Default/1.6/universe_create_sectors.php
- templates/Default/admin/Default/1.6/universe_create_warps.php
- templates/Default/engine/Default/GalaxyMap.inc
- templates/Default/engine/Default/alliance_forces.php
- templates/Default/engine/Default/bar_galmap_buy.php
- templates/Default/engine/Default/course_plot.php
- templates/Default/engine/Default/forces_list.php
- templates/Default/engine/Default/includes/PlanetList.inc
- templates/Default/engine/Default/includes/PlanetListFinancial.inc
- templates/Default/engine/Default/includes/SectorMap.inc
This continues the effort to store raw data in the database, leaving
it intact to be processed in whatever ways are necessary (since an
escaped string cannot be "unescaped").
We add `SmrGalaxy::getDisplayName` and replace most calls to `getName`
with this new method. Also remove `SmrSector::getGalaxyName` as it is
a wrapper that becomes less useful with this design.
I confirmed that no galaxy names in the live database have the `&`
character, so no database changes should be needed.
> SmrGalaxy: don't store escaped name in database

- db/patches/V1_6_65_07__add_scouts_to_BYDF.sql
Currently scouts are only sold at a Combat Accessories during normal games.  This makes scouts unnecessarily rare as the CA locations are tightly controlled in order to keep mines away from fed beacons.  Furthermore, placing a CA in a place accessible to racial galaxies but not in a place to be mined in is a time consuming pain in the ass.
We could bypass that SNAFU by simply adding scout drones to the drone farm inventory.  Which this PR does!  (assuming no errors were committed!)
> add scouts to backyard drone farm

- lib/Default/Plotter.class.php
- lib/Default/SmrGalaxy.class.php
Adds type-hints for function interfaces and typed class properties.
Minor internal changes:
* startSector now defaults to uninitialized, and when we call
getStartSector, it will do an `isset` check instead of checking
if it is false. This allows us to specify it as a single type (int).
* The function arguments for getMapSectors now default to null instead
of false. Then we will do an `is_null` check instead of checking
if they are false. This allows us to use an int type-hint.
> SmrGalaxy: add types

- db/patches/V1_6_65_09__change_yesno_enum.sql
- engine/Default/preferences_processing.php
- lib/Default/AbstractSmrAccount.class.php
All other boolean columns in the database use the TRUE/FALSE enum, so
we switch to that for `account.images` for consistency.
Note that to do this transition, we needed to add TRUE/FALSE, map the
old values to the new values, and then remove Yes/No.
> Rename account.images Yes/No enum to TRUE/FALSE

- admin/Default/game_status_processing.php
- admin/Default/log_console_detail.php
- engine/Default/hall_of_fame_new.php
- engine/Default/rankings_alliance_profit.php
- engine/Default/rankings_player_profit.php
- lib/Default/AbstractSmrAccount.class.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/ChessGame.class.php
- lib/Default/MySqlDatabase.class.php
- lib/Default/SmrAlliance.class.php
- lib/Default/hof.functions.inc
- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/Container/DiContainerTest.php
- test/SmrTest/MySqlPropertiesTest.php
- test/SmrTest/lib/DefaultGame/MySqlDatabaseIntegrationTest.php
- test/SmrTest/lib/DefaultGame/MySqlDatabaseTest.php
- test/strict_types.sh
* Simplify many of the get/escape methods (adding type-hints, removing arguments, using more straightforward logic).
* Remove the microtime hack for incorrectly stored microtimes.
* Fix nullable for object methods.
* Add many unit tests for the escape methods (the get methods are difficult to test due to a lack of DI with the query results).
See individual commit messages for more details.
> Clean up get/escape methods in MySqlDatabase

- db/patches/V1_6_65_10__change_message_notifications.sql
- lib/Default/AbstractSmrAccount.class.php
- test/SmrTest/lib/DefaultGame/AbstractSmrAccountIntegrationTest.php
Adds type-hints for function interfaces and typed class properties.
Minor internal changes:
* Setters now use `===` to check against current value instead of `==`
now that type equality is ensured.
* Many functions using `false` for a default argument value now use
`null` instead. This is necessary to use typed arguments.
> SmrAccount: add types

- .travis.yml
- docker-compose.yml
- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/PhpFileInspectionTest.php
- test/phplint.sh
- test/strict_types.sh
- tools/irc/irc.php
- tools/rerunChessGames.php
- tools/reserializeCombatLogs.php
- tools/updatePortCache.php
This allows the phplint and strict_type tests to be easily run in the containerized PHP environment.
> Perform file inspection tests in phpunit

- src/bootstrap.php
- src/tools/discord/GameLink.class.php
- src/tools/discord/commands/8ball.php
- src/tools/discord/commands/forces.php
- src/tools/discord/commands/game.php
- src/tools/discord/commands/invite.php
- src/tools/discord/commands/money.php
- src/tools/discord/commands/op.php
- src/tools/discord/commands/seed.php
- src/tools/discord/commands/seedlist.php
- src/tools/discord/commands/turns.php
- src/tools/discord/mysql_cleanup.php
DiscordPHP uses reactphp/promise for async events (such as sending
messages). If no rejection handler is supplied, then exceptions that
are thrown by the event get swalled (i.e. silently ignored).
Since our primary goal is to ensure all errors are reported, we call
`->done(null, 'logException')` on all returned promises. This means
that it will do nothing on success and call `logException` on failure.
Note that if `logException` throws an exception itself, it will cause
a fatal PHP error.
We also use `logException` for the normal handling of exceptions that
are thrown during the command responses instead of just printing them
(e.g. for additional logging machinery).
> Fix swallowing exceptions from DiscordPHP

- src/lib/Default/Request.class.php
- test/SmrTest/lib/DefaultGame/RequestTest.php
On pages with form submission, we typically save the form data in the
SmrSession $var. If the player then refreshes this page and resubmits
the form data (which is the default for most browsers), then we would
raise an exception due to the data being present both in $var and in
$_REQUEST. We want to allow this behavior, while still catching any
coding errors that result from setting session data incorrectly.
To do this, we now allow duplicate indices in $var and $_REQUEST if
and only if the values are the same in both. This could still hide a
coding error (if the values were accidentally the same), but at least
in this case it has no impact on the displayed page (unlike if the
values are different).
Also added a unit test for the Request class, and some minor refactoring.
> Prevent unnecessary page refresh errors

- src/lib/Default/AbstractSmrPlayer.class.php
- src/templates/Default/admin/Default/1.6/GameDetails.inc.php
Previously, players would get 100k credits or 1/4 their ship value,
whichever was higher.
Now, players will get the starting credits + 1/4 their ship value.
This change allows us to modify the minimum credits supplied on death
for a given game (whereas previously it was a hard-coded constant).
However, it would be even better to have a separate knob to change
the on-death credits.
The two components are added instead of taking the larger amount only
for simplicity. It also makes death slightly less punishing (in a
monetary sense) for players in ships less than ~1M credits, which is
probably a good thing.
> Change credits given to players on death

- Dockerfile
- config/env.sample
- docker-compose.yml
Specify `XDEBUG_MODE=profile` in the `.env` file to enable profiling
output by Xdebug. This will work with both the `smr` and `smr-dev`
services (but not `smr-integration-test`, because the profiling does
not work properly with long-running processes). If not specified,
`XDEBUG_MODE` will use the Xdebug default value 'develop' (for more
information, see https://xdebug.org/docs/all_settings#mode).
Profiling data is output to `./vol_xdebug`. These files can get quite
large, so you may want to clean them up from time to time.
The `webgrind` service can be used to quickly visualize the profiler
output, and is served at http://localhost/webgrind.
> Add infrastructure for Xdebug profiling

- Dockerfile
* Use the `--quiet=2` option for apt-get commands (note that this
implies `-y` for install).
* Add the `--quiet` option to composer, and use `update` instead of
`install` as per the instructions in the warning that we don't use
a composer.lock file.
* Redirect stdout of `docker-php-ext-install` commands to /dev/null,
as recommended by the docker-php maintainer (see, e.g.,
https://github.com/docker-library/php/issues/319).
* Redirect stdout of xdebug installation to /dev/null, because there
is no recommended way to make the command quieter. While some of
its stdout is useful (e.g. notification when a new xdebug version
is available), there is simply too much compiler output.
> Dockerfile: reduce verbosity

- .github/workflows/run-tests.yml
GitHub Actions environments support buildkit, which is a new build API
that is supposed to offer a lot of benefits over the legacy build
(see https://docs.docker.com/develop/develop-images/build_enhancements/).
We use the "plain" progress output so that the CI logs have the full
output (since the default buildkit output is compactified).
> run-tests.yml: use buildkit for docker builds

- Dockerfile
- src/htdocs/map_warps.php
- src/templates/Default/engine/Default/course_plot.php
- src/templates/Default/engine/Default/includes/EndingJavascript.inc.php
- src/templates/Default/engine/Default/includes/Head.inc.php
- src/templates/Default/engine/Default/preferences.php
- src/templates/Default/engine/Default/weapon_reorder.php
- src/templates/Default/login/login.php
- src/templates/Default/login/skeleton.php
- src/templates/Default/ship_list.php
- src/templates/Default/weapon_list.php
The behavior of this package has changed since v1.4.1, such that the
replacements are made in files with a strict adherence to relative
paths from the `baseDir` option. Since many of our PHP files aren't
located where they are served from (e.g. templates, includes, etc.),
grunt-cache-bust doesn't bust these files anymore.
The easiest fix is reference all JS/CSS with absolute URL paths (e.g.
`css/Default.css` -> `/css/Default.css`). While this is not an ideal
solution, due to its degradation of our support for serving the game
from a subdirectory (e.g. `http://localhost/smr` instead of just
`http://localhost`), it solves the problem for our current dev and
production configurations.
See https://github.com/benhoIIand/grunt-cache-bust/pull/211 for the
PR that introduced this breaking change. …
> Upgrade to grunt-cache-bust v1.7.0

- Dockerfile
- composer.json
- src/lib/Default/AbstractSmrAccount.class.php
- src/lib/Default/SmrGalaxy.class.php
- test/SmrTest/lib/DefaultGame/MySqlDatabaseIntegrationTest.php
* Add union types to interfaces. These were omitted when adding type
hints to some classes prior to switching to PHP 8.
* The "Array to string conversion" notice has been promoted to a
warning.
> Upgrade to PHP 8

- src/lib/Default/AbstractSmrCombatWeapon.class.php
- src/lib/Default/DummyShip.class.php
- src/templates/Default/engine/Default/includes/ForceTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/ForcesCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlanetCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PortCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PortTraderTeamCombatResults.inc.php
@hemberger requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/smrealms/smr/
> Scrutinizer Auto-Fixes

- src/config.php
- src/engine/Default/chess_move_processing.php
- src/engine/Default/chess_resign_processing.php
- src/engine/Default/combat_log_list.php
- src/engine/Default/course_plot_nearest_processing.php
- src/engine/Default/current_sector.php
- src/engine/Default/port_payout_processing.php
- src/htdocs/weapon_list.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/ChessGame.class.php
- src/lib/Default/Plotter.class.php
- src/lib/Default/SmrSector.class.php
- src/lib/Default/messages.inc.php
The PHP8 `match` function is much more robust (strict types, throw on
unmatched) and compact than the `switch` function. We use it anywhere
we can sensibly return a value.
> Replace switch with match where possible

- db/patches/V1_6_65_13__change_under_attack.sql
- src/engine/Default/beta_func_processing.php
- src/engine/Default/cargo_dump_processing.php
- src/engine/Default/forces_attack_processing.php
- src/engine/Default/forces_drop_processing.php
- src/engine/Default/planet_attack_processing.php
- src/engine/Default/planet_defense_processing.php
- src/engine/Default/port_attack_processing.php
- src/engine/Default/shop_hardware_processing.php
- src/engine/Default/shop_ship_processing.php
- src/engine/Default/trader_attack_processing.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrShip.class.php
- src/lib/Default/smr.inc.php
- src/tools/npc/npc.php
We will no longer try to infer whether a ship is under attack by
keeping track of the "old hardware" values.
This was unnecessarily complicated, and the methods for setting the
"old hardware" were prone to misuse. They also caused inconsistency
in the display for the player (if two players are triggering on each
other, sometimes you will see the "under attack" warning, but other
times you won't).
Other problems include NPCs getting stuck in a state of thinking they
were under attack (which is kind of ironic...), and needing to call
the `removeUnderAttack` function in the many places where hardware is
being modified in a non-combat context.
The fix is to remove the "old hardware" paradigm entirely, and then
replace it with a simple `under_attack` column in the `player` db.
This is set …
> SmrShip: remove "old hardware" paradigm

- src/lib/Default/MySqlDatabase.class.php
- test/SmrTest/lib/DefaultGame/MySqlDatabaseIntegrationTest.php
In #924, the `$dbConn` property was changed so that it is unset when
`close()` is called instead of being set to `false`. Therefore, when
we call `close()` on an already closed MySqlDatabase instance, we need
to perform an `isset` check on `$dbConn` instead of a boolean check.
This fix allows us to make repeated calls to `close()` again, and we
add a test to ensure this functionality.
Note that this impacted the IRC bot, which will make repeated calls to
close without reconnecting to the database if it processes an event
that doesn't require the database.
> MySqlDatabase: fix repeated calls to close()

- src/tools/irc/irc.php
- src/tools/irc/server.php
As of PHP 8, it is a fatal error to pass a bool to `preg_replace`,
whereas in PHP 7.4, it returned an empty string.
This change broke irc.php, because we treated the result of `fgets`
as a string (by passing it to `preg_replace`) before we verified that
it was not `false`, which is the value it returns when there is no
message from the server (or in the case of an error).
To fix this, we simply rearrange the logic at the beginning of the
`readFromStream`. The checks independent of the server message are
performed first (1. server timeout check and 2. player timer check).
Next we poll for a message from the server, and at this point we can
properly return early if we get `false` (no message or error).
Setting the "last ping" time has been moved into the `server_ping`
function, which seems …
> irc.php: fix PHP 8 error

- .github/workflows/run-tests.yml
Running these commands in separate stages will make it easier to find
the output of interest, since GitHub only provides structured output
at the stage level (and not individual commands within each stage).
The build output is quite long, so it takes a while to find the test
output when they are run in the same stage.
> run-tests.yml: split up build and test stage

- db/patches/V1_6_66_14__ajax_returns_default_null.sql
- src/engine/Default/combat_log_viewer.php
- src/engine/Default/current_sector.php
- src/engine/Default/forces_attack.php
- src/engine/Default/forces_attack_processing.php
- src/engine/Default/planet_attack.php
- src/engine/Default/planet_attack_processing.php
- src/engine/Default/port_attack.php
- src/engine/Default/port_attack_processing.php
- src/engine/Default/trader_attack.php
- src/engine/Default/trader_attack_processing.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/DummyPlayer.class.php
- src/lib/Default/DummyShip.class.php
- src/lib/Default/SmrSession.class.php
- src/tools/npc/npc.php
- src/tools/reserializeCombatLogs.php
These methods are a wrapper around serialize and gzcompress for
database escaping and querying. Use them, where applicable, instead
of getting the raw strings and manually (un)serializing/compressing
them.
For the various attack pages, we can store the combat results in the
global `$var` in its raw form. Serializing them only to unserialize
them later just creates extra work.
This also includes two simplifications in SmrSession:
1. We always specify `active_session.session_var` on insertion, and
`self::$var` is always set to an array; therefore, we know that
the `session_var` can be safely extracted with `getObject`, rather
than getting the raw string and verifying that it is not empty.
2. Since we don't always specify `active_session.ajax_returns`, it
now has a default value of null. …
> Use MySqlDatabase::{get,escape}Object

- src/lib/Default/Page.class.php
- src/lib/Default/smr.inc.php
Add function `Page::process` that performs the processing of engine
pages. This helps to ensure a sanitized namespace that only has the
global variables in it that we expect to find. The goal is to remove
all of these global variables eventually (if for no other reason than
to improve static analysis of engine files).
Also remove special handling of error.php. We can use `require` for
every page instead of `require_once`.
> Move engine processing from do_voodoo to Page class

- src/htdocs/js/ajax.js
The first AJAX update was being made instantaneously after each page
load. This seemed unnecessary from a gameplay perspective, since not
much can change in that first instant. It was also a bit distracting
due to the content (TOD and runtime, e.g.) rapidly updating after the
page had just loaded.
Instead, we now wait the normal AJAX delay interval before performing
the first AJAX update.
> ajax.js: delay first ajax update

- src/htdocs/loader.php
- src/lib/Smr/Session.php
- test/SmrTest/lib/DefaultGame/SessionIntegrationTest.php
We were getting the SN in the Session constructor anyway, so it didn't
make sense to get it externally and pass it in via `findCurrentVar`.
There also doesn't seem to be any purpose to the `updateSN` function.
The `active_session.last_sn` field only matters on the next page load,
when we check `hasChangedSN`, and it is sufficient to update this when
the `update` method is called.
> Session: define SN property in constructor

- src/lib/Default/AbstractSmrCombatWeapon.class.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrCombatDrones.class.php
- src/lib/Default/SmrForce.class.php
- src/lib/Default/SmrMines.class.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrScoutDrones.class.php
Affects the Smr{CombatDrones,ScoutDrones,Mines} classes.
The argument is written as `$gameTypeID`, but we were always passing
a game ID instead. Also, it was completely unused.
The same change was made to SmrWeapon in 0b1af16a0c.
> Remove unused gameTypeID constructor arguments

- src/lib/Default/AbstractSmrCombatWeapon.class.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/SmrCombatDrones.class.php
- src/lib/Default/SmrMines.class.php
- src/lib/Default/SmrScoutDrones.class.php
- src/lib/Default/SmrWeapon.class.php
- src/lib/Default/Traits/CombatWeaponForce.class.php
- test/SmrTest/lib/DefaultGame/SmrCombatDronesTest.php
- test/SmrTest/lib/DefaultGame/SmrMinesTest.php
- test/SmrTest/lib/DefaultGame/SmrScoutDronesTest.php
The typed properties introduced in #1072 caused an issue with the deserialization of some classes when viewing old combat logs. See commit messages for details.
> Fix combat logs

- db/patches/V1_6_66_16__drop_ship_class.sql
- db/patches/V1_6_66_17__drop_user_rankings.sql
- src/engine/Default/sector_mines.inc.php
- src/engine/Default/shop_ship.php
- src/engine/Default/smr_file_create.php
- src/htdocs/ship_list.php
- src/lib/Default/AbstractSmrAccount.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/Globals.class.php
- src/lib/HunterWars/SmrLocation.class.php
- src/lib/Smr/ShipClass.php
- src/lib/Smr/UserRanking.php
- src/templates/Default/engine/Default/rankings_view.php
- src/templates/Default/ship_list.php
- test/SmrTest/lib/DefaultGame/AbstractSmrShipTest.php
- test/SmrTest/lib/DefaultGame/DatabaseIntegrationTest.php
- test/SmrTest/lib/DefaultGame/ShipClassTest.php
- test/SmrTest/lib/DefaultGame/UserRankingTest.php
The database should be reserved for data that changes over time,
especially because database queries are the slowest way to retrieve
data (whereas loading a PHP class is significantly faster).
The following table -> class replacements are made:
* `user_rankings` -> `UserRanking`
* `ship_class` -> `ShipClass`
> Switch constant tables from database to PHP class

- db/patches/V1_6_66_22__drop_unused.sql
- src/admin/Default/game_delete_processing.php
* npc_long_term_goal
* npc_short_term_goal
* player_repaired
* plot_cache
Verified that these tables are empty in the live database.
> Drop unused tables

- src/engine/Default/alliance_create_processing.php
- src/engine/Default/game_join_processing.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/SmrAlliance.class.php
- test/SmrTest/lib/DefaultGame/SmrAllianceIntegrationTest.php
Use table locking on the `alliance` table to ensure that when we get
the `alliance_id` for a new alliance, it is unique.
Two things prevent us from using AUTO_INCREMENT for the `alliance_id`:
1. We have a range of IDs that are reserved for the NHA and similar.
2. When we switch to an InnoDB engine, AUTO_INCREMENT on a column that
is part of a multi-column primary key will no longer reset the
increment when the other primary key changes (as it does with the
current MyISAM engine). Therefore, we cannot rely on this behavior.
> SmrAlliance: make createAlliance threadsafe

- src/engine/Default/alliance_share_maps_processing.php
- src/engine/Default/message_view.php
- src/tools/npc/npc.php
Identified by errors collected after the engine update for Game 142.
> Miscellaneous fixes

- src/tools/irc/channel_msg.php
- src/tools/irc/channel_msg_op.php
- src/tools/irc/notice.php
* Return `$player` instead of returning it by reference. This change
is needed because the value is `null` when it is passed in, which
breaks the type requirement `AbstractSmrPlayer`. Fixes the error:
> Unncaught TypeError: check_for_registration(): Argument `#1`
> ($player) must be of type AbstractSmrPlayer, null given
* If the registration check fails, we return `false` instead of `true`
so that we can use the union return type `AbstractSmrPlayer|false`.
* Use a `callable` for the `$callback` argument instead of a string
representation that must be run with `eval`.
> irc: fix check_for_registration interface

- src/htdocs/css/shared.css
- src/lib/Default/ChessGame.class.php
- src/templates/Default/engine/Default/chess_play.php
We had a complicated scheme for highlighting the last move of a chess
game, where the JavaScript code would be transmitted to the browser
via ajax, and then a special "EVAL" hook would run that code.
A simpler scheme would be to put the highlighting code in the JS file,
and then only transmit the "lastMove" data via ajax.
However, the simplest scheme seems to be to just add the `lastMove`
HTML class attribute when processing the page server-side. Otherwise,
the browser needs to run the highlighting code on every ajax update,
even though most of the time the page won't be changing. This way we
don't even need to transmit the "lastMove" data to the browser at all.
Additional details:
* To pass the `lastMove` HTML class attribute via ajax, we had to move
it to a new child `<div>` of the …
> Highlight last chess move server-side

- src/engine/Default/port_attack.php
- src/engine/Default/port_payout_processing.php
- src/lib/Default/AbstractSmrPort.class.php
- src/templates/Default/engine/Default/port_attack.php
* Ports can no longer be looted after the defenses have reset.
* Only players who participated in the port raid can loot/claim the port.
> Fix port raid loopholes

- src/htdocs/vote_link_callback.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/SmrForce.class.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrShip.class.php
These methods had two major flaws:
1. They do not actually update existing instances of classes. So any
place where an instance was stored outside the cache could be out
of sync with the version in the cache.
2. They do more work than simply using `clearCache` since it forces
all existing instances to be reloaded immediately, rather than
letting them be reloaded on demand.
The only place any of these were used was in vote_link_callback.php,
and it was being used incorrectly there. Specifically, `$player` was a
reference to the _original_ instance, prior to getting a sector lock,
and we were not updating it after calling `resetCache`. Therefore, we
were potentially overwriting data if the database was updated between
the initial `getPlayer` call and acquiring the lock. (Note that this
was …
> Remove resetCache methods

- src/engine/Default/planet_attack_processing.php
- src/lib/Default/AbstractSmrCombatWeapon.class.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrCombatDrones.class.php
- src/lib/Default/SmrForce.class.php
- src/lib/Default/SmrMines.class.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrWeapon.class.php
- test/SmrTest/lib/DefaultGame/SmrPlanetIntegrationTest.php
* Rename combat damage methods for clarity (e.g. `doMinesDamage` -> `takeDamageFromMines`).
* Remove delayed planet defense updating, because it is unused.
> Minor combat interface cleanup

- Dockerfile
Xdebug 3.1 is the first version to support PHP 8.1.
> Dockerfile: update Xdebug from 3.0.4 to 3.1.1

- composer.json
This ensures that dev environments and production environments are
using the same dependency versions. It also ensures that dependabot
keeps us properly updated on any new release.
* abraham/twitteroauth: ^3.1 -> 3.2.0
* google/recaptcha: ^1.1 -> 1.2.4
> composer.json: use explicit dependency versions

- src/lib/Smr/Template.php
- test/SmrTest/lib/DefaultGame/TemplateTest.php
The middle panel was not ajax updating due to a Template bug that was
introduced in 2b4257472. Basically, we were using the `contextNode`
argument of `DOMXPath::query` to check for ajax-enabled content in the
middle panel, but even though the `contextNode` was the middle panel
element, we were using an XPath expression starting with "//", which:
> Selects nodes in the document from the current node that match the
> selection no matter where they are
As a result, the query was escaping the context node and finding ajax-
enabled elements _outside_ of the middle panel. The context node is
_only_ relevant for _relative_ XPath queries (i.e. it is not the same
as creating a new DOMDocument out of the context node).
The fix is simple: we convert the queries to be relative by prepending
a ".". …
> Fix middle panel ajax updates

- src/lib/Smr/Database.php
This ensures that an exception is raised if none of the types are
matched instead of implicitly returning null. Fixes the following
PHPStan warning:
> Method Smr\Database::escape() should return mixed but return
> statement is missing.
> Database: use match expression in escape function

- db/patches/V1_6_67_02__chess_piece_colour.sql
- src/engine/Default/chess.php
- src/engine/Default/chess_create_processing.php
- src/engine/Default/chess_move_processing.php
- src/engine/Default/chess_play.php
- src/engine/Default/chess_resign_processing.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/Chess/ChessPiece.php
- src/templates/Default/engine/Default/chess_play.php
- src/tools/npc/chess.php
- src/tools/rerunChessGames.php
* Move chess-related classes into the PSR-4 autoloader.
* Simplify some chess class methods.
* Remove unneeded properties from `ChessPiece` class.
> Chess refactor

- src/admin/Default/box_view.php
- src/admin/Default/notify_view.php
- src/htdocs/map_warps.php
- src/lib/Default/Globals.class.php
- src/lib/Default/SmrGame.class.php
- src/lib/Default/hof.inc.php
- test/SmrTest/lib/DefaultGame/SmrGameIntegrationTest.php
* Remove unused method `Globals::getGameType` (we use `$game->getGameType()` instead).
* Rename `Globals::isValidGame` to `SmrGame::gameExists`.
* Use `self` typehint in SmrGame.
* Add SmrGame unit test.
> Minor refactor of SmrGame

- docker-compose.yml
Many of our services were building their own image, but were able to
avoid doing any extra work thanks to the Docker layer cache. Basically,
this was the same image but with many different names.
In some sense this was nice because it decoupled the services. Building
for one service would not modify the container for other services.
This was a double-edged sword, however, because often we wanted to keep
the images in sync, but it was easy to forget the build step for some
of the services.
By specifying an `image` field in addition to `build`, we are telling
Docker to build the image with the name indicated by `image` (rather
than giving it an automatic name based on the directory/service name).
Now all the services that specify `image` will use the updated image,
regardless of which …
> docker-compose.yml: add smr-builder YAML anchor

- src/engine/Default/death_processing.php
- src/tools/npc/npc.php
The NPCs were continuing to trade in an Escape Pod if they were killed
in the middle of their session.
Now they will reship in the same way that they would at the start of
the session.
And some other small misc improvements.
> npc.php: reship the NPC immediately after death

- .github/codecov.yml
We have a lot of PRs that don't change coverage (i.e. dependabot PRs),
and the huge codecov PR comments just get in the way when there are no
coverage changes to report.
> Omit codecov PR comments when coverage unchanged

- composer.json
Previously, we were not pinning the version of php-code-coverage, which
made it hard to disentangle real coverage changes from changes in the
behavior of the code coverage library. Historically, this has not been
a problem, because php-code-coverage was very stable. However, between
versions 9.2.10 and 9.2.13, there were several changes/regressions that
caused coverage changes.
Pinning avoids any ambiguity, and ensures that coverage changes in a
PR come _only_ from the PR code changes (unless we're explicitly
updating the php-code-coverage pinned version).
> composer.json: pin the php-code-coverage dependency

- .scrutinizer.yml
This configuration used to be stored online at Scrutinizer-CI, but it
was difficult to track when something needed to change (such as PHP
version or directory structure). The configuration included here is
merged with the online configuration.
See https://scrutinizer-ci.com/docs/configuration/cascade.
> Add .scrutinizer.yml

- src/engine/Default/admin/unigen/universe_create_locations.php
- src/engine/Default/admin/unigen/universe_create_save_processing.php
- src/templates/Default/engine/Default/admin/unigen/universe_create_sector_details.php
* In the "Headquarters" section of page for adding Locations, only the
primary HQ locations are specified, and the linked locations will be
added automatically. Previously, if this page was used after the HQ
locations were already populated, the linked locations would be
scattered across the galaxy (in addition to new ones being added
alongside the HQ). Now, the only caveat is that any _intentionally_
unlinked locations will be clobbered if this page is used.
* You can now manually edit the location/placement of linked locations
in the "Edit Sector" page by using the new checkbox to toggle whether
or not linked locations should be added with the HQ.
> Uni Gen: fix linked location handling

- src/engine/Default/preferences_processing.php
- src/htdocs/login_create_processing.php
- src/htdocs/login_processing.php
- src/htdocs/login_social_create.php
- src/htdocs/resend_password_processing.php
- src/htdocs/reset_password_processing.php
- src/lib/Default/AbstractSmrAccount.class.php
- src/tools/discord/GameLink.class.php
- src/tools/irc/channel_msg.php
- test/SmrTest/lib/DefaultGame/AbstractSmrAccountIntegrationTest.php
If an account cannot be found, it now throws an exception instead of
returning null. This is important for ensuring that the `getAccount*`
functions all return a single type. It also makes it consistent with
the other fundamental object classes (SmrPlayer, SmrAlliance, etc.).
As a result of this change, all places that check for null returns
needed to be modified to do a try-catch instead.
> Refactor SmrAccount constructors

- src/engine/Default/bar_gambling_processing.php
- src/lib/Smr/Blackjack/Hand.php
- test/SmrTest/lib/DefaultGame/Blackjack/HandTest.php
This page has been one of the last holdouts of intermixed processing
and display logic. While it's not fully disentangled, it is much less
egregious now.
The two most impactful simplifications made here are:
1. The logic for displaying a hand of cards has been refactored into
a `display_hand` function.
2. There is a single condition for tracking if the game has ended.
Previously this was scattered all over, and resulted in a bunch of
code that turned out to be unreachable.
Additional changes:
* Converted the `check_for_win` function to use a match function
instead of a complex if-statement.
* Added the Hand::hasBusted method.
> bar_gambling_processing.php: major simplification

- src/engine/Default/alliance_invite_player_processing.php
- src/engine/Default/bar_lotto_buy_processing.php
- src/engine/Default/cargo_dump_processing.php
- src/engine/Default/current_players.php
- src/engine/Default/message_view.php
- src/engine/Default/sector_mines.inc.php
- src/engine/Default/shop_goods_processing.php
- src/lib/Default/smr.inc.php
- src/templates/Default/engine/Default/combat_log_list.php
- src/templates/Default/engine/Default/course_plot_result.php
- src/templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlottedCourse.inc.php
- src/templates/Default/engine/Default/includes/PortTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/message_view.php
- src/templates/Default/engine/Default/planet_list.inc.php
- src/templates/Default/engine/Default/sector_jump_calculate.php
- test/SmrTest/lib/DefaultGame/PluraliseTest.php
Include the amount in the returned value to simplify the way it is
used in a majority of cases.
The only times when we don't want to include the value, it is because
we are using some special HTML formatting of the amount. This is why
the function now has a `$includeAmount` boolean argument.
We remove the "is -> are" functionality, since places where this was
used could be reworded in a sensible way.
> Refactor pluralise function

- src/engine/Default/admin/ip_view_results.php
- src/engine/Default/admin/unigen/universe_create_locations.php
- src/engine/Default/album_edit_processing.php
- src/lib/Default/AbstractSmrAccount.php
- src/lib/Default/AbstractSmrPlayer.php
- src/lib/Default/AbstractSmrPort.php
- src/lib/Default/AbstractSmrShip.php
- src/lib/Default/Globals.php
- src/lib/Default/SmrAlliance.php
- src/lib/Default/SmrPlanet.php
- src/lib/Default/SmrPlanetType.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/Database.php
- src/lib/Smr/HallOfFame.php
- src/lib/Smr/SocialLogin/SocialLogin.php
- src/lib/Smr/Template.php
- src/lib/Smr/VoteSite.php
- src/templates/Default/engine/Default/includes/SectorPlayers.inc.php
- src/tools/chat_helpers/channel_msg_forces.php
- src/tools/chat_helpers/channel_msg_seed.php
- src/tools/chat_helpers/channel_msg_seedlist.php
- src/tools/npc/npc.php
PSR2R.ControlStructures.UnneededElse
In general, if/else clauses that create exit points (continue, break,
return, etc.) are unneeded because the code that follows will not be
reachable. The extra indentation caused by this code smell can also
be harmful to code readability (since deep nesting is hard to read).
When a condition clearly indicates a departure from the "normal"
execution path, then:
```php
if (condition) {
return foo
}
return bar
```
matches the asymmetry of the logic better than:
```php
if (condition) {
return foo
} else {
return bar
}
```
The former also has the benefit of reducing indentation levels, and
thus (usually) making the code easier to read.
At first, I was skeptical that this was a good code sniff, but after
reassessing each case carefully, I realized that it …
> Fix code smell UnneededElse

- src/engine/Default/admin/admin_message_send_processing.php
- src/engine/Default/admin/announcement_create_processing.php
- src/engine/Default/admin/box_reply_processing.php
- src/engine/Default/admin/newsletter_send_processing.php
- src/engine/Default/admin/notify_reply_processing.php
- src/engine/Default/admin/vote_create_processing.php
- src/engine/Default/admin/word_filter_add.php
- src/engine/Default/alliance_create_processing.php
- src/engine/Default/alliance_message_add_processing.php
- src/engine/Default/alliance_stat_processing.php
- src/engine/Default/bank_anon_create_processing.php
- src/engine/Default/council_send_message_processing.php
- src/engine/Default/course_destination_button_processing.php
- src/engine/Default/galactic_post_write_article_processing.php
- src/engine/Default/game_join_processing.php
- src/engine/Default/message_send_processing.php
- src/engine/Default/planet_ownership_processing.php
- src/engine/Default/preferences_processing.php
- src/htdocs/login.php
- src/htdocs/login_create_processing.php
- src/lib/Smr/Request.php
- test/SmrTest/lib/DefaultGame/RequestTest.php
In many cases where we use `Request::get`, we trim the returned value
manually. This is because leading and trailing whitespace from a form
input is almost always accidental and/or meaningless.
For example, I was copy-pasting the alliance name when creating NPCs,
and because we were _not_ trimming that form input, I ended up creating
a second alliance due to a trailing whitespace artifact from the copy.
Now we will _always_ trim form inputs in `Request::get`, and so we no
longer need to call `trim` explicitly on its returned value.
> Globally trim strings input by the user

- composer.json
- src/lib/Smr/Container/DiContainer.php
Fixes deprecation warning from one of its dependencies.
https://github.com/PHP-DI/PHP-DI/releases/tag/6.4.0
> composer.json: update PHP-DI from 6.3.5 to 6.4.0

- src/lib/Smr/Container/DiContainer.php
- src/lib/Smr/Epoch.php
- src/tools/npc/chess.php
- src/tools/npc/npc.php
- test/SmrTest/lib/DefaultGame/EpochTest.php
Setting NPC_SCRIPT as a PHP constant made it difficult to test classes
that depended on it. This is because PHPUnit has no mechanism to change
the value of a PHP constant, apart from `@runInSeparateProcess`, and
then setting the constant to a different value in that process.
Unfortunately, `@runInSeparateProcess` interacted poorly with PHP-DI
in a way that I don't completely understand. When running tests using
this decorator, the following error would be triggered:
```
PHPUnit\Framework\Exception: PHP Fatal error:  Uncaught Error: Using $this when not in object context in /smr/vendor/php-di/php-di/src/Compiler/Template.php:4
Stack trace:
#0 Standard input code(1154): require_once()
#1 {main}
thrown in /smr/vendor/php-di/php-di/src/Compiler/Template.php on line 4
Fatal error: Uncaught …
```
> Change NPC_SCRIPT from a const to a DI variable

- src/engine/Default/current_sector.php
- src/engine/Default/planet_examine.php
- src/engine/Default/planet_main.php
- src/engine/Default/port_attack_warning.php
- src/engine/Default/trader_attack_processing.php
- src/lib/Default/SmrSector.php
- src/lib/Smr/Template.php
- src/templates/Default/engine/Default/current_sector.php
- src/templates/Default/engine/Default/includes/SectorPlayers.inc.php
- src/templates/Default/engine/Default/planet_examine.php
- src/templates/Default/engine/Default/planet_main.php
- src/templates/Default/engine/Default/port_attack_warning.php
- src/templates/Default/engine/Default/trader_examine.php
- test/SmrTest/lib/DefaultGame/TemplateTest.php
* Add eligible attacker lists to the "Port Raid" and (hostile) "Examine Planet" pages. This will help triggers to make sure everyone is ready for the shot (e.g. who is in sector, if anyone still has newbie turns, etc.). It should also help to prevent people from accidentally clicking on the "Attack Planet" button when they intend to land, because the page will look significantly different (i.e. it will have a list of attackers).
* On the "Current Sector" page, ship sensors will now _always_ detect cloaked ships, even if there are other ships in sector. This improves parity between the information provided by the "Current Sector" and "Local Map" pages.
* Changes to the "Examine Ship" page:
* Player lists will no longer get randomly sorted on each auto-refresh.
* All players eligible to …
> Enhancements for player lists

- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/lib/DefaultGame/AbstractSmrAccountIntegrationTest.php
- test/SmrTest/lib/DefaultGame/AbstractSmrPlayerIntegrationTest.php
- test/SmrTest/lib/DefaultGame/CreateNHATest.php
- test/SmrTest/lib/DefaultGame/SectorLockTest.php
- test/SmrTest/lib/DefaultGame/SessionIntegrationTest.php
- test/SmrTest/lib/DefaultGame/SmrAllianceIntegrationTest.php
- test/SmrTest/lib/DefaultGame/SmrGameIntegrationTest.php
- test/SmrTest/lib/DefaultGame/SmrPlanetIntegrationTest.php
- test/SmrTest/lib/DefaultGame/SmrShipIntegrationTest.php
- test/SmrTest/lib/DefaultGame/VoteSiteIntegrationTest.php
The goal is to have the database return to its initial state after
every test, so that tests are independent of each other.
The way we were previously achieving this was by storing a list of
tables that start empty and truncating all those tables after every
test, since we (happen to) only modify tables that start empty.
This is the slowest method (apart from re-initializing the database
after every test) because we currently have ~120 empty tables, but
most test only modify a handful of them. This incurs a lot of overhead
cost, even with empty tables. With this method, the tests take ~23
seconds.
A faster way to do this is to count the number of rows of each table,
and then only truncate tables that change from zero to non-zero rows.
I suspect this is faster because counting rows is done …
> Speed up tests that modify the database

- src/config.php
- src/htdocs/album/album_comment_processing.php
- src/htdocs/error.php
- src/htdocs/login_create_processing.php
- src/htdocs/login_processing.php
- src/htdocs/login_social_processing.php
- src/htdocs/map_galaxy.php
- src/htdocs/map_warps.php
- src/htdocs/resend_password_processing.php
- src/htdocs/reset_password_processing.php
- src/lib/Default/Page.php
- src/lib/Default/SmrGalaxy.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Exceptions/GalaxyNotFound.php
- src/templates/Default/engine/Default/GalaxyMap.inc.php
- src/templates/Default/login/error.php
- test/SmrTest/lib/DefaultGame/PageIntegrationTest.php
- test/SmrTest/lib/DefaultGame/VoteSiteIntegrationTest.php
* Ability to use `create_error` everywhere, and proper handling of `UserError` outside the loader.
* More user-friendly errors on the Galaxy Map.
* New error page.
> Better non-loader error handling

- src/lib/Default/AbstractSmrPort.php
- test/SmrTest/lib/DefaultGame/AbstractSmrPortTest.php
The `port_has_goods` and `route_cache` tables will now only be updated when `SmrPort::update` is called.
> SmrPort: isolate database changes

- src/engine/Default/admin/unigen/check_map.php
- src/lib/Default/AbstractSmrPlayer.php
- src/lib/Default/Plotter.php
- src/lib/Smr/Routes/MultiplePortRoute.php
- src/lib/Smr/Routes/OneWayRoute.php
- src/lib/Smr/Routes/Route.php
- src/lib/Smr/Routes/RouteGenerator.php
- src/tools/npc/npc.php
- test/SmrTest/lib/DefaultGame/Routes/MultiplePortRouteTest.php
- test/SmrTest/lib/DefaultGame/Routes/OneWayRouteTest.php
- test/SmrTest/lib/DefaultGame/Routes/RouteGeneratorTest.php
* Add unit tests for all classes in the `Routes` namespace.
* Fix misuse of `Routes` in the NPC script that was restricting it to 2-port routes.
* Speed optimizations for the `RouteGenerator`.
* Make logic in `Routes` compatible with buy/sell from the perspective of the player. This fixes routes being ordered incorrectly (which is only a non-cosmetic issue for 3+ port routes).
Many other small fixes, documentation, and polish. See commit messages for details.
> Major improvements to RouteGenerator

- src/engine/Default/admin/unigen/check_map.php
- src/engine/Default/admin/unigen/galaxies_edit.php
- src/engine/Default/admin/unigen/galaxies_edit_processing.php
- src/engine/Default/admin/unigen/universe_create_galaxies.php
- src/engine/Default/admin/unigen/universe_create_locations.php
- src/engine/Default/admin/unigen/universe_create_save_processing.php
- src/engine/Default/smr_file_create.php
- src/htdocs/map_warps.php
- src/lib/Default/SmrGalaxy.php
- src/lib/Default/SmrGame.php
- src/templates/Default/engine/Default/bar_galmap_buy.php
- src/templates/Default/engine/Default/course_plot.php
- src/tools/npc/npc.php
Because the Plotter and RouteGenerator require a contiguous sector
range, we can only select the galaxies until the first Planet galaxy
is encountered. If no galaxies are selected with this method (i.e. if
the first galaxy is a Planet galaxy), then we will just use the NPC's
current galaxy only.
If this causes memory exhaustion, then we may need to rethink this
feature (or optimize the route generator).
* Add `SmrGame::getGalaxies`
* Add galaxy type constants to `SmrGalaxy`
> Allow NPCs to trade in any Racial/Neutral galaxy

- src/engine/Default/alliance_list.php
- src/engine/Default/alliance_treaties.php
- src/engine/Default/game_stats.php
- src/engine/Default/rankings_alliance_experience.php
- src/engine/Default/rankings_alliance_profit.php
- src/engine/Default/rankings_alliance_vs_alliance.php
- src/htdocs/js/listjs_include.js
- src/lib/Default/Rankings.php
- src/lib/Default/SmrAlliance.php
- src/templates/Default/engine/Default/alliance_list.php
- src/templates/Default/engine/Default/rankings_alliance_vs_alliance.php
- test/SmrTest/lib/DefaultGame/SmrAllianceIntegrationTest.php
This should make it easier for new players to find alliances that they
can join without needing a password.
We might want to consider putting the "Join" button right on this page,
but for now it will just say "Yes"/"No".
Also improved efficiency of constructing multiple SmrAlliance instances.
> Gameplay: add recruitment column to alliance list

- src/engine/Default/game_stats.php
- src/engine/Default/rankings_alliance_experience.php
- src/engine/Default/rankings_alliance_kills.php
- src/engine/Default/rankings_alliance_profit.php
- src/lib/Default/Rankings.php
- src/templates/Default/engine/Default/game_stats.php
All remaining raw SQL queries are moved from the rankings_*.php pages
to the Rankings class. The game_stats.php page is re-implemented with
the Rankings class methods.
* Fix SQL error in alliance experience rankings in game_stats.php. In
disbanded alliances (i.e. no players), we would be calling `SUM` on
`NULL` due to a missing `COALESCE`, which was present in the
(otherwise) identical query in rankings_alliance_experience.php
in d9fca79617661.
* Fix bug calculating alliance kill counts in game_stats.php. We must
get the count from the `alliance.alliance_kills` column instead of
from the individual player kill counts. This way, only the kills
awarded while the player was a member of the alliance will count
toward the alliance total.
* The game_stats.php rankings automatically inherit the …
> Extend Rankings to game_stats.php

- phpstan.neon.dist
- src/bootstrap.php
- src/lib/Smr/Container/DiContainer.php
- src/lib/Smr/Container/ResettableCompiledContainer.php
- src/lib/Smr/Container/ResettableContainer.php
- src/lib/Smr/Container/ResettableContainerTrait.php
- src/lib/Smr/Database.php
- src/lib/Smr/Discord/DatabaseCommand.php
- src/tools/discord/bot.php
- src/tools/irc/irc.php
- src/tools/irc/stream.php
- test/SmrTest/Container/DiContainerTest.php
- test/SmrTest/Container/ResettableContainerTraitTest.php
- test/SmrTest/lib/DefaultGame/DatabaseIntegrationTest.php
Add introspection (`initialized`) and resetability (`reset`) to the DI container interface. This allows for two major infrastructural improvements:
1. The database connection can now be properly reset after use in daemonized services (Discord/IRC clients) in a way that doesn't initialize the connection unnecessarily during a request where it's not used. It can be recreated again on demand without any special reconnection logic.
2. Logging no longer initializes resources that were not used up until the logging facility was invoked. This also prevents issues with throwing during logging (in case the resources themselves are the source of the error).
> Extend the DI container interface

- composer.json
- phpstan.neon.dist
Manually update phpstan because it induces some new warnings. Note that these warnings are due to a limitation of dynamicConstantNames and empty constant arrays.
Related to https://github.com/phpstan/phpstan/issues/7913.
Closes https://github.com/smrealms/smr/pull/1432.
> Update phpstan from 1.8.2 to 1.8.5

- .github/workflows/run-tests.yml
- README.md
- composer.json
- db/init_admin.sh
- docker-compose.yml
The docker compose plugin is a native docker subcommand rather than a separate program written in Python.
Use docker compose v2+ and the "Compose Specification" format of the configuration file instead of the legacy "Version 3" format. In this new format, the schema "version" element is deprecated.
* For services that specify both a `build` and `image` elements (i.e. all the services that use the `local/smr` image), we were getting an error during `docker compose pull` (because the image only exists locally). Specifying `pull_policy: build` resulted in rebuilding the image whenever the service was _run_, so we settled on never pulling the image (`pull_policy: never`).
* Even though the flyway service `command` worked properly with docker-compose 1.29, in v2.10.2 it was not being parsed …
> Switch to docker compose plugin

- .github/workflows/build-live.yml
- .github/workflows/run-tests.yml
See https://github.com/actions/runner-images/issues/5998.
> GH Actions: update image from Ubuntu 20.04 to 22.04

- src/lib/Default/AbstractSmrPort.php
- test/SmrTest/lib/DefaultGame/AbstractSmrPortTest.php
If a port lost a level on the same attack where it is destroyed, then
it would throw an error when trying to update the good amounts in the
database. We now update the internal state properly when removing goods.
> Fix port combat bug

- src/engine/Default/current_sector.php
- src/engine/Default/forces_mass_refresh.php
- src/lib/Default/AbstractSmrPlayer.php
- src/lib/Default/Plotter.php
The logic for displaying sector refresh/attack messages on the "Current Sector" page has been significantly simplified.
> Simplify sector messages

- docker-compose.yml
Set `XDEBUG_MODE=off` on the `smr-test` YAML anchor so that it is inherited by the test services that do not explicitly turn it on.
* PHPStan turns off xdebug if the `--xdebug` flag is not explicitly passed, so we were never using xdebug here. However, this silences the warning about xdebug being active but unused.
* PHP_CodeSniffer _was_ being slowed down by xdebug. The `phpcs` service now runs about 3x faster (~30s -> ~10s).
> docker-compose.yml: turn off xdebug by default for test services

- db/patches/V1_6_68_07__drop_chess_game_pieces.sql
- phpcs.xml
- src/bootstrap.php
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Chess/Board.php
- src/lib/Smr/Chess/Castling.php
- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/Chess/ChessPiece.php
- src/pages/Player/Chess/MatchPlay.php
- src/templates/Default/engine/Default/chess_play.php
- src/tools/npc/chess.php
- test/SmrTest/lib/Chess/BoardTest.php
- test/SmrTest/lib/DatabaseIntegrationTest.php
* The Board class encapsulates all the information that is necessary to fully represent any given board state (i.e. an FEN string). It helps to disentangle game metadata vs. board state from ChessGame, and allows us to pass a single object to methods instead of passing a board array (`$board`) and a bookkeeping array (`$hasMoved`).
* The Board class has a bunch of new methods that help to simplify the logical operations (like finding the King piece, or getting all the pieces of a particular colour).
* The array returned by Board::movePiece removes a bunch of fields we weren't using.
* Remove the `chess_game_pieces` table, because it is not sufficient information on its own to reproduce the board state, and so we just need to use `chess_game_moves` for complete info anyway.
* Add a …
> Refactor ChessGame into Board class

- src/pages/Admin/CombatSimulator.php
- src/templates/Default/engine/Default/includes/TraderTeamCombatResults.inc.php
As a result of adding the "minimal display" option to player vs player combat in 93c6e67e01e6b, we need to add a couple template variables to the CombatSimulator display page.
We rework the TraderTeamCombatResults template to allow `$ThisPlayer` to be null, in which case we don't display how much damage was done to "you".
> Fix combat results template for CombatSimulator

- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Account.php
- src/lib/Smr/Alliance.php
- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/Force.php
- src/lib/Smr/Galaxy.php
- src/lib/Smr/Game.php
- src/lib/Smr/Planet.php
- src/lib/Smr/Port.php
- src/lib/Smr/Sector.php
- src/lib/Smr/Session.php
- src/lib/Smr/WeightedRandom.php
Storing the Database object makes it difficult to use these classes in persistent scripts (e.g. Discord, NPC). If the database connection is reset, this reference would become invalid. It also makes unit testing harder since we can't inject it as a dependency.
The solution is to simply get the Database instance each time it is needed.
> Do not store Database as a class property

- phpcs.xml
- src/bootstrap.php
- src/lib/Smr/Account.php
* Use the PHP 8.2 SensitiveParameter attribute to prevent account passwords from being included in backtraces.
* Use a more comprehensive list of request fields that can include account passwords, which get redacted when dumping `$_REQUEST` in `logException`.
> Redact account passwords from error logs

- src/htdocs/imprint.php
At MrSpock's request, imprint data is no longer hard-coded. Instead, we download a JSON file with up-to-date data.
Add the "lastUpdated" time to the display.
> Generate imprint dynamically from JSON

- src/htdocs/login_create_processing.php
- src/htdocs/login_processing.php
- src/htdocs/login_social_create.php
- src/lib/Smr/Account.php
- src/lib/Smr/SocialLogin/Facebook.php
- src/lib/Smr/SocialLogin/Google.php
- src/lib/Smr/SocialLogin/SocialIdentity.php
- src/lib/Smr/SocialLogin/SocialLogin.php
- src/lib/Smr/SocialLogin/Twitter.php
- src/templates/Default/login/login_social_create.php
- test/SmrTest/lib/AccountTest.php
- test/SmrTest/lib/SocialLogin/SocialIdentityTest.php
Separate the concepts of the social login machinery from the storage of social identity.
The new `SocialIdentity` class will be the output of social login, and will not be allowed to exist in an invalid state.
Also disallow social registration without an email. Previously we allowed manually specifying an email in this case, but I think we should insist that the email is provided by the social platform.
> Refactor SocialLogin classes

- db/patches/V1_6_68_09__more_unique_constraints.sql
- src/htdocs/album/album_comment_processing.php
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Account.php
- src/lib/Smr/Alliance.php
- src/lib/Smr/Lotto.php
- src/lib/Smr/Page/Page.php
- src/lib/Smr/Sector.php
- src/pages/Account/AlbumEditProcessor.php
- src/pages/Account/BugReportProcessor.php
- src/pages/Account/ContactFormProcessor.php
- src/pages/Account/GameLeaveProcessor.php
- src/pages/Account/LoginProcessor.php
- src/pages/Account/PreferencesProcessor.php
- src/pages/Account/PreferencesTransferProcessor.php
- src/pages/Admin/AlbumModerateProcessor.php
- src/pages/Admin/ChangelogAddProcessor.php
- src/pages/Admin/UniGen/EditSectorProcessor.php
- src/pages/Admin/UniGen/SaveProcessor.php
- src/pages/Player/AllianceRolesProcessor.php
- test/SmrTest/lib/DatabaseIntegrationTest.php
* Navigating to the root URL now goes to "Current Sector" instead of "Play Game" when your session already has a game.
* Fix hanging when errors occur after a table is locked.
* Fix OOM error when game ends.
* Prevent duplicate values in lookup columns in database.
* Fix adding linked locations when editing a sector in UniGen.
> Miscellaneous bugfixes

- db/patches/V1_6_68_10__ship_changes_game150.sql
- src/lib/Default/sector_mines.inc.php
- src/lib/Smr/AbstractPlayer.php
- src/pages/Player/AttackPortConfirm.php
- src/pages/Player/ExaminePlanet.php
- src/pages/Player/ExamineTrader.php
- src/templates/Default/engine/Default/trader_examine.php
- test/SmrTest/lib/AbstractPlayerIntegrationTest.php
* Shuffle Devastator defenses in favor of armour.
* Additional protection for new players (newbie kill warnings and protections against mines).
* Display sector number in "Port Raid" and "Examine Planet" pages.
> Gameplay changes for game 150

- db/patches/V1_6_68_11__strict_sql.sql
- db/patches/V1_6_68_12__hof_signed_double.sql
- docker-compose.yml
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Account.php
- src/lib/Smr/Alliance.php
- src/lib/Smr/Session.php
- src/pages/Admin/IpViewResults.php
- src/pages/Player/AllianceMessageBoard.php
This helps to ensure that all queries behave in the expected way, and
respect the table/column definitions. For example, in non-strict mode,
if a column without a default value is omitted, MySQL will guess what
the default value should be and use that.
> Enable strict SQL mode

- src/templates/Default/engine/Default/game_play.php
In case the current game ends without one prepared to replace it, we want some way to direct players to get information about when the next game will start.
To achieve this, we add a note to the "Play Game" page if there is no active games and no games to join, with a link to the Discord server to get more information.
> game_play.php: add note when there are no games

- config/config.specific.sample.php
- phpstan.neon.dist
- src/pages/Account/ContactFormProcessor.php
This is a necessity in part because the `@smrealms.de` mailbox is overwhelmed with spam. But even if it weren't, this would allow for more prompt responses to submissions (e.g. CC'ing a personal email address that is monitored much more frequently than the official mailbox).
> Add configuration for CC addresses in Contact Form

- src/lib/Smr/SectorsFile.php
As a result of the indentation for the switch from engine pages to Page classes in 58258169e68c7, literal multi-line strings were accidentally prepended with tabs. This extra whitespace broke importing the SMR file in MGU.
We remove the prepended whitespace here by avoiding literal multiline strings.
> SectorsFile.php: remove unintentional indentation

- .github/workflows/run-tests.yml
We need to specify the token due to rate limiting of their global upload token.
We also want the workflow to fail if we can't upload the coverage report for any reason. Otherwise, it is too easy to overlook the absence of coverage data.
> Update codecov-action from v3 to v4

- composer.json
- test/SmrTest/Container/ResettableContainerTraitTest.php
- test/SmrTest/lib/Routes/RouteGeneratorTest.php
Address deprecation warnings:
> Targeting a trait such as Smr\Container\ResettableContainerTrait with #[CoversClass] is deprecated, please refactor your test to use #[CoversTrait] instead.
> returnValueMap() is deprecated and will be removed in PHPUnit 12. Use $double->willReturnMap() instead of $double->will($this->returnValueMap())
> Upgrade to PHPUnit 11

- Dockerfile
- api-docs/Dockerfile
> The 'as' keyword should match the case of the 'from' keyword
> FromAsCasing: 'as' and 'FROM' keywords' casing do not match
> More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
> Fix Dockerfile check from GitHub Actions

- src/pages/Player/Bank/AnonBankDetailProcessor.php
When depositing into an anon account, the database would overflow if the amount in the account would exceed MAX_MONEY. Now, the deposit will be adjusted so that it doesn't exceed MAX_MONEY, and if the account is already at MAX_MONEY, it will emit a comprehensible error.
> Handle overflow in anon bank deposits

- .github/actions/api-docs/Dockerfile
This version update should have taken place in #1968.
> api-docs: fix phpDocumentor version in Dockerfile

- src/lib/Default/smr.inc.php
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/AbstractShip.php
- src/lib/Smr/Account.php
- src/lib/Smr/Album.php
- src/lib/Smr/Alliance.php
- src/lib/Smr/Combat/Weapon/Weapon.php
- src/lib/Smr/Force.php
- src/lib/Smr/Galaxy.php
- src/lib/Smr/Globals.php
- src/lib/Smr/Location.php
- src/lib/Smr/Messages.php
- src/lib/Smr/Planet.php
- src/lib/Smr/PlanetTypes/PlanetType.php
- src/lib/Smr/Plotter.php
- src/lib/Smr/Port.php
- src/lib/Smr/Request.php
- src/lib/Smr/Sector.php
- src/lib/Smr/Session.php
- src/lib/Smr/ShipType.php
- src/lib/Smr/Template.php
- src/lib/Smr/WeaponType.php
In PHP 8.4, making function arguments implicitly nullable via a null default value is deprecated. The specified type must be explicitly nullable.
No functionality changes.
> Fix implicitly nullable function arguments

- src/htdocs/resend_password_processing.php
When the `email` request field doesn't exist, an error is thrown and it sends a bug report email. Even though the actual page has an HTML5 form property that prevents submitting an empty email, it appears that crawlers are submitting this page without the `email` field.
We can prevent this bug report email if we default `email` to an empty string, so that the user gets an error message response. This is not ideal, because it means that if the form breaks (e.g. field is changed without updating the processor), we won't get bug emails, but I think this is necessary to avoid the sheer volume of crawler bug emails.
> resend_password_processing.php: do not throw on no email

- composer.json
- phpstan.neon.dist
- src/lib/Default/alliance_pick.inc.php
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Chess/Board.php
- src/lib/Smr/Chess/ChessPiece.php
- src/lib/Smr/Globals.php
- src/lib/Smr/Port.php
- src/lib/Smr/Routes/Route.php
- src/lib/Smr/Routes/RouteIterator.php
- test/SmrTest/lib/BarDrinkTest.php
* Update rector to 2.0 as well due to its PHPStan dependency.
* Remove some `checkAlwaysTrue*` options that are now true by default.
* Fix errors reported by PHPStan 2.0 (some typos, wrong types, and wide types).
> Update to PHPStan 2.0

- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Container/DiContainer.php
- src/lib/Smr/Database.php
- src/lib/Smr/DatabaseRecord.php
- src/lib/Smr/DummyShip.php
- src/lib/Smr/Epoch.php
- src/lib/Smr/Port.php
- src/lib/Smr/SectorLock.php
- src/lib/Smr/Session.php
- src/lib/Smr/Template.php
- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/Container/DiContainerTest.php
- test/SmrTest/lib/DatabaseIntegrationTest.php
- test/SmrTest/lib/DatabaseRecordTest.php
- test/SmrTest/lib/SectorLockTest.php
- test/SmrTest/lib/SessionIntegrationTest.php
Use the `@template` syntax to reduce how often we return `mixed` types from container querying methods.
This impacts the following classes:
* DatabaseRecord
* DiContainer
> Container template methods

- src/lib/Default/smr.inc.php
- test/SmrTest/lib/functions/FormatTimeTest.php
- test/SmrTest/lib/functions/PluraliseTest.php
The `pluralise` function was not returning the correct pluralization for identically 1 float values. Since ceil/floor return a float, this was causing `format_time` to return strings like "1 minutes" instead of "1 minute".
This is fixed by casting the value to a float in the comparison to 1 in `pluralise`.
> Fix format_time pluralization

- src/lib/Smr/Chess/Board.php
- src/lib/Smr/Chess/ChessGame.php
- src/pages/Player/Chess/MatchPlay.php
- src/templates/Default/engine/Default/chess_play.php
- test/SmrTest/lib/Chess/BoardTest.php
* Checkmate no longer incorrectly happens when there are valid moves to block check.
* Two simple draw conditions are now checked to properly end the game in a draw:
1. Insufficient material (just two kings)
2. Stalemate
> Chess: fix checkmate and add draw

- .github/actions/api-docs/Dockerfile
- api-docs/Dockerfile
This adds support for PHP 8.3 and 8.4.
> api-docs: update phpDocumentor from 3.5.3 to 3.7.1

- .github/dependabot.yml
The use of `directories` instead of `directory` allows consolidating updates within the same package ecosystem. We had 4 docker entries with the same settings, which is now collapsed into a single entry.
The use of `groups` with the "php" pattern should allow all PHP version updates to occur in a single dependabot PR. This ensures consistency across the repo.
> dependabot.yml: use directories and groups

- src/lib/Smr/Force.php
- src/lib/Smr/Template.php
- src/templates/Default/engine/Default/includes/ForceTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/ForcesCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlanetCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PortCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PortTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/TraderTeamCombatResults.inc.php
- test/SmrTest/lib/TemplateTest.php
The combat templates were all duplicating the exact logic for building the damage taken display HTML. We refactor this logic into the Template methods `display{Force}TakenDamage`.
Also fix the messages so that they are properly pluralized.
Note that the kamikaze effect is handled slightly differently. Now, if there is a kamikaze, it subtracts that from the number of mines that were destroyed by non-kamikaze. Previously, it only printed the mine damage if it was greater than kamikaze, but then displayed the total number of mines lost. I think the new logic is more correct, but from a practical perspective they are identical, because combat drones do not currently do both kamikaze and normal damage to mines.
> Deduplicate damage taken display construction

- docker-compose.yml
Fixes the following warning:
> WARN[0000] secrets `uid`, `gid` and `mode` are not supported, they will be ignored
See https://github.com/docker/compose/issues/9648.
By inspection of the secrets file, the uid/gid is root and the mode is 0444. This seems fine for the current state of the container, but we can't change it if needed without further docker-compose development.
> docker-compose.yml: remove secrets mode attribute

- composer.json
- src/lib/Default/smr.inc.php
- test/SmrTest/lib/functions/BbifyTest.php
The vanilla/nbbc code has a deprecation warning that will be fixed with the following PR:
https://github.com/vanilla/nbbc/pull/39
While we wait for that to be merged, install from the PR branch to avoid the deprecation warning.
Added a test of the `bbify` function, since there was previously no test code exercising nbbc. Also pass the `smrBBCode` function as a first- class callable when creating BBCode rules.
> Fix php 8.4 deprecation in nbbc

- composer.json
Replace "github" with "vcs". I'm not sure why the former doesn't work, but it seems to give intermittent git/authentication errors that I wouldn't expect for a simple https download. If I still wanted to use "github", I think I would need to specify `"no-api": true`, otherwise the GitHub API would be used, maybe?
See https://getcomposer.org/doc/05-repositories.md#git-alternatives.
> composer.json: fix nbbc repository

- src/lib/Smr/Galaxy.php
- src/pages/Admin/UniGen/EditGalaxies.php
- src/pages/Admin/UniGen/EditGalaxiesAddProcessor.php
- src/pages/Admin/UniGen/EditGalaxiesProcessor.php
- src/templates/Default/engine/Default/admin/unigen/galaxies_edit.php
When designing games, it can be helpful to be able to add a new galaxy. In the past, we would have to create an entirely new game. This feature is only available for games that are not yet enabled.
It was easiest to create an empty dummy galaxy that could then be modified using the existing EditGalaxiesProcessor subsequently. I had considered creating a javascript interface where you specify all desired changes client-side before any submissions, but that was harder to code both for the display and the processing. Maybe something for the future.
* Galaxy::getConnectivity now handles 0-size galaxies, since that's the default for newly inserted galaxies.
* Galaxy::getStartSector no longer assumes that we have all the galaxy IDs starting from 1. This *should* be true, but I ran into this …
> UniGen: add ability to insert new galaxy

- src/lib/Smr/Galaxy.php
- src/pages/Admin/UniGen/EditGalaxies.php
- src/pages/Admin/UniGen/EditGalaxiesAddProcessor.php
- src/pages/Admin/UniGen/EditGalaxiesDelProcessor.php
- src/pages/Admin/UniGen/EditGalaxiesProcessor.php
- src/pages/Admin/UniGen/EditGalaxy.php
- src/templates/Default/engine/Default/admin/unigen/GalaxyDetails.inc.php
Implemented by reusing the galaxy resizing (setting the size to 0) from EditGalaxiesProcessor (with only a slight reorganization, no real logic changes) to handle the sector bookkeeping, and then deleting the galaxy.
Related fixes:
* Add early return in Galaxy::getMapSectors, which otherwise will throw if the size is 0 and it is the last galaxy ID (since the start sector it thinks it has won't exist).
* Fix the ordering of clearing the Galaxy cache and adding a new galaxy, since `Galaxy::createGalaxy` returns the cached galaxy if a galaxy with the same ID already exists. This fixes #2081, which only worked when the galaxy didn't exist.
* Fix the galaxyID for the back button when adding a new galaxy (and use the same kind of logic for deleting a galaxy) so that we return to the galaxy we …
> UniGen: add ability to delete galaxies

- src/lib/Smr/Planet.php
- src/pages/Player/Planet/LandProcessor.php
Newbie Help Alliance players should get to experience planet gameplay without needing to make themselves vulnerable by dropping their newbie turns in order to land.
As a consequence, newbie turns will be consumed for landing and building for consistency.
> Gameplay: allow NHA members to land on planets with newbie turns

- src/pages/Admin/UniGen/EditGalaxy.php
We were not passing along the galaxyID to the next container, and so it would default to galaxyID=1 and try to start that galaxy at the recenter sectorID (which usually was not in that galaxy).
> EditGalaxy: fix recenter link

- .my.cnf.sample
While this expands the permissions of commandline mysql access, using the non-root user was problematic in the live configuration because we modify the password on redeploy, which means we're not able to complete the password change without doing so as the root user.
Then we also run into issues where if the container is already running, the `.my.cnf` file won't be updated properly because it's file-mounted (and the container will continue to see the old inode).
Therefore, it's simpler to use the root user for commandline access.
> .my.cnf.sample: switch back to root user

- docker-compose.yml
- traefik/traefik-live.toml
* Contrary to smrealms/dockerize@24c8e5a, we are not allowed to have multiple email addresses for a single ACME resolver (even though Let's Encrypt seems to allow comma-delimited email registration). I'm not sure how this ever worked, but it creates a very clear error in traefik now: "Error validating contact(s) :: unable to parse email address".
* Mount the traefik subdirectory as read+write in the traefik service so that the `acme.json` file can be written. This recovers the dockerize repo behavior and fixes a "read-only file system" error.
> Fix traefik ACME certificate in live

- src/lib/Smr/AbstractShip.php
- test/SmrTest/lib/AbstractShipTest.php
Neither of these methods work if there are no Weapons.
Also add unit tests for these methods.
> AbstractShip: match assertions in moveWeapons{Up,Down}

- composer.json
This is a follow-up to #2078 now that the PR supporting PHP 8.4 has been merged upstream.
> Update to nbbc 3.0

- .github/dependabot.yml
This is necessary for updating packages like traefik, mysql, etc.
> Add docker-compose ecosystem to dependabot

- abstract-services.yml
In CI, we sometimes fail to start the mysql service in the allotted time. During the `start_period`, the test will be performed every 5s (by default) but won't count toward the number of retries. Then we'll try every 5s 10 times for a total of 30 + 50 = 80s. Timeout is decreased to 5s because the command should return almost immediately once mysql is ready for connections.
Note that this was likely failing because the first mysql run requires additional setup. If we continue to see failures, then there is likely some other issue at play.
> Give mysql service more time to pass healthcheck

- phpstan.neon.dist
As of phpstan 2.1.23, dynamic constants can be typehint. Previously, they were restricted to the type of their nominal value (which was problematic in particular for empty arrays).
Note that if any dynamic constants are typehinted, they ALL must be typehinted.
See https://github.com/phpstan/phpstan/commit/f678f174796aae2e
> phpstan: add typehints to dynamicConstantNames
