- templates/Default/engine/Default/planet_financial.php
Still need to figure out a way to style the dialog box. I've been playing with doing it dynamically using JQuery but I think it would be better to use the JQuery themeroller instead. As it stands the jquery-ui CSS overrides pretty much any changes.
> Issue #15. Warning dialog for planet bonding.

- lib/Login/SocialLogin.class.inc
Should work, but I've no way of testing at the moment.
> Facebook login fix

- engine/Default/council_embassy_processing.php
- templates/Default/engine/Default/council_vote.php
These two commits 1) add notifications for racial councils when a vote is added and 2) improve the voting center so that it is easier to understand for newer players. See the commit messages for more details.
> Council Vote Notifications and Voting Center improvements

- admin/Default/game_delete.php
* Prepend game numbers to game names in the dropdown to unambiguously
identify games.
* u -> you
> game_delete.php: minor display cleanup

- engine/Default/shop_goods.php
Replace a `<form>` that was supposed to be `</form>`.
> shop_goods.php: fix broken form html

- engine/Default/bank_report.php
Use a more traditional table instead of a list of tables.
> bank_report.php: improve report formatting

- engine/Default/smr.inc
- templates/Default/engine/Default/planet_construction.php
These commits make ajax updates more robust in general by ensuring that `xmlify` produces valid XML, and in the process fixes a specific issue with the Planet Construction page.
> Fix ajax updates

- admin/Default/1.6/universe_create_planets.php
- admin/Default/1.6/universe_create_save_processing.php
- templates/Default/admin/Default/1.6/universe_create_planets.php
The "Create Planets" page now has a list of all types of planets, rather than just creating Terran planets.
We also convert this page to a template and clean up some unused code.
> Add ability to create planets of any type

- Dockerfile
- composer.json
- htdocs/config.inc
- lib/Default/MySqlDatabase.class.inc
The mysql connector is deprecated in php 5.5 and removed from
php 7+. This change will allow us to seamlessly upgrade to php 7.
> Switch to mysqli database connector

- admin/Default/newsletter_send.php
- admin/Default/newsletter_send_processing.php
- templates/Default/admin/Default/newsletter_send.php
Major overhaul of the "Send Newsletter" admin tool:
* Converted to template
* Add html and plain text preview
* Add optional personalized salutation
* Add ability to change newsletter e-mail subject
See the commit messages for details about the changes.
> Additional functionality for "Send Newsletter"

- docs/README.md
- docs/docker-compose.yml
- docs/phpdox.xml
Provides simple infrastructure and configuration for serving the generated documentation.
> Add docker-compose service for serving documentation

- engine/Default/galactic_post_view_article.php
* Avoid re-inserting article into news on ajax updates
* Replace link with a "success" message once news is added to breaking news
* Tidy up some whitespace
> Fix posting GP article to Breaking News

- Dockerfile
- composer.json
- htdocs/config.inc
- lib/Default/MySqlDatabase.class.inc
This is because there are problems with mysqli and smr in production, so reverting this until we can get fully dockerised and hopefully remove whatever blocker is there
> Revert "Switch to mysqli database connector"

- .gitignore
- engine/Default/alliance_forces.php
- engine/Default/forces_list.php
- engine/Default/preferences_processing.php
- engine/Default/trader_status.php
- htdocs/email_processing.php
- templates/Default/engine/Default/alliance_planets.php
- templates/Default/engine/Default/council_embassy.php
- templates/Default/engine/Default/council_list.php
- templates/Default/engine/Default/council_politics.php
- templates/Default/engine/Default/council_vote.php
- templates/Default/engine/Default/course_plot.php
- templates/Default/engine/Default/game_join.php
- templates/Default/engine/Default/includes/PlanetList.inc
- templates/Default/engine/Default/includes/RightPanel.inc
- templates/Default/engine/Default/planet_main.php
The links are hard-coded now (apart from the `WIKI_URL` base), but I could add a constant for each linked page if that is preferable.
> Fix links pointing to wiki pages

- engine/Default/alliance_treaties_processing.php
Fix a couple bugs in the current alliance treaty processing page.
> alliance_treaties_processing.php: fix database errors

- templates/Default/admin/Default/announcement_create.php
Sometimes it's unclear what certain admin tools do. Add a sentence
briefly explaining "Create Announcement".
> announcement_create.php: add explanatory sentence

- engine/Default/alliance_message.php
- engine/Default/bank_alliance_processing.php
- engine/Default/bank_report.php
- engine/Default/port_attack_processing.php
- templates/Default/engine/Default/bank_alliance.php
* Fix an assortment of PHP warnings that were dominating the nginx logs
* Fix identification of non-player alliance message thread authors (e.g. Bank Reporter)
> Fix an assortment of PHP warnings and related minor bugs

- engine/Default/current_players.php
This feature was requested in 2011! They pointed out that
it may allow new players to more easily get help.
> current_players.php: add link to send global message

- admin/Default/log_console.php
- templates/Default/engine/Default/combat_log_viewer.php
> Fix PHP warnings

- htdocs/login_create.php
- htdocs/login_create_processing.php
- lib/Default/AbstractSmrAccount.class.inc
- tools/npc/npc.php
* Be less verbose about multiple accounts. It was an intimidating
paragraph (with some typos too).
* Link to multi rules on wiki instead of the webboard. The previous
link required a webboard login.
* Since address is optional, simply remove it altogether.
* Make it clearer what the "User Agreement" is.
> Simplify login creation

- lib/Default/SmrPlanet.class.inc
- templates/Default/engine/Default/planet_construction.php
This is a copy of PR #182, but without the exp scaling, as requested by the admins.
> Modify planet construction time formula

- templates/Default/engine/Default/game_join.php
Add a nbsp between "Name:", "Race:", and their corresponding
input boxes. This helps it feel a little less crowded.
> game_join.php: tweak spacing

- engine/Default/course_plot.php
- lib/Default/Plotter.class.inc
- lib/Default/SmrSector.class.inc
- templates/Default/engine/Default/course_plot.php
Added an additional category for "Plot To Nearest" called "Galaxies",
which will plot to the nearest sector in the galaxy you select.
This was a requested feature.
> Plot To Nearest: add Galaxies

- engine/Default/current_players.php
As requested, move the button above the player list so that it
doesn't bounce around as people log on and off.
> current_players.php: move Send Global Message button

- engine/Default/smr.inc
- lib/Default/Template.class.inc
- templates/Default/engine/Default/combat_log_list.php
- templates/Default/engine/Default/game_stats.php
- templates/Default/engine/Default/message_view.php
The pluralise function is useful outside the context of a template,
so make it a free function instead.
> Move pluralise from Template to free function

- engine/Default/album_delete_processing.php
- engine/Default/album_edit_processing.php
- engine/Default/alliance_leave_processing.php
- engine/Default/beta_apply_processing.php
- engine/Default/bug_report_processing.php
- engine/Default/cargo_dump_processing.php
- engine/Default/chess_resign_processing.php
- engine/Default/configure_hardware_processing.php
- engine/Default/contact_processing.php
- engine/Default/council_send_message_processing.php
- engine/Default/current_sector.php
- engine/Default/error.php
- engine/Default/galactic_post_application_processing.php
- engine/Default/game_play_processing.php
- engine/Default/leave_newbie_processing.php
- engine/Default/logged_in.php
- engine/Default/message_send_processing.php
- engine/Default/planet_main_processing.php
- engine/Default/preferences_processing.php
- engine/Default/smr.inc
- engine/Default/toggle_processing.php
- engine/Default/vote_link.php
- templates/Default/engine/Default/includes/LeftPanel.inc
* `current_sector.php` now forwards to `planet_main.php` if we're on a planet instead of erroring
* Remove duplicated logic throughout codebase when forwarding to current sector
* Enable current sector hotkey for going to the planet main page when on a planet
> Planet Main hotkey

- engine/Default/game_join.php
- templates/Default/engine/Default/game_join.php
* Remove a lot of duplicate sentences and ideas
* Compactify page heading and move Round description above game table
* Fix spelling and grammar mistakes
* Add some color to focus attention on key words
* Make it clear that naming rules descript prohibited behavior
* Reword short race descriptions to be a little less awkward
> game_join.php: reorganization and rewording

- lib/Default/MySqlDatabase.class.inc
Add the ability to close the mysql session.
> MySqlDatabase.class.inc: add close method

- .gitignore
- config/discord/config.specific.sample.php
- tools/chat_helpers/channel_msg_money.php
- tools/discord/Dockerfile
- tools/discord/GameLink.inc
- tools/discord/bot.php
- tools/discord/commands/game.php
- tools/discord/commands/invite.php
- tools/discord/commands/money.php
- tools/discord/commands/turns.php
- tools/discord/composer.json
- tools/discord/mysql_cleanup.php
We use DiscordPHP to build a bot for integration into Discord.
This handles the same responsibilities as Caretaker for IRC.
The Dockerfile that builds the bot image uses php:5.6-cli.
>  Add Discord integration tools

- templates/Default/engine/Default/skeleton.php
Put the vote links in a named span so that they can be AJAX
updated. It was odd to have the timer update without the images
(or links) changing.
> skeleton.php: allow vote links to AJAX update

- engine/Default/game_play.php
- engine/Default/game_stats.php
- templates/Default/engine/Default/game_stats.php
Minor modifications to the Game Stats page (including removing the Current Players display), and making it available to view for all previous 1.6 games.
> Game Stats for previous 1.6 games

- tools/chat_helpers/channel_msg_8ball.php
- tools/chat_helpers/channel_msg_forces.php
- tools/discord/bot.php
- tools/discord/commands/8ball.php
- tools/discord/commands/forces.php
- tools/irc/channel_msg.php
- tools/irc/irc.php
Adds 8ball and forces commands.
> Even more discord commands

- db/patches/V1_6_61_12__add_user_ranking.sql
Many players have reached Master, so a new rank will give them
something to work towards.
> Add Grandmaster user ranking

- engine/Default/album_edit_processing.php
Print an error message if the album photo failed to upload.
> album_edit_processing.php: check file upload result

- admin/Default/album_approve.php
- engine/Default/graph.php
- templates/Default/engine/Default/album_edit.php
Fix a couple PHP warnings and remove an unused file.
> Minor cleanup

- templates/Default/engine/Default/alliance_message.php
- templates/Default/engine/Default/includes/PlanetList.inc
* Planet List: fix sorting by "Level"
* Alliance Message Board: fix sorting by "Last Reply"
> Fix two list.js sorting issues

- admin/Default/1.6/universe_create_save_processing.php
While the whole Newbie Help Alliance message board is in desperate
need of some cosmetic and informational updating, this patch
only fixes the most egregious typos.
> Fix typos in Newbie Help Alliance message board

- htdocs/css/Freon22-layout.css
- templates/Default/engine/Default/includes/RightPanelPlayer.inc
- templates/Default/engine/Default/includes/RightPanelShip.inc
- templates/Default/engine/Default/includes/VoteLinks.inc
- templates/Default/engine/Default/skeleton.php
- templates/Freon22/engine/Default/includes/LeftPanel.inc
- templates/Freon22/engine/Default/skeleton.php
The Freon22 template has gotten slightly out of sync with the Deafult
template, so make some changes to synchronize them:
* Move vote links code out of skeleton.php and into `VotesLinks.inc`,
which is now included in both templates.
* Factor `RightPanel.inc` into `RightPanelPlayer.inc` (used only in
Default) and  `RightPanelShip.inc` (used in both).
> Fix Freon22 skeleton.php

- engine/Default/current_players.php
- engine/Default/trader_search_result.php
Compactify code by using this helper function instead of
manually constructing the array.
> Use create_container in some places

- engine/Default/game_stats.php
- templates/Default/engine/Default/game_stats.php
Enhance the game stats that are available for previous games.
> game_stats.php: add alliance rankings

- engine/Default/current_players.php
- templates/Default/engine/Default/current_players.php
Convert this page to a template and switch from server-side
mysql sorting to client-side list.js sorting.
> current_players.php: use list.js to sort

- engine/Default/government.php
- engine/Default/shop_ship_processing.php
- engine/Default/shop_weapon_processing.php
- engine/Default/underground.php
- htdocs/config.php
- htdocs/ship_list.php
- htdocs/weapon_list.php
This address https://github.com/smrealms/smr/pull/272#discussion_r161069366.
> Define constants for buyer restrictions and alignment

- admin/Default/1.6/universe_create_save_processing.php
- htdocs/config.php
- lib/Default/council.inc
* MIN_GLOBAL_RELATIONS = -500
* MAX_GLOBAL_RELATIONS = 500
> config.php: add constants for Relations

- Dockerfile
- docker-compose.yml
* Use production php.ini by default
* Disable apache .htaccess
> Optimize php-apache image

- templates/Default/engine/Default/course_plot.php
* Use html5 input type `number` to restrict sector ID input
* Rename label from "Destination" to "Sector" for clarity.
> course_plot.php: restrict new destination input

- templates/Default/engine/Default/bar_opening.php
- templates/Default/engine/Default/donation.php
For now I've just hard-coded the correct pluralization, since
the boilerplate for using `pluralise` in templates is annoying.
> Correct SMR Credit pluralization

- engine/Default/underground.php
> underground.php: add some simple flavor text

- engine/Default/bar_gambling_lotto.php
- engine/Default/bar_gambling_processing.php
* bar_gambling_lotto.php: use format_time
Reduce code duplication by using existing `format_time` helper
function.
* bar_gambling_processing.php: fix ticket pluralization
Since players will always encounter the scenario where they have
purchased one ticket, fix the pluralization of how many tickets
you have purchased.
> Bar gambling cleanup

- lib/Default/bar.functions.inc
* Better document what is going on in this function.
* Simplify the sql queries. We know that we're essentially
deleting every ticket when a winner is determined, so
just do it.
* Use a `while` loop for unclaimed prizes instead of `if`
just in case we somehow get a backlog of unclaimed prizes.
> bar.functions.inc: clean up checkForLottoWinner

- engine/Default/trader_relations.php
- templates/Default/engine/Default/trader_relations.php
* Convert to an actual table.
* Rename "Global Relations" to "Political Relations" to make it
clearer what it actually is. (I think internally political or
"race" relations were called "global" because they were accessed
via the `Globals` class.)
* Add a new column for the total relations.
>  trader_relations.php: visual cleanup

- admin/Default/newsletter_send_processing.php
* Improve progress reporting and display
* Fix a bug with reply-to addresses for mass mailings
* Give PHP unlimited time to send the mass mailings
> Newsletter send progress

- admin/Default/newsletter_send_processing.php
The previous buffering strategy only worked in debug environments
where output buffering was turned off in php.ini. The new controls
turn off all PHP and Nginx buffering.
> newsletter_send_processing.php: tweak buffering

- engine/Default/game_join_processing.php
- htdocs/config.inc
- templates/Default/engine/Default/current_players.php
- tools/npc/chess.php
- tools/npc/npc.php
* Fix bug with shutting down cleanly
* Fix NPC display name in CPL
* Fix NPC trading due to SmrPort refactoring
* Moderate refactoring
> Various NPC fixes

- admin/Default/account_edit.php
* Fix missing variable
* Fix dropdown display
> Fixes for Edit Account admin tool

- engine/Default/shop_goods.php
- lib/Default/AbstractSmrShip.class.inc
This complements the `isFederal` method.
> SmrShip: add isUnderground method

- admin/Default/ip_view_results.php
This code doesn't use any objects and has extremely old design
patterns. It also emits many warnings and sometimes causes 502
Bad Gateway errors (perhaps due to the overwhelming number of
warnings?).
* Use objects and their methods where it makes sense from a
DB performance standpoint to do so (e.g. `SmrAccount` and
`isDisabled`).
* Use `implode` to join lists of strings together.
* Remove the special case for `Account tagged for deletion`
closing reasons (which isn't a closing reason that exists).
* Since `host` is stored in `account_has_ip`, don't recompute
it. It's only for informational purposes anyway.
* Minor fixes:
- Remove an extra column
- Replace an erroneous `ip` with `$ip`
- Fix copy-pasted code for result description
There is still a lot of code duplication here, but for now …
> ip_view_results.php: modernize code

- templates/Default/engine/Default/course_plot.php
* Add a sentence of text describing how to add/organize
sector destinations.
* Include the sector number in the displayed label.
> course_plot.php: make stored destinations clearer

- docker-compose.yml
* Switch from deprecated `links` option to `depends_on`.
* Add mysql service as an explicit dependency to all services that require it.
> docker-compose.yml: update dependencies

- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/AbstractSmrShip.class.inc
- lib/Default/SmrCombatDrones.class.inc
- lib/Default/SmrGalaxy.class.inc
- lib/Default/SmrGame.class.inc
- lib/Default/SmrLocation.class.inc
- lib/Default/SmrMines.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrPort.class.inc
- lib/Default/SmrSector.class.inc
- lib/Default/SmrShip.class.inc
- lib/Default/SmrWeapon.class.inc
More progress towards the goal of removing references that were incorrectly used.
> Remove internal references in classes

- templates/Default/engine/Default/includes/PlottedCourse.inc
> PlottedCourse.inc: fix pluralization

- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/SmrLocation.class.inc
- lib/Default/SmrPlanet.class.inc
* SmrPlanet
* SmrLocation
* AbstractSmrAccount
* AbstractSmrPlayer
Adding a SQL member visually simplifies a lot of queries and
reduces the number of times we call `escapeNumber`, which is
a non-trivial expense when called as many times as it is.
> Add SQL members to more classes

- lib/Default/SmrShip.class.inc
* Add SQL member to reduce `escapeNumber` calls.
* Remove unnecessary DB call when saving all SmrShip instances.
> Optimizations in SmrShip

- lib/Default/smr.inc
See #317.
Also fix spelling of `doSkeletonAssigns`.
> smr.inc: remove references in function arguments

- engine/Default/planet_bond_confirmation.php
- engine/Default/planet_stockpile.php
- templates/Default/engine/Default/planet_bond_confirmation.php
- templates/Default/engine/Default/planet_stockpile.php
* planet_stockpile.php
* planet_bond_confirmation.php
> Convert a couple pages to templates

- engine/Default/alliance_leadership.php
- engine/Default/alliance_roster.php
- lib/Default/SmrAlliance.class.inc
- templates/Default/engine/Default/alliance_leadership.php
Also add `SmrAlliance::getMembers` as a convenience wrapper around
`SmrPlayer::getAlliancePlayers`.
> alliance_leadership.php: convert to template

- engine/Default/games_previous.php
* Remove a huge chunk of code when no game is specified. This duplicates the `game_play.php` code, and is unused, so we remove it.
* Modernize styling, getting rid of the `align` attribute in particular.
> Cleanup games_previous.php

- lib/Default/council.inc
> council.inc: remove unnecessary references

- lib/Default/SmrPlayer.class.inc
- templates/Default/engine/Default/includes/RightPanelPlayer.inc
- templates/Freon22/engine/Default/skeleton.php
This method factors out the work that is duplicated in the
skeleton for each of the templates.
> SmrPlayer: add method getTurnsColor

- engine/Default/rankings_view.php
Use the cached `Globals::getUserRanking` function instead of
duplicating the db query here.
> rankings_view.php: remove duplicate db query

- engine/Default/trader_search.php
- engine/Default/trader_search_result.php
- templates/Default/engine/Default/trader_search.php
- templates/Default/engine/Default/trader_search_result.php
* Convert trader_search_result.php to a template.
* Visually clean up some of the formatting on the search pages.
> Trader search polishing

- engine/Default/smr_file_create.php
* Remove references (no major impact on memory)
* Clear caches after processing each galaxy (major impact on memory)
> smr_file_create.php: fix OOM errors

- admin/Default/album_moderate.php
- templates/Default/admin/Default/album_moderate.php
Improvements made during conversion:
* Remove outdated HTML elements (e.g. `align`).
* Select from a dropdown of eligible album entries instead of
having to enter an account ID. (This also fixes an exception
that was thrown when an invalid account ID was specified.)
* Convert some forms that don't post any data into links.
> album_moderate.php: convert to template

- db/patches/V1_6_62_17__set_nmv_starter.sql
This is a more appropriate ship class for the NMV since it is
the ship that newbies start with.
> Change NMV ship class from Hunter to Starter

- admin/Default/album_approve.php
- lib/Default/Template.class.inc
* Template.class.inc: simplify join statement
Use the `join` PHP function instead of manually joining the
elements of an array.
* album_approve.php: simplify get_album_nick function
> Simplify a couple functions

- engine/Default/alliance_share_maps_processing.php
- engine/Default/bar_main.php
- engine/Default/bar_read_wall.php
- engine/Default/beta_func_processing.php
- engine/Default/bounty_claim.php
- engine/Default/bounty_place.php
- engine/Default/bounty_place_confirm.php
- engine/Default/cargo_dump_processing.php
- engine/Default/course_plot_nearest_processing.php
- engine/Default/military_payment_claim.php
- engine/Default/planet_attack_processing.php
- engine/Default/port_attack_processing.php
- engine/Default/sector_jump_processing.php
- engine/Default/sector_scan.php
- engine/Default/shop_goods_processing.php
- engine/Default/trader_attack_processing.php
This variable is already defined as `$player->getSector()` in
`do_voodoo`, so there is no need to redefine it.
> Don't reassign to $sector

- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/missions.inc
This will allow the (rather large) arrays to be cached by OPcache
and will speed up mission processing.
> Convert mission arrays to PHP constants

- admin/Default/1.6/universe_create_sectors.php
- engine/Default/map_local.php
- htdocs/map_galaxy.php
- lib/Default/SmrGalaxy.class.inc
This method allows us to refactor duplicated code out of Local Map,
Galaxy Map, and Uni Gen.
> SmrGalaxy: add getMapSectors method

- engine/Default/shop_ship_processing.php
- lib/Default/SmrPort.class.inc
- lib/Default/shop_goods.inc
Replace them with the named constants `RACE_*`.
> Remove hard-coded race ID's

- engine/Default/alliance_remove_member.php
Put a space between the player name and player ID.
> alliance_remove_member.php: improve name display

- admin/Default/1.6/universe_create_ports.php
- admin/Default/1.6/universe_create_save_processing.php
- lib/Default/AbstractSmrShip.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrSector.class.inc
- lib/Default/smr.inc
- templates/Default/engine/Default/includes/SectorMap.inc
This feature was supposed to be a new type of location (i.e. an
asteroid) that you could mine for precious metals.
We remove it for 3 reasons:
1. This feature of the game was not used.
2. The database tables associated with this feature do not exist,
so we could not enable it without significant work.
3. It uses a poorly chosen name ("mining" and "mines", which
conflict with mines as forces).
Also clean up "Create Ports"
* Remove "...and Mines"
* Make totals disabled inputs because they shouldn't be modified
manually.
NOTE: the UniGen previously had a confusing option to create "Mines".
> Remove "mining"

- engine/Default/beta_func_processing.php
1. Don't let beta functions tell the player he's under attack.
(He's not -- we're just changing his hardware.)
2. Don't pass `$player` unnecessarily.
> beta_func_processing.php: small fixes to doUNO

- lib/Default/SmrShip.class.inc
* Rename loadWeapon -> loadWeapons
* Add docstring to clarify what this method does
This method is responsible for initializing the SmrWeapon array
for weapons that are already onboard this ship. The previous
version was easy to confuse with `addWeapon`.
> SmrShip: document and rename loadWeapon

- engine/Default/contact.php
- templates/Default/engine/Default/contact.php
Reworked the text a little and shortened the message box by 100px.
> contact.php: convert to template

- admin/Default/album_approve.php
- admin/Default/album_approve_processing.php
- templates/Default/admin/Default/album_approve.php
Change the Approve form into two Approve/Reject submit-style
buttons.
> album_approve.php: convert to template

- engine/Default/bar_galmap_buy.php
- engine/Default/bar_ticker_buy.php
- templates/Default/engine/Default/bar_galmap_buy.php
- templates/Default/engine/Default/bar_ticker_buy.php
* bar_galmap_buy.php
* bar_ticker_buy.php
> Convert bar pages to templates

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/1.6/universe_create_sector_details.php
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrPlayer.class.inc
* Fix an instance of an include that isn't using `get_file_loc`
* Correctly display when a Bunker is destroyed
* Don't hard-code the max level of ports
> Various bugfixes

- admin/Default/1.6/universe_create_save_processing.php
- htdocs/js/smr15.js
- templates/Default/admin/Default/1.6/universe_create_ports.php
Add a jQuery button to clear the port levels so that you can either
start from scratch or submit to remove all ports.
> universe_create_ports.php: add button to zero ports

- templates/Default/engine/Default/newbie_warning.php
Fix some typos and minor wordsmithing.
> newbie_warning.php: clean up newbie turn warning text

- templates/Default/engine/Default/planet_defense.php
- templates/Default/engine/Default/shop_weapon.php
- templates/Default/engine/Default/weapon_reorder.php
* Shink some columns to reduce empty space
* Add "%" symbol to Accuracy consistently
* Add Power Level to mounted weapons on planets
> Clean up weapon display tables

- htdocs/level_requirements.php
* Use CSS styles and center the table in the page
* Replace explicit database call with Globals::getLevelRequirements
> level_requirements.php: simplify

- lib/Default/AbstractSmrAccount.class.inc
- lib/Default/smr.inc
Use cryptographically strong random string generators to create the account validation and password reset codes.
This fixes a possible account validation exploit and prevents the password reset codes from leaking private data.
> Generate random validation/password reset codes

- admin/Default/1.6/game_create.php
- admin/Default/1.6/game_create_processing.php
- admin/Default/1.6/universe_create_galaxies.php
- admin/Default/1.6/universe_create_sectors.php
- admin/Default/1.6/upload_smr_file_processing.php
- engine/Default/smr_file_create.php
- lib/Default/AbstractSmrPort.class.inc
- lib/Default/smr.inc
- templates/Default/admin/Default/1.6/game_create.php
- templates/Default/admin/Default/1.6/universe_create_galaxies.php
Enhancement to the Uni Gen to allow admins to create game universes from an uploaded SMR file.
* Number of galaxies now chosen on the create galaxy page instead of the create game page
* Max force time added to SMR file (bumped version number to 1.04)
See individual commit messages for technical details.
> Create universe from SMR file

- lib/Album/album_functions.php
* Minor language edits
* Fix typo ("fictitional" -> "fictional")
> Clean up album rules

- engine/Default/album_edit_processing.php
- engine/Default/bug_report_processing.php
- engine/Default/contact_processing.php
- engine/Default/error.php
- engine/Default/game_play_processing.php
- engine/Default/logged_in.php
- engine/Default/preferences.php
- engine/Default/preferences_processing.php
- engine/Default/rankings_view.php
- htdocs/loader.php
- htdocs/map_galaxy.php
- htdocs/map_warps.php
- lib/Default/AbstractSmrLocation.class.inc
- lib/Default/ChessGame.class.inc
- lib/Default/Menu.class.inc
- lib/Default/SmrSession.class.inc
- lib/Default/Template.class.inc
- lib/Default/gov.functions.inc
- lib/Default/smr.inc
- lib/Hunter Wars/SmrLocation.class.inc
- templates/Default/engine/Default/includes/VoteLinks.inc
- tools/npc/chess.php
- tools/npc/npc.php
- tools/rerunChessGames.php
This helps us keep track of where the $game_id is being changed,
since it can now only be changed by the `SmrSession::updateGame`
method.
Added access methods `hasGame` and `getGameID` in the SmrSession
class.
> SmrSession: make $game_id private

- engine/Default/shop_goods.php
- lib/Default/AbstractSmrShip.class.inc
- templates/Default/engine/Default/shop_goods.php
Convert page to template and replace hard-coded numerical good IDs with named constants.
> Shop goods template

- admin/Default/1.6/universe_create_sector_details.php
- engine/Default/alliance_leave_confirm.php
- engine/Default/bank_anon.php
- engine/Default/bank_anon_create.php
- engine/Default/bank_anon_create_processing.php
- engine/Default/bank_anon_detail.php
- engine/Default/bank_anon_detail_processing.php
- engine/Default/bank_personal.php
- engine/Default/bounty_place.php
- engine/Default/bounty_place_confirm.php
- engine/Default/changelog_view.php
- engine/Default/council_send_message.php
- engine/Default/message_notify_confirm.php
- templates/Default/admin/Default/1.6/universe_create_sector_details.php
- templates/Default/engine/Default/alliance_leave_confirm.php
- templates/Default/engine/Default/bank_anon.php
- templates/Default/engine/Default/bank_anon_create.php
- templates/Default/engine/Default/bank_anon_detail.php
- templates/Default/engine/Default/bank_personal.php
- templates/Default/engine/Default/bounty_place.php
- templates/Default/engine/Default/bounty_place_confirm.php
- templates/Default/engine/Default/changelog_view.php
- templates/Default/engine/Default/council_send_message.php
- templates/Default/engine/Default/message_notify_confirm.php
See #30.
* changelog_view.php
* universe_create_sector_details.php
* bounty_place_confirm.php
* bank_personal.php
* council_send_message.php
* message_notify_confirm.php
* bounty_place.php
* bank_anon.php
* alliance_leave_confirm.php
> Convert more pages to templates

- admin/Default/anon_acc_view.php
- templates/Default/admin/Default/anon_acc_view.php
* Add a "Back" button
* Clarify that "Account ID" refers to an anon account ID
* Improve error message when account doesn't exist
> anon_acc_view.php: convert to template

- admin/Default/1.6/universe_create_ports.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/Distance.class.inc
- lib/Default/SmrForce.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrPlayer.class.inc
- lib/Default/SmrSector.class.inc
- lib/Default/VoteSite.class.inc
- lib/Semi Wars/SmrAccount.class.inc
This is a proof-of-concept PR that fixes a small fraction of the errors reported by Scrutinizer CI. Many more changes to come. See commit messages for details.
> Fix errors found by Scrutinizer CI

- admin/Default/account_edit.php
- htdocs/config.inc
- htdocs/config.php
- lib/Default/AbstractSmrShip.class.inc
- templates/Default/admin/Default/account_edit.php
- templates/Default/engine/Default/includes/Head.inc
- templates/Default/login.inc
> Miscellaneous enhancements

- engine/Default/bank_anon_detail.php
- engine/Default/bank_report.php
- engine/Default/combat_log_viewer.php
- engine/Default/game_join.php
- engine/Default/message_notify_confirm.php
- engine/Default/news_read_advanced.php
- engine/Default/reopen_account.php
- engine/Default/shop_goods.php
- engine/Default/shop_hardware.php
- engine/Default/trader_search_result.php
- htdocs/login_processing.php
- lib/Default/Template.class.inc
* Add Template class destructor that warns if a template variable was assigned but not displayed.
* Fix a missing Template instantiation in login_processing.php.
* Fix innocuous cases of assigning template vars before forwarding.
> Template: add an error-checking dtor and other fixes

- lib/Default/AbstractSmrAccount.class.inc
* Explicitly declare visibility for methods
* Explicitly declare properties
> SmrAccount: fix Scrutinizer best practices

- db/patches/V1_6_63_14__drop_blackjack_table.sql
- engine/Default/bar_gambling_processing.php
- lib/Default/PlayingCard.class.inc
* Add a new class `PlayingCard` that handles blackjack card logic in a simple object-oriented way.
* Remove the `blackjack` table and its associated obsolete sanity check.
> Simplify blackjack engine

- engine/Default/galactic_post.php
- templates/Default/engine/Default/galactic_post.php
Also raise exception if page is accessed by non-Editor.
> galactic_post.php: convert to template

- lib/Default/SmrSector.class.inc
Remove some unnecessary:
* temporary variables
* if-statements
* early returns
> Clean up some SmrSector methods

- engine/Default/preferences_processing.php
- lib/Default/AbstractSmrPlayer.class.inc
- lib/Default/Menu.class.inc
- templates/Default/admin/Default/account_edit.php
- templates/Default/admin/Default/box_view.php
- templates/Default/admin/Default/manage_draft_leaders.php
- templates/Default/engine/Default/alliance_mod.php
- templates/Default/engine/Default/alliance_roster.php
- templates/Default/engine/Default/chat_rules.php
- templates/Default/engine/Default/chat_sharing.php
- templates/Default/engine/Default/council_send_message.php
- templates/Default/engine/Default/council_vote.php
- templates/Default/engine/Default/feature_request.php
- templates/Default/engine/Default/history_games_hof.php
- templates/Default/engine/Default/planet_defense.php
- templates/Default/engine/Default/planet_stockpile.php
- templates/Default/engine/Default/trader_search.php
These HTML errors were identified by `DOMDocument::loadHTML`.
> Fix invalid HTML

- engine/Default/album_edit.php
- engine/Default/album_edit_processing.php
- engine/Default/buy_ship_name_processing.php
- templates/Default/engine/Default/album_edit.php
- templates/Default/engine/Default/buy_ship_name.php
* Better and more consistent error checking for image uploads
* Enhancements to the "Album Edit" page on submission
> Image uploads and Album Edit

- engine/Default/bar_gambling_processing.php
- engine/Default/hall_of_fame_player_detail.php
- templates/Default/engine/Default/alliance_roster.php
- templates/Default/engine/Default/trader_status.php
* alliance_roster.php: fix another form HTML consistency issue
* trader_status.php: fix invalid HTML
* Synchronize the personal hall of fame browsing code with the global hall of fame
* Color blackjack result messages and add a missing result message
> Minor fixes

- engine/Default/bank_report.php
- engine/Default/bank_report_processing.php
- templates/Default/engine/Default/bank_report.php
* Add separate processing page to avoid resending the report to the alliance message board on each ajax update.
* Convert the page to a template.
> bank_report.php: cleanup

- docs/Dockerfile
- engine/Default/mission_accept_processing.php
- engine/Default/mission_claim_processing.php
- lib/Default/AbstractSmrPort.class.inc
- lib/Default/Plotter.class.inc
- lib/Default/bar.functions.inc
- lib/Default/smr.inc
- tools/npc/npc.php
* Fix phpdox installation
* Fix a couple NPC errors/warnings
* Fix unused code and other trivial errors
> Various minor fixes

- .travis.yml
- Dockerfile
- composer.json
- docs/Dockerfile
- tools/discord/Dockerfile
- tools/discord/composer.json
- tools/irc/Dockerfile
- tools/irc/composer.json
- tools/npc/Dockerfile
- tools/npc/composer.json
No changes needed other than an update to UOPZ.
> Upgrade to php 7.3

- templates/Default/engine/Default/includes/PlanetList.inc
- templates/Default/engine/Default/includes/PlanetListFinancial.inc
- templates/Default/engine/Default/planet_construction.php
- templates/Default/engine/Default/planet_main.php
* Fix a few HTML issues.
* Revamp the "Construction" table.
* Improve spacing around supplies in Planet List.
> Minor improvements to planet tables

- admin/Default/changelog.php
- admin/Default/ship_check_processing.php
- engine/Default/bank_alliance_exempt_processing.php
- engine/Default/bug_report_processing.php
- engine/Default/contact_processing.php
- engine/Default/course_plot.php
- engine/Default/forces_drop.php
- engine/Default/galactic_post_make_paper_processing.php
- engine/Default/galactic_post_paper_edit_processing.php
- engine/Default/game_join.php
- engine/Default/game_play.php
- engine/Default/hall_of_fame_new.php
- engine/Default/map_local.php
- engine/Default/message_blacklist_add.php
- engine/Default/planet_defender_check.php
- engine/Default/trader_status.php
- lib/Default/SmrForce.class.inc
- lib/Default/smr.inc
* Simplify function `format_time`.
* Use `create_container` instead of constructing containers directly from `array`.
* Remove unused file `planet_defender_check.php`.
> Miscellaneous changes

- admin/Default/permission_manage_processing.php
- lib/Default/smr.inc
* smr.inc: fix format_time for 0 seconds
* permission_manage_processing.php: fix PHP warnings
> Misc PHP fixes

- engine/Default/planet_land_processing.php
- engine/Default/planet_ownership.php
We can replace these queries with `SmrPlanet` methods.
> Remove direct queries to the planet table

- admin/Default/account_edit_processing.php
- admin/Default/changelog.php
- admin/Default/changelog_add_processing.php
- admin/Default/manage_post_editors.php
- admin/Default/permission_manage.php
- db/patches/V1_6_63_18__drop_player_cache.sql
- engine/Default/alliance_mod.php
- engine/Default/galactic_post_write_article_processing.php
- htdocs/login_social_processing.php
- lib/Default/Globals.class.inc
- lib/Default/smr.inc
- templates/Default/admin/Default/account_edit.php
- templates/Default/admin/Default/changelog.php
- templates/Default/admin/Default/manage_post_editors.php
- templates/Default/engine/Default/alliance_roster.php
- templates/Default/engine/Default/galactic_post_write_article.php
- templates/Default/engine/Default/includes/AllianceRole.inc
- templates/Default/engine/Default/includes/PortTraderTeamCombatResults.inc
> Miscellaneous Updates

- admin/Default/account_edit_processing.php
- db/patches/V1_6_63_19__admin_news.sql
- engine/Default/game_join_processing.php
- engine/Default/login.inc
- engine/Default/news_read.php
- engine/Default/news_read_advanced.php
- engine/Default/news_read_current.php
- engine/Default/preferences_processing.php
- lib/Default/news.functions.inc
- templates/Default/engine/Default/includes/NewsTable.inc
- templates/Default/engine/Default/news_read.php
- templates/Default/engine/Default/news_read_advanced.php
- templates/Default/engine/Default/news_read_current.php
* Refactor to avoid duplication between the 3 news pages (and make them consistent).
* Handle administrative messages separately from other news.
* Add news entry when players join the game.
> Minor News Updates

- engine/Default/album_edit_processing.php
- engine/Default/beta_func_processing.php
- engine/Default/combat_simulator.php
- engine/Default/forces_drop_processing.php
> Scrutinizer fixes

- htdocs/js/ajax.js
- htdocs/js/map_warps.js
> Fix javascript warnings

- htdocs/vote_link_callback.php
- lib/Default/Council.class.inc
- lib/Default/Rankings.class.inc
- lib/Default/SmrScoutDrones.class.inc
- lib/Default/SmrShip.class.inc
- lib/Default/VoteSite.class.inc
- lib/autoload.inc
- tools/discord/bot.php
- tools/discord/commands/8ball.php
- tools/discord/commands/forces.php
- tools/discord/commands/game.php
- tools/discord/commands/invite.php
- tools/discord/commands/money.php
- tools/discord/commands/op.php
- tools/discord/commands/seed.php
- tools/discord/commands/turns.php
- tools/discord/mysql_cleanup.php
- tools/irc/channel_msg.php
- tools/irc/channel_msg_op.php
- tools/irc/server.php
@hemberger requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/smrealms/smr/
> Scrutinizer Auto-Fixes

- admin/Default/newsletter_send_processing.php
- lib/Default/Menu.class.inc
- lib/Default/Rankings.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/missions.inc
- lib/Default/news.functions.inc
- lib/Default/shop_goods.inc
- tools/npc/npc.php
> Miscellaneous cleanup

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/account_edit_processing.php
- admin/Default/comp_share.php
- engine/Default/bar_gambling_processing.php
- engine/Default/council_vote.php
- engine/Default/current_players.php
- engine/Default/feature_request.php
- engine/Default/feature_request_comments.php
- engine/Default/game_join.php
- engine/Default/game_join_processing.php
- engine/Default/login_story.inc
- engine/Default/note_add_processing.php
- engine/Default/sector_move_processing.php
- htdocs/config.inc
- htdocs/login_processing.php
- lib/Album/album_functions.php
- lib/Default/Council.class.inc
- lib/Default/SmrShip.class.inc
- templates/Default/engine/Default/chess_play.php
- templates/Default/engine/Default/includes/RightPanelShip.inc
> Miscellaneous fixes

- htdocs/css/Default.css
- htdocs/css/shared.css
- htdocs/js/smr15.js
> Minor changes to CSS/JS

- htdocs/js/filter_list.js
* Remove unnecessary `in_array` function
* Avoid unnecessarily referencing `window`
* Avoid the need to prepoulate the filter array
These changes should make the script a little easier to work with and also avoids modifying the array prototype (generally something to avoid), I haven't tested these because live SMR still has the old html so I can't drop in my changes to test but can do so once it's deployed if you want to wait
> filter_list.js cleanup

- engine/Default/smr_file_create.php
- htdocs/js/ajax.js
- templates/Default/admin/Default/1.6/universe_create_sectors.php
- templates/Default/engine/Default/includes/LeftPanel.inc
- templates/Freon22/engine/Default/includes/LeftPanel.inc
Addresses two reported cases of "Multiple actions..." errors:
1. On form submission (e.g. while trading)
2. When clicking "DL Sectors File"
> Avoid multiple actions errors

- htdocs/config.inc
- htdocs/config.php
- lib/Default/SmrSession.class.inc
- lib/Default/Template.class.inc
A handful of changes to the exception logging (and related improvements identified while testing these changes) that will be useful for more automatic reporting of any issue identified on the beta server.
> Improve error reporting

- lib/Default/SmrSession.class.inc
- tools/npc/npc.php
* Avoid `setcookie` headers warning
* Change the way we select NPC's
> Fix a couple NPC issues

- admin/Default/1.6/galaxies_edit_processing.php
- admin/Default/1.6/galaxy_reset_processing.php
- admin/Default/1.6/game_create_processing.php
- admin/Default/1.6/universe_create_galaxies.php
- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/1.6/universe_create_sectors.php
- htdocs/map_warps.php
- lib/Default/AbstractSmrLocation.class.inc
- lib/Default/SmrGalaxy.class.inc
- lib/Default/SmrGame.class.inc
- lib/Default/SmrPlanet.class.inc
- lib/Default/SmrSector.class.inc
- templates/Default/admin/Default/1.6/GalaxyDetails.inc
- templates/Default/admin/Default/1.6/galaxies_edit.php
- templates/Default/admin/Default/1.6/universe_create_galaxies.php
- templates/Default/admin/Default/1.6/universe_create_sectors.php
Adds the following options:
* Edit Galaxy Details -- change galaxy metadata and dimensions
* Reset Current Galaxy -- clears all fixtures (ports, planets, warps, locations, connections) from the current galaxy
> Add new Uni Gen functionality

- admin/Default/1.6/universe_create_save_processing.php
- admin/Default/1.6/universe_create_sector_details.php
- admin/Default/1.6/universe_create_sectors.php
- templates/Default/admin/Default/1.6/universe_create_ports.php
- templates/Default/admin/Default/1.6/universe_create_sectors.php
* Allow empty fields in the "Number of Ports" field when creating ports.
* Allow editing a sector from the "Modify Sector" input regardless of what galaxy it is in.
* Minor cosmetic changes.
> Minor Uni Gen enhancements

- engine/Default/rankings_race.php
- engine/Default/rankings_race_death.php
- engine/Default/rankings_race_kills.php
- templates/Default/engine/Default/rankings_race.php
- templates/Default/engine/Default/rankings_race_death.php
- templates/Default/engine/Default/rankings_race_kills.php
Use `getColouredRaceName` to display the race name linked to the
respective council page.
> Link race ranking pages to council pages

- lib/Default/SmrWeapon.class.php
- lib/Default/WeightedRandom.class.php
I tweaked the weighted random code slightly.  I believe weapons will hit at their intended rate regardless of their accuracy with this change.
I also changed the code to state things in terms of affirmation.  A hit is true and a miss is false.  Hopefully this is more direct and easier to read.
> weapon hit code cleaning

- lib/Default/AbstractSmrAccount.class.php
- lib/Default/AbstractSmrLocation.class.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/AbstractSmrPort.class.php
- lib/Default/AbstractSmrShip.class.php
- lib/Default/ChessGame.class.php
- lib/Default/Council.class.php
- lib/Default/Distance.class.php
- lib/Default/DummyPlayer.class.php
- lib/Default/DummyShip.class.php
- lib/Default/Globals.class.php
- lib/Default/Plotter.class.php
- lib/Default/Rankings.class.php
- lib/Default/SmrAlliance.class.php
- lib/Default/SmrForce.class.php
- lib/Default/SmrGalaxy.class.php
- lib/Default/SmrGame.class.php
- lib/Default/SmrPlanet.class.php
- lib/Default/SmrPlayer.class.php
- lib/Default/SmrSector.class.php
- lib/Default/SmrShip.class.php
- lib/Default/SmrWeapon.class.php
- lib/Default/Template.class.php
- lib/Default/WeightedRandom.class.php
- lib/Default/message.functions.inc
- lib/Hunter Wars/SmrLocation.class.php
- tools/npc/npc.php
Major work on removing unnecessary references. See commit messages for details.
> Remove references

- lib/Default/ChessGame.class.php
- lib/Default/Routes/OneWayRoute.class.php
- lib/Default/SmrPlanetStructureType.class.php
- lib/Default/SmrPlanetType.class.php
- lib/Default/SmrShip.class.php
- lib/Default/smr.inc
> Misc fixes

- admin/Default/account_edit_processing.php
- engine/Default/alliance_message_add_processing.php
- engine/Default/alliance_roles_processing.php
- engine/Default/alliance_roster.php
- engine/Default/buy_ship_name_processing.php
- engine/Default/feature_request.php
- engine/Default/map_local.php
- htdocs/map_galaxy.php
- lib/Default/AbstractSmrAccount.class.php
- lib/Default/AbstractSmrPlayer.class.php
- lib/Default/AbstractSmrPort.class.php
- lib/Default/AbstractSmrShip.class.php
- lib/Default/SmrSector.class.php
- lib/Default/SmrSession.class.php
- templates/Default/engine/Default/includes/ForcesCombatResults.inc
- templates/Default/engine/Default/includes/SectorMap.inc
- tools/discord/commands/forces.php
Replaces ternary expressions with binary expressions by using the null
coalescing operator introduced in PHP 7. For example,
isset($x) ? $x : $y;
is replaced with
$x ?? $y;
> Use ?? operator to simplify expressions

- admin/Default/1.6/universe_create_sector_details.php
- admin/Default/manage_draft_leaders.php
- admin/Default/manage_post_editors.php
- engine/Default/course_plot.php
- engine/Default/galactic_post_past.php
- templates/Default/admin/Default/manage_draft_leaders.php
- templates/Default/admin/Default/manage_post_editors.php
- templates/Default/engine/Default/galactic_post_past.php
- templates/Default/engine/Default/includes/SectorMap.inc
This replaces some verbose processing of input. Some inputs need to
be renamed so that the request and var names are identical.
> Use SmrSession::getRequestVar for display pages

- docker-compose.yml
- engine/Default/contact_processing.php
* Set FQDN for smtp hostname to `hostname.local`.
* Don't spoof player e-mail addresses.
> Fix a couple SMTP issues

- admin/Default/account_edit.php
- admin/Default/account_edit_processing.php
- admin/Default/account_edit_search.php
- admin/Default/account_edit_search_processing.php
- lib/Default/AdminPermissions.class.php
- templates/Default/admin/Default/account_edit.php
- templates/Default/admin/Default/account_edit_search.php
* Break into two pages to simplify logic.
* Use placeholders for player renames.
> Improve account_edit.php

- engine/Default/bank_alliance_processing.php
- lib/Default/SmrAlliance.class.php
- tools/chat_helpers/channel_msg_money.php
Get the total credits in the alliance bank account by using the
`SmrAlliance::getAccount` method instead of a raw SQL query.
Also document the method since its name is a bit ambiguous.
> channel_msg_money.php: use SmrAlliance methods

- admin/Default/1.6/universe_create_galaxies.php
- admin/Default/1.6/universe_create_sector_details.php
- admin/Default/1.6/universe_create_sectors.php
- admin/Default/admin_message_send.php
- admin/Default/album_moderate.php
- admin/Default/anon_acc_view.php
- admin/Default/game_delete_confirm.php
- admin/Default/log_console_detail.php
- admin/Default/manage_draft_leaders.php
- admin/Default/manage_post_editors.php
- admin/Default/npc_manage.php
- admin/Default/permission_manage.php
- engine/Default/bank_anon_detail.php
- engine/Default/course_plot.php
- engine/Default/galactic_post_past.php
- engine/Default/preferences_confirm.php
- engine/Default/rankings_alliance_vs_alliance.php
- engine/Default/trader_search_result.php
- lib/Default/Request.class.php
- lib/Default/SmrGame.class.php
- lib/Default/SmrSession.class.php
- templates/Default/admin/Default/manage_draft_leaders.php
- templates/Default/admin/Default/manage_post_editors.php
- templates/Default/admin/Default/npc_manage.php
- templates/Default/engine/Default/course_plot.php
- templates/Default/engine/Default/galactic_post_past.php
Some pages were raising exceptions after the addition of strict types (attributes and function interfaces). These changes should address those issues.
> SmrGame fixes for strict types

- admin/Default/word_filter_add.php
- admin/Default/word_filter_del.php
- engine/Default/bar_galmap_buy.php
- engine/Default/bar_ticker_buy.php
- engine/Default/bar_ticker_buy_processing.php
- engine/Default/message_blacklist_add.php
- engine/Default/message_blacklist_del.php
- engine/Default/trader_search.php
- engine/Default/trader_search_result.php
- lib/Default/SmrPlayer.class.php
- templates/Default/admin/Default/word_filter.php
- templates/Default/engine/Default/bar_galmap_buy.php
- templates/Default/engine/Default/bar_ticker_buy.php
- templates/Default/engine/Default/message_blacklist.php
Fix some errors and improve some form validation related to the addition of the Request class and type strictness. See individual commit messages for details.
> Clean up some Request-related code

- admin/Default/1.6/universe_create_locations.php
- admin/Default/1.6/universe_create_planets.php
- admin/Default/1.6/universe_create_ports.php
- templates/Default/admin/Default/1.6/universe_create_locations.php
- templates/Default/admin/Default/1.6/universe_create_planets.php
- templates/Default/admin/Default/1.6/universe_create_ports.php
In the "Create {Locations,Planets,Ports}" sub-pages, instead of just
saying what galaxy we're working on, turn it into a dropdown where you
can quickly navigate to other galaxies.
> Uni Gen: add dropdown to quickly switch galaxies

- engine/Default/alliance_invite_player.php
- lib/Default/AbstractSmrAccount.class.php
Use `array_key_exists` instead of `in_array` + `array_keys`.
It is more precise and likely more performant.
No functionality changes.
> Fix misuse of in_array

- engine/Default/bug_report_processing.php
* Include "Subject" field in the message
* Provide confirmation that the report was submitted
> Improve "Report A Bug" form

- engine/Default/planet_ownership_processing.php
- templates/Default/engine/Default/planet_main.php
- templates/Default/engine/Default/planet_ownership.php
* Fix some HTML formatting in "Planet Main"
* Fix some issues related to passwords in "Planet Ownership"
> Minor changes to planet pages

- htdocs/map_warps.php
- templates/Default/engine/Default/includes/Head.inc
- templates/Default/login/login.php
Upgrade jQuery and jQuery-UI to the latest versions.
* Change CDN to consistently use `code.jquery.com`.
* Use HTTPS protocol consistently.
* Remove unused jQuery-UI CSS link.
No code changes were necessary, likely because we're using very basic functionality from these libraries.
> Upgrade jQuery

- engine/Default/game_join_processing.php
- tools/npc/npc.php
Some existing issues became blocking when strict-typing was added. This PR addresses those issues.
> Get NPCs working again

- admin/Default/newsletter_send.php
- engine/Default/alliance_stat.php
- engine/Default/bar_gambling_processing.php
- lib/Default/smr.inc
- templates/Default/admin/Default/newsletter_send.php
- templates/Default/engine/Default/alliance_stat.php
These are replaced by writing out the HTML explicitly, which is the
purpose of the template files (to avoid writing HTML in PHP).
> Remove some functions that write HTML in PHP

- admin/Default/1.6/universe_create_sectors.php
- templates/Default/admin/Default/1.6/universe_create_sectors.php
This mimicks the behavior of the Galaxy Map, and is useful for getting
a different perspective of the galaxy layout.
> Uni Gen: add option to recenter sector map

- engine/Default/bar_gambling_processing.php
- lib/Default/PlayingCard.class.php
> Blackjack fixes

- htdocs/ship_list.php
- htdocs/weapon_list.php
- templates/Default/ship_list.php
- templates/Default/weapon_list.php
No display changes. See commit messages for details.
> Clean up ship and weapon list pages

- db/patches/V1_6_65_03__update_lvl5_weapons.sql
- lib/Default/AbstractSmrPort.class.php
- templates/Default/engine/Default/port_attack.php
* Increase trade profit by 5%
* Decrease port raid profit by 10%
* Decrease Nuke/HHG accuracy from 35% -> 30%
> Balance changes for Game 136

- engine/Default/shop_ship.php
- templates/Default/engine/Default/shop_ship.php
* Redesign invoice for clarity.
* Don't explicitly enumerate hardware types.
An example where you get a refund:
An example where you have to pay:
> shop_ship.php: revamp details view

- engine/Default/bank_alliance_processing.php
- engine/Default/bank_anon_detail_processing.php
- engine/Default/bank_personal_processing.php
- engine/Default/cargo_dump_processing.php
- engine/Default/course_plot_nearest_processing.php
- engine/Default/course_plot_processing.php
- engine/Default/death_processing.php
- engine/Default/forces_drop_processing.php
- engine/Default/game_play_processing.php
- engine/Default/leave_newbie_processing.php
- engine/Default/planet_construction_processing.php
- engine/Default/planet_defense_processing.php
- engine/Default/planet_financial_processing.php
- engine/Default/planet_land_processing.php
- engine/Default/planet_launch_processing.php
- engine/Default/planet_ownership_processing.php
- engine/Default/planet_stockpile_processing.php
- engine/Default/port_loot_processing.php
- engine/Default/port_payout_processing.php
- engine/Default/sector_jump_processing.php
- engine/Default/shop_goods.php
- engine/Default/shop_goods_processing.php
- engine/Default/shop_hardware_processing.php
- engine/Default/shop_ship_processing.php
- engine/Default/shop_weapon_processing.php
- lib/Default/AbstractSmrPlayer.class.php
This is a wrapper around SmrAccount::log that sets the sector ID
automatically.
It has two main benefits:
1. Simplfies calls to the admin logging interface.
2. Reduces explicit dependence on the account for player actions.
> Add SmrPlayer::log

- config/discord/config.specific.sample.php
- tools/discord/GameLink.inc
- tools/discord/bot.php
Bug fix:
* Fix broken commands in guild (public) channels.
Enhancements:
* Add ability to set logging level in the config file.
* Add listening presence to Autopilot.
* Add customized bot description in help text.
> Discordbot improvements and fixes

- engine/Default/planet_attack_processing.php
- lib/Default/SmrPlanet.class.php
- templates/Default/engine/Default/planet_financial.php
* Remove `isClaimed` (duplicate of `hasOwner`).
* Rename `removeClaimed` to `removeOwner` (since all other similar
method names refer to the "owner").
> SmrPlanet: clean up Owner methods

- lib/Default/SmrAlliance.class.php
Adds type-hints for function interfaces and typed class properties.
> SmrAlliance: add types

- lib/Default/AbstractSmrLocation.class.php
Adds type-hints for function interfaces and typed class properties.
Minor internal changes:
* Some functions using `false` for a default argument value now use
`null` instead. This is necessary to use typed arguments.
> SmrLocation: add types

- admin/Default/1.6/universe_create_save_processing.php
- lib/Default/AbstractSmrLocation.class.php
- lib/Default/SmrSector.class.php
* Avoid database error when admin adds the same location to a sector twice.
* Fix inefficiency in editing sector locations.
> Fixes for editing sector locations

- .travis.yml
- composer.json
- docker-compose.yml
* Minor changes to the composer.json scripts for more flexible workflow support.
* Fix Travis test timeouts.
* Use the sample config file when running tests.
> Build and test config updates

- src/engine/Default/rankings_alliance_death.php
- src/engine/Default/rankings_alliance_experience.php
- src/engine/Default/rankings_alliance_kills.php
- src/engine/Default/rankings_alliance_profit.php
- src/engine/Default/rankings_player_assists.php
- src/engine/Default/rankings_player_death.php
- src/engine/Default/rankings_player_experience.php
- src/engine/Default/rankings_player_kills.php
- src/engine/Default/rankings_player_profit.php
- src/engine/Default/rankings_race.php
- src/engine/Default/rankings_race_death.php
- src/engine/Default/rankings_race_kills.php
- src/engine/Default/rankings_sector_kill.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/Rankings.class.php
- src/templates/Default/engine/Default/rankings_race.php
- src/templates/Default/engine/Default/rankings_race_death.php
- src/templates/Default/engine/Default/rankings_race_kills.php
> Improvements to ranking page processing

- src/engine/Default/history_games_news.php
- src/engine/Default/news_read.php
- src/engine/Default/news_read_advanced.php
Continue to replace raw access to `$_REQUEST` with the `Request` class.
> More uses for the Request class

- src/admin/Default/1.6/universe_create_save_processing.php
- src/bootstrap.php
- src/engine/Default/bar_buy_drink_processing.php
- src/engine/Default/sector_jump_processing.php
- src/engine/Default/shop_goods.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrCombatDrones.class.php
- src/lib/Default/SmrForce.class.php
- src/lib/Default/SmrGalaxy.class.php
- src/lib/Default/SmrMines.class.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrScoutDrones.class.php
- src/lib/Default/SmrShip.class.php
- src/lib/Default/WeightedRandom.class.php
- src/lib/Default/shop_goods.inc.php
- src/tools/npc/npc.php
* Use `rand` instead of `mt_rand`.
* Add function `array_rand_values` since no such builtin function exists.
> Random function refactoring

- db/patches/V1_6_65_12__fix_boolean_column.sql
- src/engine/Default/alliance_message.php
- src/engine/Default/alliance_message_add_processing.php
- src/engine/Default/news_read_advanced.php
- src/lib/Default/Globals.class.php
> Fix minor regressions

- src/admin/Default/npc_manage_processing.php
- src/engine/Default/game_join_processing.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Smr/UserException.php
- test/SmrTest/lib/DefaultGame/AbstractSmrPlayerIntegrationTest.php
And some minor improvements to the function. See commit messages for details.
> Unit test SmrPlayer::createPlayer

- .github/dependabot.yml
- db/Dockerfile
- docker-compose.yml
- src/bootstrap.php
- src/engine/Default/album_edit_processing.php
- src/lib/Default/DummyShip.class.php
- src/lib/Default/bar.inc.php
> More miscellaneous fixes

- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrCombatDrones.class.php
- src/lib/Default/SmrForce.class.php
- src/lib/Default/SmrMines.class.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrScoutDrones.class.php
- src/lib/Default/SmrWeapon.class.php
> Remove unused weapon functions

- src/engine/Default/combat_simulator.php
- src/engine/Default/forces_attack_processing.php
- src/engine/Default/planet_attack_processing.php
- src/engine/Default/port_attack_processing.php
- src/engine/Default/trader_attack_processing.php
- src/lib/Default/AbstractSmrCombatWeapon.class.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/AbstractSmrPort.class.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/DummyPlayer.class.php
- src/lib/Default/SmrCombatDrones.class.php
- src/lib/Default/SmrForce.class.php
- src/lib/Default/SmrMines.class.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrScoutDrones.class.php
- src/lib/Default/SmrWeapon.class.php
- src/templates/Default/engine/Default/includes/ForceTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/ForcesCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlanetCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PlanetTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PortCombatResults.inc.php
- src/templates/Default/engine/Default/includes/PortTraderTeamCombatResults.inc.php
- src/templates/Default/engine/Default/includes/TraderTeamCombatResults.inc.php
> Remove references from combat code

- src/engine/Default/planet_construction_processing.php
- src/lib/Default/SmrPlanet.class.php
- src/lib/Default/SmrPlanetType.class.php
- src/lib/Default/smr.inc.php
- src/templates/Default/engine/Default/planet_construction.php
- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/PhpFileInspectionTest.php
- test/SmrTest/lib/DefaultGame/AbstractSmrPlayerIntegrationTest.php
- test/SmrTest/lib/DefaultGame/MySqlDatabaseIntegrationTest.php
- test/SmrTest/lib/DefaultGame/RequestTest.php
- test/SmrTest/lib/DefaultGame/SmrPlanetIntegrationTest.php
* Rework `createPlanet`, `exists`, and `canBuild`.
* Add start of a unit test.
* Add typed properties and type hints.
> Improvements to SmrPlanet

- src/bootstrap.php
- src/engine/Default/alliance_invite_accept_processing.php
- src/engine/Default/alliance_join_processing.php
- src/engine/Default/alliance_roster.php
- src/lib/Default/AbstractSmrAccount.class.php
- src/lib/Default/Distance.class.php
- src/lib/Default/SmrAlliance.class.php
- src/lib/Smr/Container/DiContainer.php
- src/templates/Default/engine/Default/alliance_roster.php
- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/Container/DiContainerTest.php
- test/SmrTest/MySqlPropertiesTest.php
- test/SmrTest/lib/DefaultGame/AbstractSmrAccountIntegrationTest.php
- test/SmrTest/lib/DefaultGame/AbstractSmrPlayerIntegrationTest.php
- test/SmrTest/lib/DefaultGame/MySqlDatabaseIntegrationTest.php
- test/SmrTest/lib/DefaultGame/RequestTest.php
- test/SmrTest/lib/DefaultGame/SmrPlanetIntegrationTest.php
> Minor cleanup in tests, docs, and interfaces

- src/tools/irc/irc.php
Since we are calling `$db->close()` at the end of each polling cycle,
we need to reconnect to the database before making any queries (by
calling `MySqlDatabase::getNewInstance`).
The simplest way to do this is to move the `irc_seen` cleanup to the
beginning of the reconnect loop, since we probably want to reset the
`irc_seen` stats at that point anyway (as we may have disconnected).
Also simplified the logical layout of the reconnect loop (without
changing functionality).
> irc.php: reconnect to database after IRC reconnect

- src/bootstrap.php
- src/htdocs/loader.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Session.php
- src/tools/npc/npc.php
- test/SmrTest/lib/DefaultGame/SessionIntegrationTest.php
> Improve robustness of Session and exception logging

- src/admin/Default/1.6/upload_smr_file_processing.php
- src/admin/Default/album_moderate.php
- src/admin/Default/changelog.php
- src/admin/Default/notify_view.php
- src/admin/Default/permission_manage.php
- src/engine/Default/album_edit_processing.php
- src/engine/Default/alliance_message.php
- src/engine/Default/bank_alliance_exempt_processing.php
- src/engine/Default/bank_report.php
- src/engine/Default/bar_buy_drink_processing.php
- src/engine/Default/bounty_place_confirm_processing.php
- src/engine/Default/buy_ship_name_processing.php
- src/engine/Default/combat_log_list.php
- src/engine/Default/combat_simulator.php
- src/engine/Default/forces_attack_processing.php
- src/engine/Default/history_games_detail.php
- src/engine/Default/history_games_hof.php
- src/engine/Default/rankings_alliance_vs_alliance.php
- src/engine/Default/rankings_sector_kill.php
- src/engine/Default/shop_ship.php
- src/htdocs/album/album_comment.php
- src/htdocs/ship_list.php
- src/lib/Default/DummyPlayer.class.php
> Fix phpstan warnings

- src/lib/Smr/Template.php
- test/SmrTest/TestUtils.php
- test/SmrTest/lib/DefaultGame/TemplateTest.php
* Add typehints
* Add unit test
* Fix bug causing non-fillable input types to prevent AJAX updates
> Template enhancements

- db/patches/V1_6_66_18__add_nmv_restriction.sql
- src/engine/Default/forces_drop_processing.php
- src/htdocs/ship_list.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrForce.class.php
- src/templates/Default/engine/Default/includes/SectorForces.inc.php
> Miscellaneous Smr{Ship,Force} changes

- src/engine/Default/alliance_remove_member.php
- src/engine/Default/trader_status.php
- src/lib/Default/AbstractSmrPlayer.class.php
* Querying `bounty` in trader_status.php, replaced with `SmrPlayer::getClaimableBounties`.
* Querying `level` in trader_status.php, replaced with `SmrPlayer::getNextLevel`.
* Querying `player` in alliance_remove_member.php, replaced with `SmrAlliance::getMembers`.
> Replace a few database calls with methods

- docker-compose.yml
- phpstan.neon.dist
- src/lib/Smr/Template.php
- src/templates/Default/engine/Default/bank_alliance.php
- src/templates/Default/engine/Default/bar_main.php
- src/templates/Default/engine/Default/buy_ship_name_preview.php
- src/templates/Default/engine/Default/donation.php
* Switch to config file instead of command-line options.
* Add a handful of stricter analyses.
* Fix inconsistent function/class capitalization.
> PHPStan improvements

- src/lib/Default/Plotter.class.php
- src/lib/Default/SmrSector.class.php
- test/SmrTest/lib/DefaultGame/SmrSectorTest.php
> Fixes to SmrSector

- src/admin/Default/1.6/drag_location.php
- src/admin/Default/1.6/drag_planet.php
- src/admin/Default/1.6/universe_create_sectors.php
- src/htdocs/css/shared.css
- src/htdocs/js/ajax.js
- src/htdocs/js/chess_play.js
- src/htdocs/js/uni_gen.js
- src/lib/Default/AbstractSmrLocation.class.php
- src/templates/Default/admin/Default/1.6/universe_create_sectors.php
- src/templates/Default/engine/Default/chess_play.php
- src/templates/Default/engine/Default/includes/EndingJavascript.inc.php
- src/templates/Default/engine/Default/includes/SectorMap.inc.php
This new feature allows us to move locations and planets to different
sectors in the Uni Gen (instead of the laborious task of going into
the details page for one sector, removing the location, then going to
the details of another sector and adding that location). The Uni Gen
should be a much more pleasant experience with this change.
> Uni Gen: add ability to drag and drop locations

- db/patches/V1_6_66_21__drop_bar_drink.sql
- src/engine/Default/bar_buy_drink_processing.php
- src/lib/Default/missions.inc.php
- src/lib/Smr/BarDrink.php
- test/SmrTest/lib/DefaultGame/BarDrinkTest.php
* Many new drink names
* Rename "Salvene Swamp Water" to "Salvene Swamp Soda" to alleviate mission confusion
* Replace the `bar_drink` table with a `BarDrink` class
* Change some bar drink flavor text
> Rework bar drinks

- src/engine/Default/bounty_claim.php
- src/engine/Default/bounty_place.php
- src/engine/Default/bounty_place_confirm.php
- src/engine/Default/government.php
- src/engine/Default/military_payment_claim.php
- src/engine/Default/news_read.php
- src/engine/Default/news_read_advanced.php
- src/engine/Default/news_read_current.php
- src/engine/Default/underground.php
- src/lib/Default/AbstractMenu.class.php
- src/lib/SemiWars/Menu.class.php
* Fix var error in news by passing game ID to `Menu::news`.
* Improve encapsulation of `Menu::headquarters` by passing location type ID.
> Menu fixes

- .github/workflows/run-tests.yml
- [Release notes](https://github.com/codecov/codecov-action/releases)
- [Changelog](https://github.com/codecov/codecov-action/blob/master/CHANGELOG.md)
- [Commits](codecov/codecov-action@v1...v2.0.0)
> Upgrade codecov-action from v1 to v2

- src/engine/Default/rankings_alliance_death.php
- src/engine/Default/rankings_alliance_experience.php
- src/engine/Default/rankings_alliance_kills.php
- src/engine/Default/rankings_alliance_profit.php
- src/engine/Default/rankings_player_assists.php
- src/engine/Default/rankings_player_death.php
- src/engine/Default/rankings_player_experience.php
- src/engine/Default/rankings_player_kills.php
- src/engine/Default/rankings_player_npc_kills.php
- src/engine/Default/rankings_player_profit.php
- src/engine/Default/rankings_race.php
- src/engine/Default/rankings_race_death.php
- src/engine/Default/rankings_race_kills.php
- src/engine/Default/rankings_sector_kill.php
- src/lib/Default/AbstractMenu.class.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/Rankings.class.php
- src/templates/Default/engine/Default/includes/AllianceRankings.inc.php
- src/templates/Default/engine/Default/includes/PlayerRankings.inc.php
- src/templates/Default/engine/Default/includes/RaceRankings.inc.php
- src/templates/Default/engine/Default/includes/SectorKillList.inc.php
- src/templates/Default/engine/Default/rankings_player_npc_kills.php
- src/templates/Default/engine/Default/rankings_race.php
- src/templates/Default/engine/Default/rankings_race_death.php
- src/templates/Default/engine/Default/rankings_race_kills.php
* Refactor to perform all rank computations with a single SQL query for consistency and robustness.
* Add "NPC Kill Rankings" page.
* Refactor race rankings template to avoid code duplication.
> Rank page improvements

- src/engine/Default/game_join_processing.php
- src/engine/Default/preferences_processing.php
- src/lib/Smr/DisplayNameValidator.php
- test/SmrTest/lib/DefaultGame/DisplayNameValidatorTest.php
* Disallow "[NPC]" in name
* Add `DisplayNameValidator` class to reduce code duplication and simplify logic
> Display name validation

- src/engine/Default/bar_gambling_processing.php
- src/lib/Smr/Blackjack/Card.php
- src/lib/Smr/Blackjack/Deck.php
- src/lib/Smr/Blackjack/Hand.php
- test/SmrTest/lib/DefaultGame/Blackjack/CardTest.php
- test/SmrTest/lib/DefaultGame/Blackjack/DeckTest.php
- test/SmrTest/lib/DefaultGame/Blackjack/HandTest.php
* Move them into the `Smr` namespace
* Simplify some functions and interfaces
* Add unit tests
> Refactor Blackjack classes

- Dockerfile
- config/env.sample
- docker-compose.yml
- test/env
* Update Dockerfile dependencies (xdebug and Composer)
* Fix the `pma` service for beta.smrealms.de
* Make Composer update more verbose
* Simpler scaffolding for the `smr-test` services
> Various dev-ops updates

- src/engine/Default/vote_link.php
- src/htdocs/vote_link_callback.php
- src/lib/Default/VoteSite.class.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/VoteSite.php
- test/SmrTest/lib/DefaultGame/VoteSiteIntegrationTest.php
No external functionality changes. See commit messages for details.
> Refactor VoteSite class

- src/admin/Default/npc_manage_processing.php
- src/engine/Default/alliance_invite_accept_processing.php
- src/engine/Default/alliance_message.php
- src/engine/Default/chat_sharing.php
- src/engine/Default/course_plot_processing.php
- src/engine/Default/hall_of_fame_player_detail.php
- src/engine/Default/message_blacklist_add.php
- src/engine/Default/trader_search_result.php
- src/engine/Draft/alliance_pick.php
- src/htdocs/login_create_processing.php
- src/htdocs/login_social_processing.php
- src/htdocs/map_galaxy.php
- src/lib/Default/AbstractSmrPlayer.class.php
- src/lib/Default/Globals.class.php
- src/lib/Default/SmrAlliance.class.php
- src/lib/Default/SmrSector.class.php
- src/lib/Default/hof.inc.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Exceptions/AllianceNotFound.php
- src/tools/discord/GameLink.class.php
- src/tools/irc/channel_msg.php
- src/tools/irc/irc.php
- src/tools/npc/npc.php
- test/SmrTest/lib/DefaultGame/SmrAllianceIntegrationTest.php
* Add AllianceNotFound exception
* Omit exception variable when unused
> Exception improvements

- src/engine/Default/admin/admin_tools.php
- src/engine/Default/admin/permission_manage.php
- src/lib/Smr/AdminPermissions.php
- src/lib/Smr/Template.php
- src/templates/Default/engine/Default/admin/admin_tools.php
- src/templates/Default/engine/Default/admin/permission_manage.php
- src/templates/Default/engine/Default/game_play.php
- test/SmrTest/lib/DefaultGame/AdminPermissionsTest.php
- test/SmrTest/lib/DefaultGame/TemplateTest.php
> Add some miscellaneous testing

- .github/workflows/run-tests.yml
- Dockerfile
- src/config.php
- src/engine/Default/cargo_dump_processing.php
- src/engine/Default/planet_attack_processing.php
- src/engine/Default/planet_land_processing.php
- src/engine/Default/port_attack_processing.php
- src/engine/Default/trader_attack_processing.php
- src/lib/Default/AbstractSmrShip.class.php
- src/lib/Default/SmrPlanetType.class.php
- src/lib/Default/SmrShipType.class.php
- src/templates/Default/engine/Default/cargo_dump.php
- src/templates/Default/engine/Default/planet_attack.php
- src/templates/Default/engine/Default/planet_examine.php
- src/templates/Default/engine/Default/trader_examine.php
> Miscellaneous infrastructure enhancements and bugfixes

- config/npc/config.specific.sample.php
- db/patches/V1_6_67_03__truncate_invalidated_tables.sql
- docker-compose.yml
- src/engine/Default/admin/npc_manage_processing.php
- src/engine/Default/shop_goods_processing.php
- src/lib/Default/shop_goods.inc.php
- src/tools/npc/npc.php
> Miscellaneous updates and fixes

- Dockerfile
* Composer 2.2.4 -> 2.2.6
* Xdebug 3.1.2 -> 3.1.3
> Dockerfile: update Composer and Xdebug

- src/lib/Default/Page.class.php
- src/lib/Default/help.inc.php
- src/lib/Default/smr.inc.php
- src/tools/discord/GameLink.class.php
- src/tools/npc/chess.php
- test/SmrTest/lib/DefaultGame/AbstractSmrShipTest.php
> Coding style fixes

- docker-compose.yml
- phpunit.xml
- src/lib/autoload.inc.php
* Fix autoloader error
* Fix colors
> PHPUnit fixes

- src/lib/Default/AbstractSmrPlayer.php
- src/lib/Default/AbstractSmrPort.php
- src/lib/Default/DummyPlayer.php
- src/lib/Default/SmrWeapon.php
No functionality changes. See commit messages for details.
> Miscellaneous phpcs fixes

- phpcs.xml
- src/lib/Default/SmrGalaxy.php
- src/lib/Smr/Request.php
> Fix some phpcs warnings

- phpcs.xml
- phpstan.neon.dist
- src/engine/Default/cargo_dump_processing.php
- src/engine/Default/planet_stockpile_processing.php
- src/engine/Default/shop_goods.php
- src/engine/Default/shop_goods_processing.php
- src/lib/Default/AbstractSmrPort.php
- src/lib/Default/AbstractSmrShip.php
- src/lib/Default/DummyPlayer.php
- src/lib/Default/SmrPlanet.php
- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/SocialLogin/Google.php
- src/lib/Smr/SocialLogin/Twitter.php
- src/tools/npc/NpcActor.php
- test/SmrTest/lib/DefaultGame/SmrPlanetIntegrationTest.php
PHPStan level 2 provides:
> unknown methods checked on all expressions (not just $this), validating PHPDocs
> Increase PHPStan level from 1 -> 2

- phpstan.neon.dist
- src/engine/Default/admin/combat_simulator.php
- src/engine/Default/admin/combat_simulator_processing.php
- src/engine/Default/admin/edit_dummys.php
- src/engine/Default/admin/edit_dummys_processing.php
- src/engine/Default/news_read_advanced.php
- src/lib/Default/AbstractSmrPlayer.php
- src/lib/Default/DummyPlayer.php
- src/lib/Default/DummyShip.php
- src/lib/Default/SmrAlliance.php
- src/lib/Default/SmrInvitation.php
- src/lib/Default/SmrPlanet.php
- src/lib/Default/SmrSector.php
- src/lib/Smr/Discord/DatabaseCommand.php
- src/lib/Smr/Discord/PlayerLink.php
- src/templates/Default/engine/Default/admin/combat_simulator.php
- src/templates/Default/engine/Default/admin/edit_dummys.php
- src/templates/Default/engine/Default/admin/includes/CombatSimTeamDetails.inc.php
- src/tools/npc/NpcActor.php
> Increase PHPStan level from 2 -> 3

- src/engine/Default/admin/unigen/universe_create_save_processing.php
To find a valid sector to add locations/warps/planets/ports, we were
looping over all sectors in a galaxy and checking each sector against
a set of conditions.
Since we were not removing invalid sectors from the list as they were
checked, we could run into two problems:
1. Inefficiency, because the same (invalid) sector could be selected
randomly any number of times before finally selecting a valid one.
2. Infinite loops, because there may be _no_ valid sectors that can
satisfy the restrictions for selecting a sector.
To fix this, we now remove sectors from the list of eligible sectors
when we determine them to be ineligible. Then when the list of eligible
sectors becomes empty, we throw a UserError.
> UniGen: fix infinite loops when populating sectors

- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/Chess/ChessPiece.php
- src/lib/Smr/Chess/Colour.php
- src/tools/npc/chess.php
- test/SmrTest/lib/DefaultGame/Chess/ColourTest.php
> Miscellaneous chess improvements

- composer.json
- src/lib/Smr/Chess/ChessGame.php
- src/lib/Smr/Routes/RouteGenerator.php
> Remove some unneeded code

- src/engine/Default/admin/notify_reply.php
- src/engine/Default/admin/notify_view.php
- src/engine/Default/bank_alliance.php
- src/engine/Default/message_send.php
- src/engine/Default/message_view.php
- src/engine/Default/planet_construction_processing.php
- src/engine/Default/shop_goods_processing.php
- src/engine/Default/shop_hardware_processing.php
- src/engine/Default/weapon_reorder_processing.php
- src/engine/Draft/alliance_pick_processing.php
- src/lib/Default/AbstractSmrPlayer.php
- src/lib/Default/AbstractSmrPort.php
- src/lib/Default/Council.php
- src/lib/Default/Globals.php
- src/lib/Default/SmrPlanet.php
- src/lib/Default/SmrSector.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Messages.php
- src/lib/Smr/Template.php
- src/lib/Smr/VoteLink.php
- src/templates/Default/engine/Default/admin/notify_reply.php
- src/templates/Default/engine/Default/bank_alliance.php
- src/templates/Default/engine/Default/includes/CommonMessageSend.inc.php
- src/templates/Default/engine/Default/includes/Head.inc.php
- test/SmrTest/BaseIntegrationSpec.php
- test/SmrTest/lib/DefaultGame/SmrSectorTest.php
There is a lot more to do, but this is a start. Some of the PHPStan level 7 issues would be fixed better with a major refactoring, or with some work in progress in PHPStan itself.
> Partially fix PHPStan level 7 warnings

- src/engine/Default/bar_gambling.php
- src/engine/Default/bar_gambling_bet.php
- src/engine/Default/bar_gambling_processing.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Blackjack/Result.php
- src/lib/Smr/Blackjack/Table.php
- src/templates/Default/engine/Default/bar_gambling.php
- test/SmrTest/lib/DefaultGame/Blackjack/TableTest.php
* Rename "Bank" to "Dealer".
* Add Blackjack `Table` class and `Result` enum.
* Convert engine page to standard template design (and remove AJAX hacks).
> Blackjack improvements

- src/bootstrap.php
- src/engine/Default/error.php
- src/lib/Default/planet.inc.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Template.php
* Convert all user errors into `UserError` exceptions.
* Fix automatically forwarding to error pages during AJAX page refresh errors.
* Remove undisplayed data tracking in the Template destructor.
* Add Sector ID to exception log.
> Error handling enhancements

- src/htdocs/js/ajax.js
- src/htdocs/js/chess_play.js
- src/htdocs/js/uni_gen.js
- src/htdocs/loader.php
- src/lib/Default/smr.inc.php
- src/lib/Smr/Session.php
- test/SmrTest/lib/DefaultGame/SessionIntegrationTest.php
> Ajax updates

- composer.json
This fixes the font size of the HTML display.
> composer.json: update php-code-coverage to 9.2.20

- src/htdocs/login_processing.php
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Exceptions/PathNotFound.php
- src/lib/Smr/Location.php
- src/lib/Smr/Plotter.php
- src/lib/Smr/Port.php
- src/lib/Smr/Sector.php
- src/lib/Smr/SocialLogin/Facebook.php
- src/lib/Smr/SocialLogin/Google.php
- src/lib/Smr/SocialLogin/SocialLogin.php
- src/pages/Player/CargoDumpProcessor.php
- src/pages/Player/PlotCourseConventionalProcessor.php
- src/pages/Player/PlotCourseNearestProcessor.php
- src/pages/Player/SectorJumpCalculate.php
- src/pages/Player/SectorJumpProcessor.php
- src/tools/npc/NpcActor.php
- src/tools/npc/npc.php
> Gameplay-related fixes for Game 149

- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Account.php
- src/lib/Smr/CouncilVoting.php
- src/lib/Smr/Database.php
- src/lib/Smr/HallOfFame.php
- src/lib/Smr/Request.php
- src/lib/Smr/SectorLock.php
- src/lib/Smr/Session.php
- src/pages/Admin/IpViewResults.php
- src/pages/Player/AllianceMessageBoardDeleteReplyProcessor.php
- src/pages/Player/ChatSharingProcessor.php
- src/tools/chat_helpers/channel_msg_op_info.php
- src/tools/chat_helpers/channel_msg_seedlist.php
- src/tools/irc/channel_msg_op.php
- test/SmrTest/lib/DatabaseIntegrationTest.php
- test/SmrTest/lib/RequestTest.php
> Database: restrict escapeNumber type to int|float

- src/htdocs/login_create_processing.php
- src/htdocs/resend_password_processing.php
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Account.php
- src/lib/Smr/Database.php
- src/pages/Account/ContactFormProcessor.php
- src/pages/Account/Preferences.php
- src/pages/Account/PreferencesTransferConfirm.php
- src/pages/Admin/AlbumModerateProcessor.php
- src/templates/Default/engine/Default/game_join.php
- src/templates/Default/engine/Default/preferences.php
- src/templates/Default/engine/Default/preferences_confirm.php
- test/SmrTest/lib/AbstractPlayerIntegrationTest.php
- test/SmrTest/lib/AccountTest.php
- test/SmrTest/lib/DatabaseIntegrationTest.php
> Reserve player names with HoF name

- db/patches/V1_6_68_13__strict_sql_chess.sql
- src/lib/Smr/AbstractPlayer.php
- src/lib/Smr/Account.php
- src/lib/Smr/Chess/ChessGame.php
- src/pages/Player/Chess/MatchStartProcessor.php
> More miscellaneous fixes for game 150

- src/lib/Smr/AbstractPlayer.php
- src/pages/Player/ExaminePlanet.php
- test/SmrTest/lib/AbstractPlayerIntegrationTest.php
> Fix Player::sameAlliance

- .github/actions/api-docs/Dockerfile
- Dockerfile
- api-docs/Dockerfile
> Update to PHP 8.3

- .github/actions/api-docs/Dockerfile
- Dockerfile
- api-docs/Dockerfile
Closes #1817, closes #1818, closes #1819.
> Update PHP from 8.3.2 to 8.3.6

- Dockerfile
* Xdebug 3.3.1 -> 3.3.2
* Composer 2.6.6 -> 2.7.4
> Dockerfile: update dependencies

- src/pages/Admin/UniGen/EditGalaxy.php
- src/templates/Default/engine/Default/admin/unigen/universe_create_sectors.php
The back button has the game name in it, because it would take up too much space as a page topic.
> EditGalaxy: add back button and prev/next galaxy buttons

- .github/workflows/build-live.yml
- .github/workflows/run-tests.yml
The live server will be updated to 24.04 shortly to match.
> Update CI platform from ubuntu 22.04 to 24.04
